### ISSUE TITLE
Trying out on a random java file

### ISSUE THREAD

**Issue by bk322** [joaotavora/eglot#185] opened 2018-12-13 05:26 UTC
After calling `eglot` on java file at `/home/bkheyfets/dev/java/hellofx-ide-eclipse-modular-maven2/hellofx/src/main/java/org/openjfx/MainApp.java`:

```
Debugger entered--Lisp error: (file-missing "Removing directory" "No such file or directory" "/tmp/ome/bkheyfets/dev/java/hellofx-ide-eclipse-mo...")
  signal(file-missing ("Removing directory" "No such file or directory" "/tmp/ome/bkheyfets/dev/java/hellofx-ide-eclipse-mo..."))
  files--force(nil delete-directory-internal "/tmp/ome/bkheyfets/dev/java/hellofx-ide-eclipse-mo...")
  delete-directory("/tmp/ome/bkheyfets/dev/java/hellofx-ide-eclipse-mo...")
  flymake-proc--safe-delete-directory("/tmp/ome/bkheyfets/dev/java/hellofx-ide-eclipse-mo...")
  flymake-proc--delete-temp-directory("/tmp/home/bkheyfets/dev/java/hellofx-ide-eclipse-m...")
  flymake-proc-simple-java-cleanup()
  #f(compiled-function () #<bytecode 0x1caac31>)()
  flymake-proc-legacy-flymake(#f(compiled-function (&rest args) #<bytecode 0x1caac25>))
  apply(flymake-proc-legacy-flymake #f(compiled-function (&rest args) #<bytecode 0x1caac25>) nil)
  flymake--run-backend(flymake-proc-legacy-flymake nil)
  #f(compiled-function (backend) #<bytecode 0x1bc5c09>)(flymake-proc-legacy-flymake)
  run-hook-wrapped(#f(compiled-function (backend) #<bytecode 0x1bc5c09>) flymake-proc-legacy-flymake)
  flymake-start(t)
  flymake-mode(1)
  eglot--managed-mode(1)
  eglot--managed-mode-onoff(#<eglot-lsp-server eglot-lsp-server-1ea2be0> t)
  eglot--maybe-activate-editing-mode(#<eglot-lsp-server eglot-lsp-server-1ea2be0>)
  #f(compiled-function () #<bytecode 0x1ea2c19>)()
  eglot--call-with-interface((InitializeResult (:capabilities)) (:capabilities (:textDocumentSync (:openClose t :change 2 :willSave t :willSaveWaitUntil t :save (:includeText t)) :hoverProvider t :completionProvider (:resolveProvider t :triggerCharacters ["." "@" "#" "*"]) :signatureHelpProvider (:triggerCharacters ["("]) :definitionProvider t :typeDefinitionProvider t :implementationProvider t :referencesProvider t :documentHighlightProvider t :documentSymbolProvider t :workspaceSymbolProvider t :codeActionProvider t :codeLensProvider (:resolveProvider t) :documentFormattingProvider t :documentRangeFormattingProvider t :documentOnTypeFormattingProvider (:firstTriggerCharacter ";" :moreTriggerCharacter ["\n" "}"]) :renameProvider (:prepareProvider t) :executeCommandProvider (:commands ["java.edit.organizeImports" "java.project.updateSourceAttachment" "java.project.resolveSourceAttachment"]) :workspace (:workspaceFolders (:supported t :changeNotifications t)))) #f(compiled-function () #<bytecode 0x1ea2c19>))
  #f(compiled-function (jsonrpc-lambda-elem3) #<bytecode 0x1e1f0f5>)((:capabilities (:textDocumentSync (:openClose t :change 2 :willSave t :willSaveWaitUntil t :save (:includeText t)) :hoverProvider t :completionProvider (:resolveProvider t :triggerCharacters ["." "@" "#" "*"]) :signatureHelpProvider (:triggerCharacters ["("]) :definitionProvider t :typeDefinitionProvider t :implementationProvider t :referencesProvider t :documentHighlightProvider t :documentSymbolProvider t :workspaceSymbolProvider t :codeActionProvider t :codeLensProvider (:resolveProvider t) :documentFormattingProvider t :documentRangeFormattingProvider t :documentOnTypeFormattingProvider (:firstTriggerCharacter ";" :moreTriggerCharacter ["\n" "}"]) :renameProvider (:prepareProvider t) :executeCommandProvider (:commands ["java.edit.organizeImports" "java.project.updateSourceAttachment" "java.project.resolveSourceAttachment"]) :workspace (:workspaceFolders (:supported t :changeNotifications t)))))
  jsonrpc-connection-receive(#<eglot-lsp-server eglot-lsp-server-1ea2be0> (:jsonrpc "2.0" :id 1 :result (:capabilities (:textDocumentSync (:openClose t :change 2 :willSave t :willSaveWaitUntil t :save (:includeText t)) :hoverProvider t :completionProvider (:resolveProvider t :triggerCharacters ["." "@" "#" "*"]) :signatureHelpProvider (:triggerCharacters ["("]) :definitionProvider t :typeDefinitionProvider t :implementationProvider t :referencesProvider t :documentHighlightProvider t :documentSymbolProvider t :workspaceSymbolProvider t :codeActionProvider t :codeLensProvider (:resolveProvider t) :documentFormattingProvider t :documentRangeFormattingProvider t :documentOnTypeFormattingProvider (:firstTriggerCharacter ";" :moreTriggerCharacter ["\n" "}"]) :renameProvider (:prepareProvider t) :executeCommandProvider (:commands ["java.edit.organizeImports" "java.project.updateSourceAttachment" "java.project.resolveSourceAttachment"]) :workspace (:workspaceFolders (:supported t :changeNotifications t))))))
  jsonrpc--process-filter(#<process EGLOT (openjfx/java-mode)> "Content-Length: 1041\15\n\15\n{\"jsonrpc\":\"2.0\",\"id\":1,\"r...")
```

The server seems to be working fine. I wonder why it doesn't work. I'm on emacs 27.0.50

**Comment by joaotavora** [comment] 2019-01-02 15:09
HI @bk322.  I'm sorry for the long delay: this issue flew under my radar.

This problem appears to be related to a old, legacy, flymake backend that should be disabled if you use the latest eglot (specifically one that has commit af9dcad2e677fa7eb59faa39561f3c60f4e886d7). Can you try?

**Comment by eubarbosa** [comment] 2019-01-10 23:24
@joaotavora  I can confirm its fixed.

An issue I did open in December, @mkcms noticed that flymake error. 

Its not happening anymore and I totally ignored it was fixed! hehe

**Comment by joaotavora** [comment] 2019-01-11 09:05
I don't understand, @eubarbosa: are you and @bk322 the same person? Anyway since the op didn't chime in lately, I'm closing this.

**Closed by joaotavora** 2019-01-11 09:05 UTC

**Comment by eubarbosa** [comment] 2019-01-11 12:34
Nope, but I had that very same issue as him. Just confirming Ihave not seen that error anymore! :dagger:
