### ISSUE TITLE
Stale flymake when using Rust Cargo path dependencies

### ISSUE THREAD

**Issue by lynaghk** [joaotavora/eglot#391] opened 2019-12-31 01:44 UTC
First, let me say thanks for Eglot, it's been working like a charm!

However, I've recently run into an issue where changes to path dependencies aren't reflected by flymake --- the only fix is to restart eglot.

I've prepared a minimal reproducible test repository here: https://github.com/lynaghk/eglot-rust-reproducible-repo

I believe the issue is on the Emacs side, since Visual Studio Code (which uses the same language server backend, RLS) isn't affected.
Please let me know if there's anything I can to do further narrow down or otherwise fix the issue.
Thanks!

**Comment by nemethf** [comment] 2020-01-03 20:56
Can you give additional information by following https://github.com/joaotavora/eglot#reporting-bugs ?
Also it would be good if you could get the log of the LSP communication between VS Code and rls.  Are you sure VS Code relies on the same language server?  For example, VS Code uses tsserver directly for javascript whereas eglot can only communicate with typescript-language-server.

**Comment by lynaghk** [comment] 2020-01-04 00:28
Thanks @nemethf! I've updated my reproducible repo with logs of the same actions (jump to definition of `Foo`, remove field `b`, and then look back at `main.rs`):
The eglot log is in two pieces:

[eglot_clearing_b](https://github.com/lynaghk/eglot-rust-reproducible-repo/blob/553746a1cfebb823d01aa6455394c87c5a91d9fc/eglot_clearing_b) is from the first eglot session, which doesn't update properly after `b` is removed from the struct
[eglot_after_restart](https://github.com/lynaghk/eglot-rust-reproducible-repo/blob/553746a1cfebb823d01aa6455394c87c5a91d9fc/eglot_after_restart) is the log after `eglot-shutdown` and `eglot` emacs commands are run to restart eglot.

The [VSCode log](https://github.com/lynaghk/eglot-rust-reproducible-repo/blob/master/vscode_rls.log) was created by setting this extension setting:

![Screenshot 2020-01-03 16 28 01](https://user-images.githubusercontent.com/147919/71756708-07b34900-2e46-11ea-902c-3a2f153084d1.png)

and launching VSCode via 

    dev@mini:~/work/eglot-rust-reproducible-repo/consumer$ RUST_LOG=rls=debug code .

Let me know if you need anything else, and thanks for helping with this!

**Comment by nemethf** [comment] 2020-01-04 10:17
Thanks.  The VSCode log is the log of the rls program and from that I cannot reconstruct the client-server communication.  However, the other two logs give more clues.  Their rootPath is "/Users/dev/work/eglot-rust-reproducible-repo/consumer/", which is strange because I get its parent directory as project root with `emacs -Q`.   

Do you have some additional project related settings?  In the main.rs buffer, what do you get when you `M-: (project-current) RET`?  What is the result if you repeat the experiment with `emacs -Q`?

(At this point,  I suspect it won't be easy to fix this issue, because eglot does not currently support workspaceFolders.  But it seems rls doesn't support it either, so I might be totally wrong.  We need more info.)

**Comment by skangas** [comment] 2022-01-14 16:54
More information was requested but was not given within 2 years. I'm therefore closing this bug.

If more information can be provided, please report back and we can re-open this bug. Thanks.

**Closed by skangas** 2022-01-14 16:54 UTC
Labels: moreinfo
