### ISSUE TITLE
Support for Vue Language Server

### ISSUE THREAD

**Issue by garyo** [joaotavora/eglot#257] opened 2019-05-03 20:11 UTC
I'm using Vue.js, and it has a vue language server VLS (https://www.npmjs.com/package/vue-language-server). The latest version 0.54 requires an initialization block, or else it gives an error on startup and fails to start. I fixed that with the following code in my .emacs, which perhaps could get folded in to the standard eglot. I got the actual init options from an issue posted to the lsp-mode project with this gist: https://gist.github.com/appledelhi/c2adc3e6cadba726dd417a8d659be84e .  I'm not sure I had to make a subclass for it and I'm not sure all those options are required, but anyway it works.

```
(defclass eglot-vls (eglot-lsp-server) ()
  :documentation "Vue Language Server.")

(add-to-list 'eglot-server-programs
             '(vue-mode . (eglot-vls . ("vls" "--stdio")))
             )

(cl-defmethod eglot-initialization-options ((server eglot-vls))
  "Passes through required vetur initialization options to VLS."
  '(:vetur
    (:completion
     (:autoImport t :useScaffoldSnippets t :tagCasing "kebab")
     :grammar
     (:customBlocks
      (:docs "md" :i18n "json"))
     :validation
     (:template t :style t :script t)
     :format
     (:options
      (:tabSize 2 :useTabs :json-false)
      :defaultFormatter
      (:html "prettyhtml" :css "prettier" :postcss "prettier" :scss "prettier" :less "prettier" :stylus "stylus-supremacy" :js "prettier" :ts "prettier")
      :defaultFormatterOptions
      (:js-beautify-html
       (:wrap_attributes "force-expand-multiline")
       :prettyhtml
       (:printWidth 100 :singleQuote :json-false :wrapAttributes :json-false :sortAttributes :json-false))
      :styleInitialIndent :json-false :scriptInitialIndent :json-false)
     :trace
     (:server "verbose")
     :dev
     (:vlsPath ""))
    ))
```

**Comment by nemethf** [comment] 2019-05-06 09:06
Hi,

Wouldn't it make more sense to fix this on the server side?  Otherwise every client needs to be modified.  By the way, is this issue reported to the server developers?

(I think bisecting the initialization options might help to find the options that are necessary to work around this bug; the rest should be left to the users to customize.)

**Comment by garyo** [comment] 2019-05-10 15:57
Perhaps it would, but this fix allowed me to get going right away.

**Comment by alexanderbarbosa** [comment] 2019-05-10 16:37
@garyo 
Eglot aims to minimal as how it communicates with LSP servers, meaning: Non-opinionated, no workarounds...

Your fix should be done on users side.

**Comment by garyo** [comment] 2019-05-10 16:44
Understood. I'll leave this here in case other people want to use Vue Language Server with eglot.

**Comment by joaotavora** [comment] 2019-05-10 21:07
> Eglot aims to be minimal at how it communicates with LSP servers, meaning: Non-opinionated, no workarounds, not that many user custom variables.

@alexanderbarbosa that is your opinion, but I'd think more acurate would be this:
1. It _is_ opinionated
2. It is _as agnostic as possible_ to the LSP server being used
3. It has its share of workarounds for LSP servers, which are allowed when there is no viable alternative in sight. It has many workarounds for Emacs and other relations in elisp-land.
4. It has as many custom variables as it needs, but none of them relate to specific LSP servers.

@garyo do you have any reason to believe that the Vue Language Server developers will never fix this on their side?

**Comment by alexanderbarbosa** [comment] 2019-05-10 21:25
@joaotavora 
ouch, my bad!

**Comment by joaotavora** [comment] 2019-05-10 21:31
> ouch, my bad!

No problem. Giving your opinion is allowed here, I just wanted to correct a possible impression that Eglot was somehow very strict  (or gratuitously strict) about these kinds of requests.

**Comment by garyo** [comment] 2019-05-10 21:38
> @garyo do you have any reason to believe that the Vue Language Server developers will never fix this on their side?

No reason to believe that. I didn't report it to them yet. I will though, that makes sense. I don't know much about LSP and haven't looked at the spec, so I have no idea who's doing what here, really, or whose side the issue is really on. (Unfortunately I didn't have a lot of time to spend on this -- once I got it working, I pushed out this bug report and then kind of moved on.)

**Comment by garyo** [comment] 2019-05-10 21:46
Reported it at https://github.com/vuejs/vetur/issues/1291

**Comment by garyo** [comment] 2019-10-17 21:41
This has now become even more annoying with recent vls, sadly.
I'm passing a large config block as `eglot-initialization-options` as above (somewhat different in latest vls but ok...), but apparently it also requires the same settings in  `workspace/didChangeConfiguration` otherwise it overwrites those configs with nil. I was hoping there's some way to pass the same config block in eglot to both initialization-options and `eglot-workspace-configuration` but the latter requires a list of alists and the former is just a single list. 

Hopefully it will be fixed on the server side soon!

**Comment by joaotavora** [comment] 2019-10-18 06:05
> but the latter requires a list of alists and the former is just a single list.

Yes, not my finest design hour there, I must admit. The problem is that changing the format of `eglot-workspace-configuration` into a plist is now a backward-incompatible change.  But I could bite the bullet and do it.

Anyway, you should still be able to reuse some code between the two functions.  

Also the fact that this server needs the client to tell it the same thing twice is a code smell on their side (if I've understood the problem correctly, at least)...

**Comment by garyo** [comment] 2019-10-18 11:44
The fact that the server needs this huge block of defaults even _once_ is a pain. But they know it; tracked in https://github.com/vuejs/vetur/pull/745.

**Comment by joaotavora** [comment] 2019-10-24 11:40
Closing this, it's a server-side problem

**Closed by joaotavora** 2019-10-24 11:40 UTC
Labels: server-bug
