### ISSUE TITLE
Eglot cannot recognize actions from phpactor's language server.

### ISSUE THREAD

**Issue by pablobc-mx** [joaotavora/eglot#560] opened 2020-11-01 09:42 UTC
As @Sasanidas mentioned [here](https://github.com/joaotavora/eglot/issues/537#issuecomment-695751570). When I try to execute an action to, for example, import a missing class, I get the following error.
```
Debugger entered--Lisp error: (error "[eglot] (:title \"Import class \\\"Illuminate\\\\Suppor...")
  signal(error ("[eglot] (:title \"Import class \\\"Illuminate\\\\Suppor..."))
  error("[eglot] %s" "(:title \"Import class \\\"Illuminate\\\\Support\\\\Facad...")
  eglot--error("%S didn't match any of %S" (:title "Import class \"Illuminate\\Support\\Facades\\Log\"" :kind "quickfix.import_class" :diagnostics [(:range (:start (:line 66 :character 8) :end (:line 66 :character 11)) :severity 4 :source "phpactor" :message "Class \"Log\" has not been imported")] :isPreferred t :command (:title "Import name" :command "name_import" :arguments ["file:///home/pablo/Prog/php/proyecto/app/Http/Cont..." 2015 "class" "Illuminate\\Support\\Facades\\Log"])) (((Command) command arguments) ((CodeAction) edit command)))
  eglot-code-actions(2016 nil)
  funcall-interactively(eglot-code-actions 2016 nil)
  call-interactively(eglot-code-actions record nil)
  command-execute(eglot-code-actions record)
```

Here is the event's buffer.
```

client-request (id:83) Sun Nov  1 01:17:43 2020:
(:jsonrpc "2.0" :id 83 :method "textDocument/codeAction" :params
	  (:textDocument
	   (:uri "file:///home/pablo/Prog/php/proyecto/app/Http/Controllers/PrinterController.php")
	   :range
	   (:start
	    (:line 0 :character 0)
	    :end
	    (:line 0 :character 0))
	   :context
	   (:diagnostics
	    [])))

server-reply (id:83) Sun Nov  1 01:17:43 2020:
(:id 83 :result
     [(:title "Import function \"config\"" :kind "quickfix.import_class" :diagnostics
	      [(:range
		(:start
		 (:line 33 :character 35)
		 :end
		 (:line 33 :character 41))
		:severity 4 :source "phpactor" :message "Function \"config\" has not been imported")]
	      :isPreferred t :command
	      (:title "Import name" :command "name_import" :arguments
		      ["file:///home/pablo/Prog/php/proyecto/app/Http/Controllers/PrinterController.php" 814 "function" "config"]))
      (:title "Import function \"config\"" :kind "quickfix.import_class" :diagnostics
	      [(:range
		(:start
		 (:line 33 :character 60)
		 :end
		 (:line 33 :character 66))
		:severity 4 :source "phpactor" :message "Function \"config\" has not been imported")]
	      :isPreferred t :command
	      (:title "Import name" :command "name_import" :arguments
		      ["file:///home/pablo/Prog/php/proyecto/app/Http/Controllers/PrinterController.php" 839 "function" "config"]))
      (:title "Import function \"config\"" :kind "quickfix.import_class" :diagnostics
	      [(:range
		(:start
		 (:line 34 :character 64)
		 :end
		 (:line 34 :character 70))
		:severity 4 :source "phpactor" :message "Function \"config\" has not been imported")]
	      :isPreferred t :command
	      (:title "Import name" :command "name_import" :arguments
		      ["file:///home/pablo/Prog/php/proyecto/app/Http/Controllers/PrinterController.php" 928 "function" "config"]))
      (:title "Import function \"config\"" :kind "quickfix.import_class" :diagnostics
	      [(:range
		(:start
		 (:line 34 :character 94)
		 :end
		 (:line 34 :character 100))
		:severity 4 :source "phpactor" :message "Function \"config\" has not been imported")]
	      :isPreferred t :command
	      (:title "Import name" :command "name_import" :arguments
		      ["file:///home/pablo/Prog/php/proyecto/app/Http/Controllers/PrinterController.php" 958 "function" "config"]))
      (:title "Import function \"view\"" :kind "quickfix.import_class" :diagnostics
	      [(:range
		(:start
		 (:line 50 :character 15)
		 :end
		 (:line 50 :character 19))
		:severity 4 :source "phpactor" :message "Function \"view\" has not been imported")]
	      :isPreferred t :command
	      (:title "Import name" :command "name_import" :arguments
		      ["file:///home/pablo/Prog/php/proyecto/app/Http/Controllers/PrinterController.php" 1504 "function" "view"]))
      (:title "Import class \"Illuminate\\Support\\Facades\\Log\"" :kind "quickfix.import_class" :diagnostics
	      [(:range
		(:start
		 (:line 66 :character 8)
		 :end
		 (:line 66 :character 11))
		:severity 4 :source "phpactor" :message "Class \"Log\" has not been imported")]
	      :isPreferred t :command
	      (:title "Import name" :command "name_import" :arguments
		      ["file:///home/pablo/Prog/php/proyecto/app/Http/Controllers/PrinterController.php" 2015 "class" "Illuminate\\Support\\Facades\\Log"]))
```

I'm using the following configuration for the phpactor language server
``` emacs-lisp
  (defvar phpactor-executable "/usr/local/bin/phpactor")

  (defclass eglot-php (eglot-lsp-server) ()
    :documentation "Phpactor lsp server.")

  (add-to-list 'eglot-server-programs
               `(php-mode . (eglot-php . ("php" "-d" "memory_limit=1024M" ,phpactor-executable "language-server"))))

  (cl-defmethod eglot-initialization-options ((server eglot-php))
    "Passes through required vetur initialization options to VLS."
    `(:language_server.session_parameters []
                                          :indexer.exclude_patterns []
                                          :language_server_code_transform.import_globals ,t))
```

**Comment by nemethf** [comment] 2021-05-26 09:15
Relying solely on the backtrace and the event log, I'm not able to reproduce the error.  Do you still experience the problem with the latest version of Eglot?

**Comment by skangas** [comment] 2022-01-09 10:10
More information was requested, but none was given in over 6 months. I'm therefore closing this bug report.

If you are still seeing this, please report back or open a new issue. Thanks!

**Closed by skangas** 2022-01-09 10:10 UTC
