### ISSUE TITLE
Clangd on windows

### ISSUE THREAD

**Issue by kccha** [joaotavora/eglot#519] opened 2020-08-01 17:00 UTC
Hi, I'm trying to get eglot working with clangd on windows. I am using the following elisp to set the default server program for c++:

`(add-to-list 'eglot-server-programs '((c-mode c++-mode objc-mode cuda-mode) "clangd"))`

I noticed this in my messages log:
`error in process filter: doom-modeline-update-eglot: Symbol’s function definition is void: eglot--current-server`
`error in process filter: Symbol’s function definition is void: eglot--current-server`

Clangd appears to be running, but I just get a bunch of errors each time I try to find definitions or whatnot. So I'm wondering if this is something do with the "Connecting via TCP" thing in the ReadMe.

I'm not very experienced with the LSP protocol. How can I configure eglot to use clangd over TCP?

**Comment by Joxos** [comment] 2020-08-13 04:03
![image](https://user-images.githubusercontent.com/37507136/90092895-d0eacd00-dd5c-11ea-8fda-f76d71b59196.png)
Me too, when I tried to open a .cpp file, I got a bunch of errors. @kccha

**Comment by Eason0210** [comment] 2021-01-20 01:35
@kccha  The same config as yours，it works for me on Win 10. May be you can try to update Clangd to latest version.

**Comment by joaotavora** [comment] 2021-01-20 09:55
@Joxos, I think you need to update your software.

Either that or you must post a recipe that I can follow along to.  I don't have Doom Emacs.  See the README.md for tips on how to do that.

**Comment by joaotavora** [comment] 2021-01-20 09:56
@Eason0210 from looking at @Joxos output it's probably a Doom Emacs bug or something with its package management.

**Comment by skangas** [comment] 2022-01-08 18:55
No further updates here within 12 months, so I'm closing this bug. Please report back you are still seeing this, preferably with a reproducible recipe, and we can re-open.

**Closed by skangas** 2022-01-08 18:55 UTC
Labels: can't reproduce
