### ISSUE TITLE
Unescape markdown

### ISSUE THREAD

**Issue by fbergroth** [joaotavora/eglot#188] opened 2018-12-17 17:27 UTC
pyls is escaping `*` in its documentation strings [here](https://github.com/palantir/python-language-server/blob/79f3ffe3687785f9ed66e062f1b4a13c01312444/pyls/_utils.py#L99-L108), which is rendered as `\*` by eglot.

I'm not sure if its appropriate for eglot to do these substitutions, or if they belong in `markdown-toggle-markup-hiding` but I'm reporting it here. Btw, should `gfm-view-mode` be used instead of `gfm-mode` in `eglot--format-markup`?

Locally I'm using
```
(advice-add 'eglot--format-markup :filter-return
            (lambda (r)
              (replace-regexp-in-string "\\\\\\*" "*" r)))
```
to get rid of it.

**Comment by joaotavora** [comment] 2018-12-17 20:36
> Btw, should gfm-view-mode be used instead of gfm-mode in eglot--format-markup

Something like that maybe.  This has been annoying me too, so I'm going to try these functions, which I didn't know about.  It's not really appropriate though for Eglot to filter the output of the LSP server: as you probably expect what works for one server breaks the other, etc...

**Comment by fbergroth** [comment] 2018-12-18 10:51
I wrote an issue in markdown-mode https://github.com/jrblevin/markdown-mode/issues/377

**Comment by ilohmar** [comment] 2019-03-01 16:57
I am wondering about a related issue: Judging from the spec, it is unclear to me that markdown should be the default to render documentation items -- it might just as well be plaintext.  Do you have any opinion on that?  Language servers that I've tested so far (pyls and a fork of go-langserver) just seem to do as they please and do *not* stick to the LSP specs.  Also, they might use fenced code blocks w/o labeling the language, sigh...

**Comment by joaotavora** [comment] 2019-10-24 11:49
The `markdown-mode` dev has accepted this needs to be improved on its side. Marking "Not a bug" and closing.

**Closed by joaotavora** 2019-10-24 11:49 UTC
Labels: not-a-bug

**Comment by jimporter** [comment] 2023-03-25 23:51
For anyone tracking this here, I filed a PR to fix this in the markdown-mode repo: https://github.com/jrblevin/markdown-mode/pull/756
