### ISSUE TITLE
Missing the trailing ) during completion with yasnippet and gopls

### ISSUE THREAD

**Issue by xuchunyang** [joaotavora/eglot#332] opened 2019-10-30 06:50 UTC
For example,

![Emacs 2019-10-30 at 14 34 45](https://user-images.githubusercontent.com/4550353/67834490-7e6c5700-fb22-11e9-8fad-dab7748db618.png)

The event buffer contains the following, it seems `:newText "Print(${1:a ...interface{\\}})"` does contain the final `)`, but `yas-expand-snippet` deletes it.

```el
(
 :label "Print" :kind 3 :detail "func(a ...interface{}) (n int, err error)"
 :documentation "Print formats using the default formats for its operands and writes to standard output."
 :preselect t :sortText "00000" :filterText "Pr" :insertTextFormat 2
 :textEdit
 (:range
  (:start
   (:line 5 :character 5)
   :end
   (:line 5 :character 7))
  :newText "Print(${1:a ...interface{\\}})")
 :command
 (:title "" :command "editor.action.triggerParameterHints"))
```

I don't have such issue two or three days ago, I did update the gopls, but the response seems ok. I can reproduce without my Emacs config, e.g.,

```
~/src/emacs-mac/mac/Emacs.app/Contents/MacOS/Emacs -Q -nw \
-L ~/.emacs.d/elpa-26.3/eglot-20191028.1529               \
-L ~/.emacs.d/elpa-26.3/jsonrpc-1.0.7                     \
-L ~/.emacs.d/elpa-26.3/yasnippet-20191009.216            \
-L ~/.emacs.d/elpa-26.3/go-mode-20191022.2037             \
-L /Users/xcy/.emacs.d/elpa-26.3/company-20190907.1149    \
-l eglot                                                  \
-l yasnippet                                              \
-l company                                                \
-l go-mode                                                \
playground.go                                             \
-f yas-global-mode                                        \
-f company-mode                                           \
--eval "(setq-default eglot-workspace-configuration '((:gopls . (:usePlaceholders t))))" \
-f eglot
```

, where playground.go can be just this
```
package main

import "fmt"

func main() {
	fmt.Println("Hello, 世界")
}
```

**Comment by joaotavora** [comment] 2019-10-30 11:36
Thank you for the fantastic reproduction recipe, you're my kind of guy! It's the way I like them, just copy paste and see the bug happening.

Two tiny things:

1. The recipe has a mistake there in the `eglot-workspace-configuration` that I took the liberty to fix (it's a horrible format, I know).
2. You also need a non-empty `playground.go` file.

That said, I couldn't reproduce the error:  I get the trailing `)`.  But I was testing with emacs master version and some git heads of some other packages. Are you testing with 26.3? 

Here's my `-Q` recipe:
```
~/Source/Emacs/emacs-master/src/emacs -Q -nw              \                                                                       master ◼
-L ~/Source/Emacs/eglot                                   \
-L ~/Source/Emacs/yasnippet                               \
-L ~/.emacs.d/elpa/go-mode-20191022.2037                  \
-L ~/Source/Emacs/company-mode                            \
-l eglot                                                  \
-l yasnippet                                              \
-l company                                                \
-l go-mode                                                \
playground.go                                             \
-f yas-global-mode                                        \
-f company-mode                                           \
--eval "(setq-default                                     \
           eglot-workspace-configuration                  \
           '((:gopls . (:usePlaceholders t))))"           \
-f eglot
```

**Comment by joaotavora** [comment] 2019-10-30 11:40
Hmm, how curious... In your screenshot, one sees **two** trailing `}` instead of *one* `}` and one `)`.  How can this be?  Can you double check the snippet that the `gopls` server is sending.  Have a look at this gif when I run my repro recipe:

![Peek 2019-10-30 11-37](https://user-images.githubusercontent.com/387011/67855255-02feab80-fb0a-11e9-839e-7eba8089fd7d.gif)

**Comment by xuchunyang** [comment] 2019-10-30 11:49
> The recipe has a mistake there in the eglot-workspace-configuration

I think both are correct, json.el gives the same output, and I have used the alist format a few days and it does work.

```el
(json-encode '((:gopls . (:usePlaceholders t))))
;; => "{\"gopls\":{\"usePlaceholders\":true}}"

(json-encode '((:gopls . ((:usePlaceholders . t)))))
;; => "{\"gopls\":{\"usePlaceholders\":true}}"
```

> Are you testing with 26.3?

Yes.
---

Thanks for the reply. I'll check again gopls's response.

**Comment by joaotavora** [comment] 2019-10-30 11:56
> think both are correct, json.el gives the same output, and I have used the alist format a few days and it does work.

No, only mine is, but I understand the confusion.

the backend that jsonrpc uses in Emacs 26.3 is more permissive and will guess that you meant an alist. But the backend in upcoming 27.1 won't.

Oh this is going to be trouble when people starting using 27.1 _en masse_ :fearful:   the docstring doesn't help also
```
eglot-workspace-configuration is a variable defined in ‘eglot.el’.
Its value is ((:gopls :usePlaceholders t))

  Automatically becomes buffer-local when set.
  This variable is safe as a file local variable if its value
  satisfies the predicate ‘listp’.

Documentation:
Alist of (SECTION . VALUE) entries configuring the LSP server.
SECTION should be a keyword or a string, value can be anything
that can be converted to JSON.
```

It should read "`anything that can be converted to JSON arrays and objects.  
For representing arrays, use elisp vectors, for objects use elisp plists, NOT alists.`"

So don't use alists :-)

**Comment by xuchunyang** [comment] 2019-10-30 12:11
> I'll check again gopls's response.

lsp-mode doesn't have the same issue for me, and both of them seem are getting the same thing from gopls, this is wired.

Do this work for you? Mine is missing the final `)`, it becomes `Println(a ...interface{}}`, it this expected?

```el
(yas-expand-snippet "Println(${1:a ...interface{\\}})")
```

**Comment by xuchunyang** [comment] 2019-10-30 12:32
lsp-mode process the snippet text before sending to `yas-expand-snippet` with this function

```el
(defun company-lsp--to-yasnippet-snippet (text)
  "Convert VS code snippet TEXT to yasnippet snippet."
  ;; VS code snippet doesn't esscape "{", but yasnippet requires escaping it.
  (let (parts
        (start 0))
    (dolist (range (s-matched-positions-all (regexp-quote "{") text))
      (let ((match-start (car range)))
        (unless (and (> match-start 0) (= (aref text (1- match-start)) ?$))
          ;; Not a start of field. Escape it.
          (when (< start match-start)
            (push (substring text start match-start) parts))
          (push "\\{" parts)
          (setq start (1+ match-start)))))
    (when (< start (length text))
      (push (substring text start) parts))
    (apply #'concat (reverse parts))))
```

and after apply it to elgot, my issue is gone

```el
(define-advice eglot--snippet-expansion-fn
    (:filter-return (fn) fix-snippet-text)
  (and fn
       (lambda (text &rest r)
         (apply fn (company-lsp--to-yasnippet-snippet text) r))))
```

I don't know which version of gopls I am using, but I think I just "update" it from git master (?) maybe two days ago, so maybe you're using a different version thus you can't reproduce.

**Comment by s-kostyaev** [comment] 2019-10-30 12:56
I have found simpler solution: 
```
diff --git a/eglot.el b/eglot.el
index 1f7a396..8570a27 100644
--- a/eglot.el
+++ b/eglot.el
@@ -1073,7 +1073,8 @@ If optional MARKER, return a marker instead"
 Doubles as an indicator of snippet support."
   (and (boundp 'yas-minor-mode)
        (symbol-value 'yas-minor-mode)
-       'yas-expand-snippet))
+       (lambda (text &rest r)
+         (yas-expand-snippet (replace-regexp-in-string "\\\\}" "\}" text) r))))
 
 (defun eglot--format-markup (markup)
   "Format MARKUP according to LSP's spec."
```

**Comment by joaotavora** [comment] 2019-10-30 13:06
Ohhh, thanks @s-kostyaev 

This is a yasnippet issue https://github.com/joaotavora/yasnippet/issues/979. I should have connected the dots, but I forgot completely. The version of `gopls` that I was using is from Debian, doesn't have this problem.

I'm gonna push the fix to yasnippet, there is already a proposal there, and @npostavs has given a green light.

**Comment by joaotavora** [comment] 2019-10-30 13:33
> I'm gonna push the fix to yasnippet, there is already a proposal there, and @npostavs has given a green light.

Done.  Grab the newest yasnippet or wait a bit for MELPA updates.

Closing this, but go ahead and test @xuchunyang, and keep those fine bugs coming.

**Closed by joaotavora** 2019-10-30 13:33 UTC
Labels: can't reproduce
