### ISSUE TITLE
Nothing appears in the message area

### ISSUE THREAD

**Issue by bcmertz** [joaotavora/eglot#676] opened 2021-04-24 00:10 UTC
* Server used: gopls               
* Emacs version: Gnu Emacs 28.0.50        
* Operating system:  Manjaro Linux        
* Eglot version: 1.7             
* Eglot installation method: package.el       
* Using Doom: no                

#### LSP transcript - M-x eglot-events-buffer (mandatory unless Emacs inoperable)

     
```lisp[client-request] (id:1) Fri Apr 23 19:47:56 2021:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
	  (:processId 881177 :rootPath "/home/bennett/coding/hinge/db/" :rootUri "file:///home/bennett/coding/hinge/db" :initializationOptions #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
																			     ())
		      :capabilities
		      (:workspace
		       (:applyEdit t :executeCommand
				   (:dynamicRegistration :json-false)
				   :workspaceEdit
				   (:documentChanges :json-false)
				   :didChangeWatchedFiles
				   (:dynamicRegistration t)
				   :symbol
				   (:dynamicRegistration :json-false)
				   :configuration t)
		       :textDocument
		       (:synchronization
			(:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
			:completion
			(:dynamicRegistration :json-false :completionItem
					      (:snippetSupport :json-false)
					      :contextSupport t)
			:hover
			(:dynamicRegistration :json-false :contentFormat
					      ["plaintext"])
			:signatureHelp
			(:dynamicRegistration :json-false :signatureInformation
					      (:parameterInformation
					       (:labelOffsetSupport t)
					       :activeParameterSupport t))
			:references
			(:dynamicRegistration :json-false)
			:definition
			(:dynamicRegistration :json-false)
			:declaration
			(:dynamicRegistration :json-false)
			:implementation
			(:dynamicRegistration :json-false)
			:typeDefinition
			(:dynamicRegistration :json-false)
			:documentSymbol
			(:dynamicRegistration :json-false :hierarchicalDocumentSymbolSupport t :symbolKind
					      (:valueSet
					       [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
			:documentHighlight
			(:dynamicRegistration :json-false)
			:codeAction
			(:dynamicRegistration :json-false :codeActionLiteralSupport
					      (:codeActionKind
					       (:valueSet
						["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"]))
					      :isPreferredSupport t)
			:formatting
			(:dynamicRegistration :json-false)
			:rangeFormatting
			(:dynamicRegistration :json-false)
			:rename
			(:dynamicRegistration :json-false)
			:publishDiagnostics
			(:relatedInformation :json-false))
		       :experimental #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
						   ()))))
[server-reply] (id:1) Fri Apr 23 19:47:56 2021:
(:jsonrpc "2.0" :result
	  (:capabilities
	   (:textDocumentSync
	    (:openClose t :change 2 :save nil)
	    :completionProvider
	    (:triggerCharacters
	     ["."])
	    :hoverProvider t :signatureHelpProvider
	    (:triggerCharacters
	     ["(" ","])
	    :definitionProvider t :typeDefinitionProvider t :implementationProvider t :referencesProvider t :documentHighlightProvider t :documentSymbolProvider t :codeActionProvider
	    (:codeActionKinds
	     ["quickfix" "refactor.rewrite" "source.fixAll" "source.organizeImports"])
	    :codeLensProvider nil :documentLinkProvider nil :workspaceSymbolProvider t :documentFormattingProvider t :documentOnTypeFormattingProvider
	    (:firstTriggerCharacter "")
	    :renameProvider t :foldingRangeProvider t :executeCommandProvider
	    (:commands
	     ["test" "tidy" "upgrade_dependency" "generate" "regenerate_cgo"])
	    :workspace
	    (:workspaceFolders
	     (:supported t :changeNotifications "workspace/didChangeWorkspaceFolders")))
	   :serverInfo
	   (:name "gopls" :version "Build info\n----------\nversion master, built in $GOPATH mode\n\nGo info\n-------\ngo version go1.14.3 linux/amd64\n\n"))
	  :id 1)
[client-notification] Fri Apr 23 19:47:56 2021:
(:jsonrpc "2.0" :method "initialized" :params #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
							    ()))
[client-notification] Fri Apr 23 19:47:56 2021:
(:jsonrpc "2.0" :method "textDocument/didOpen" :params
	  (:textDocument
	   (:uri "file:///home/bennett/coding/hinge/db/db_test.go" :version 0 :languageId "go" :text "package db\n\nimport (\n	\"hinge/user\"\n	\"testing\"\n)\n\nfunc TestRemoveAndBlock(t *testing.T) {\n	d := DB{\"addr\"}\n	err := d.Initialize()\n	if err != nil {\n		t.Errorf(\"Failed to intiialize db\")\n	}\n\n	u1 := user.User{\n		ID:       123456789,\n		Name:     \"John Doe\",\n		Location: user.Location{},\n	}\n	u2 := user.User{\n		ID:       98765432221,\n		Name:     \"Jane Person\",\n		Location: user.Location{},\n	}\n\n	// TODO: finish comparing by values, probably reqauires refactoring\n	// to use a hash map or something like that\n	assertEquivalentSlices := func(t *testing.T, got, want []user.User) {\n		t.Helper()\n		if len(got) != len(want) {\n			t.Errorf(\"unequal slice length got %q want %q\", len(got), len(want))\n		}\n\n	}\n\n	d.AddMatch(u1, u2)\n	err = d.RemoveAndBlock(u1, u2)\n	if err != nil {\n		t.Errorf(\"recieved error removing and blocking user\")\n	}\n\n	t.Run(\"Make sure u1 has match removed\", func(t *testing.T) {\n		u1_matches := d.QueryMatches(u1)\n		var expected_u1_matches = []user.User{}\n		assertEquivalentSlices(t, u1_matches, expected_u1_matches)\n	})\n\n	t.Run(\"Make sure u2 has match removed\", func(t *testing.T) {\n		u2_matches := d.QueryMatches(u1)\n		var expected_u2_matches = []user.User{}\n		assertEquivalentSlices(t, u2_matches, expected_u2_matches)\n	})\n\n	t.Run(\"Make sure u1 has match removed\", func(t *testing.T) {\n		blocked := d.QueryBlocked(u1, u2)\n		want := []user.User{u1}\n		assertEquivalentSlices(t, blocked, want)\n	})\n}\n")))
[client-notification] Fri Apr 23 19:47:56 2021:
(:jsonrpc "2.0" :method "workspace/didChangeConfiguration" :params
	  (:settings nil))
[server-request] (id:1) Fri Apr 23 19:47:56 2021:
(:jsonrpc "2.0" :method "client/registerCapability" :params
	  (:registrations
	   [(:id "workspace/didChangeWatchedFiles" :method "workspace/didChangeWatchedFiles" :registerOptions
		 (:watchers
		  [(:globPattern "**/*.go" :kind 7)]))])
	  :id 1)
[client-reply] (id:1) Fri Apr 23 19:47:56 2021:
(:jsonrpc "2.0" :id 1 :result nil)
[server-request] (id:2) Fri Apr 23 19:47:56 2021:
(:jsonrpc "2.0" :method "workspace/configuration" :params
	  (:items
	   [(:scopeUri "file:///home/bennett/coding/hinge/db" :section "gopls")
	    (:scopeUri "file:///home/bennett/coding/hinge/db" :section "gopls-db")])
	  :id 2)
[client-reply] (id:2) Fri Apr 23 19:47:56 2021:
(:jsonrpc "2.0" :id 2 :result
	  [nil nil])
[server-notification] Fri Apr 23 19:47:56 2021:
(:jsonrpc "2.0" :method "window/logMessage" :params
	  (:type 3 :message "2021/04/23 19:47:56 Build info\n----------\nversion master, built in $GOPATH mode\n\nGo info\n-------\ngo version go1.14.3 linux/amd64\n\n\n"))
[server-notification] Fri Apr 23 19:47:56 2021:
(:jsonrpc "2.0" :method "window/logMessage" :params
	  (:type 3 :message "2021/04/23 19:47:56 go env for /home/bennett/coding/hinge/db\n(valid build configuration = true)\n(build flags: [-modfile=/tmp/go.db.236968300.mod])\nGO111MODULE=\"\"\nGOARCH=\"amd64\"\nGOBIN=\"\"\nGOCACHE=\"/home/bennett/.cache/go-build\"\nGOENV=\"/home/bennett/.config/go/env\"\nGOEXE=\"\"\nGOFLAGS=\"\"\nGOHOSTARCH=\"amd64\"\nGOHOSTOS=\"linux\"\nGOINSECURE=\"\"\nGONOPROXY=\"\"\nGONOSUMDB=\"\"\nGOOS=\"linux\"\nGOPATH=\"/home/bennett/coding/go\"\nGOPRIVATE=\"\"\nGOPROXY=\"https://proxy.golang.org,direct\"\nGOROOT=\"/usr/local/go\"\nGOSUMDB=\"sum.golang.org\"\nGOTMPDIR=\"\"\nGOTOOLDIR=\"/usr/local/go/pkg/tool/linux_amd64\"\nGCCGO=\"gccgo\"\nAR=\"ar\"\nCC=\"gcc\"\nCXX=\"g++\"\nCGO_ENABLED=\"1\"\nGOMOD=\"/home/bennett/coding/hinge/go.mod\"\nCGO_CFLAGS=\"-g -O2\"\nCGO_CPPFLAGS=\"\"\nCGO_CXXFLAGS=\"-g -O2\"\nCGO_FFLAGS=\"-g -O2\"\nCGO_LDFLAGS=\"-g -O2\"\nPKG_CONFIG=\"pkg-config\"\nGOGCCFLAGS=\"-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build055523923=/tmp/go-build -gno-record-gcc-switches\"\n\n"))
[server-notification] Fri Apr 23 19:47:56 2021:
(:jsonrpc "2.0" :method "window/logMessage" :params
	  (:type 3 :message "2021/04/23 19:47:56 go/packages.Load\n	snapshot=0\n	directory=/home/bennett/coding/hinge/db\n	query=[./... builtin]\n	packages=4\n"))
[server-request] (id:3) Fri Apr 23 19:47:56 2021:
(:jsonrpc "2.0" :method "workspace/configuration" :params
	  (:items
	   [(:scopeUri "file:///home/bennett/coding/hinge/db" :section "gopls")
	    (:scopeUri "file:///home/bennett/coding/hinge/db" :section "gopls-db")])
	  :id 3)
[client-reply] (id:3) Fri Apr 23 19:47:56 2021:
(:jsonrpc "2.0" :id 3 :result
	  [nil nil])

```
    
#### Backtrace (mandatory, unless no error message seen or heard):

     
```lisp
... Paste the backtrace here ...
Debugger entered--Lisp error: (error "oh no")
  signal(error ("oh no"))
  error("oh no")
  eval((error "oh no") nil)
  pp-eval-expression((error "oh no"))
  funcall-interactively(pp-eval-expression (error "oh no"))
  call-interactively(pp-eval-expression nil nil)
  command-execute(pp-eval-expression)
```
   
#### Minimal configuration (mandatory)

     
 ```sh
 # Type this in a shell to start an Emacs with Eglot configured
 $ /path/to/a/certain/version/of/emacs -Q -f package-initialize -L /path/to/git-cloned/eglot -l eglot.el 
 ```
 
 ```lisp
;; Packages and repository management
(require 'package)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("melpa-stable" . "https://stable.melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))

;;; init.el ends here
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages '(eglot go-mode)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

  ```
 
 

I have installed eglot and go-mode from the repos listed above. Gopls is up to date to master. I enter a go file, type M-x go-mode M-x eglot. Bug I'm seeing is that no information is echoed in the messages file or the message minibuffer. Nothing appears on hover. Regardless of where I put my mouse or my cursor, nothing that used to appear appears. Any help is greatly appreciated! Even if I add this to my config eglot doesn't display any type info or anything even though it launches without error. I see ```[eglot] Connected! Server `gopls' now managing `go-mode' buffers in project `hinge'.
``` in *Messages*

**Comment by joaotavora** [comment] 2021-04-24 10:28
It seems you have left the examples of the templates in, which is confusing. 

Do you understand that what appears under "Minimal configuration (mandatory)" is supposed to be an example to show me how to experience your error?   

Maybe you were confused about the issue-reporting template, which is probably my fault, though I tried hard to explain in that text what we're after.  Unfortunately, we don't have enough elements to reproduce your problem, so can't help you right away.  It's quite possible (and very common) that it's an error in your configuration, but again we can't know for sure because that information isn't available clearly.

I'm marking this irreproducible and closing, but I'll open if you provide a better reproduction recipe.  You can also start a discussion [here|https://github.com/joaotavora/eglot/discussions].

Here's what I'm looking for in a reproduction recipe, both in text form and video form, so it's as clear as possible.  You don't have to follow this exact format, this is just to illustrate how the recipe rules out many intrusions from external factors.  It tries to be scientific reproducible experiment.

#### Minimal configuration (in text form)
```
❯ emacs --version
GNU Emacs 26.3
Copyright (C) 2019 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
❯ go version
go version go1.15.6 linux/amd64
❯ ls ~/.emacs.d/elpa
acme-theme-20200724.1833/          debbugs-0.25.signed           jsonrpc-1.0.14.signed              waher-theme-20141115.1230/
afternoon-theme-20140104.1859/     diminish-20191127.1326/       json-snatcher-20200916.1717/       warm-night-theme-20161101.1428/
almost-mono-themes-20210306.1040/  eglot-1.6/                    lua-mode-20200508.1316/            web-mode-20210131.1758/
archives/                          eglot-1.6.signed              markdown-mode-20191230.1055/       weyland-yutani-theme-20210227.1749/
auctex-12.2.0/                     eldoc-1.11.0/                 modus-vivendi-theme-0.12.0/        xclip-1.10/
auctex-12.2.0.signed               eldoc-1.11.0.signed           modus-vivendi-theme-0.12.0.signed  xclip-1.10.signed
auctex-latexmk-20170618.1636/      evil-20210109.807/            monokai-theme-20201229.1001/       xclip-1.9/
autothemer-20180920.923/           flymake-1.0.9/                overcast-theme-20200425.1601/      xclip-1.9.signed
bbdb-20200102.403/                 flymake-1.0.9.signed          peg-1.0/                           xref-1.0.4/
clojure-mode-20210322.704/         gnupg/                        peg-1.0.signed                     xref-1.0.4.signed
company-0.9.10/                    go-mode-20201204.1652/        project-0.5.3/                     yaml-mode-20201109.1026/
company-0.9.10.signed              goto-chg-20201101.1029/       project-0.5.3.signed               yasnippet-0.14.0/
company-0.9.12/                    gruvbox-theme-20210105.1136/  purple-haze-theme-20141015.229/    yasnippet-0.14.0.signed
company-0.9.12.signed              imenu-list-20190115.2130/     rust-mode-20200414.2105/           yoshi-theme-20210216.29/
company-0.9.13/                    js-comint-20200117.615/       srcery-theme-20210201.1444/        zenburn-theme-20201121.1050/
company-0.9.13.signed              json-mode-20190123.422/       subatomic-theme-20190607.1022/     zweilight-theme-20170113.605/
darkokai-theme-20200614.1452/      json-reformat-20160212.853/   tron-legacy-theme-20200601.533/
debbugs-0.25/                      jsonrpc-1.0.14/               typescript-mode-20201002.1109/
❯ emacs -Q -f package-initialize ~/tmp/hello-world.go -f eglot
# Once inside Emacs, witness that Eglot seems to start correctly
```

#### The same minimal configuration (in video form)
![Peek 2021-04-24 11-21](https://user-images.githubusercontent.com/387011/115955599-64c98700-a4ef-11eb-8bb2-c66564e4d5dd.gif)

**Closed by joaotavora** 2021-04-24 10:28 UTC
