### ISSUE TITLE
Flymake bug with two backends (Was: Cannot get deno lsp working: missing field 'enable' error)

### ISSUE THREAD

**Issue by danielpza** [joaotavora/eglot#660] opened 2021-04-03 21:28 UTC
I'm trying to configure eglot with [deno lsp](https://deno.land/manual/getting_started/setup_your_environment#lsp-clients). I didn't find any issues related to the error message so I guess it has to do with my eglot configuration.

.dirs-locals.el:

```
((typescript-mode . ((eglot-server-programs . ((typescript-mode . ("deno" "lsp"))))
		     (eglot-workspace-configuration . (("enable" . t)
						       ("lint" . t)
						       ("unstable" . t))))))
```

(eglot-events-buffer):

```
[client-request] (id:1) Sat Apr  3 17:23:48 2021:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
	  (:processId 2361 :rootPath "/home/daniel/projects/learning-deno/" :rootUri "file:///home/daniel/projects/learning-deno/" :initializationOptions #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
																					())
		      :capabilities
		      (:workspace
		       (:applyEdit t :executeCommand
				   (:dynamicRegistration :json-false)
				   :workspaceEdit
				   (:documentChanges :json-false)
				   :didChangeWatchedFiles
				   (:dynamicRegistration t)
				   :symbol
				   (:dynamicRegistration :json-false)
				   :configuration t)
		       :textDocument
		       (:synchronization
			(:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
			:completion
			(:dynamicRegistration :json-false :completionItem
					      (:snippetSupport :json-false)
					      :contextSupport t)
			:hover
			(:dynamicRegistration :json-false :contentFormat
					      ["markdown" "plaintext"])
			:signatureHelp
			(:dynamicRegistration :json-false :signatureInformation
					      (:parameterInformation
					       (:labelOffsetSupport t)))
			:references
			(:dynamicRegistration :json-false)
			:definition
			(:dynamicRegistration :json-false)
			:declaration
			(:dynamicRegistration :json-false)
			:implementation
			(:dynamicRegistration :json-false)
			:typeDefinition
			(:dynamicRegistration :json-false)
			:documentSymbol
			(:dynamicRegistration :json-false :hierarchicalDocumentSymbolSupport t :symbolKind
					      (:valueSet
					       [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
			:documentHighlight
			(:dynamicRegistration :json-false)
			:codeAction
			(:dynamicRegistration :json-false :codeActionLiteralSupport
					      (:codeActionKind
					       (:valueSet
						["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"]))
					      :isPreferredSupport t)
			:formatting
			(:dynamicRegistration :json-false)
			:rangeFormatting
			(:dynamicRegistration :json-false)
			:rename
			(:dynamicRegistration :json-false)
			:publishDiagnostics
			(:relatedInformation :json-false))
		       :experimental #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
						   ()))))
[stderr] Starting Deno language server...
[stderr]   version: 1.8.3 (release, x86_64-unknown-linux-gnu)
[server-reply] (id:1) ERROR Sat Apr  3 17:23:48 2021:
(:jsonrpc "2.0" :error
	  (:code -32602 :message "missing field `enable`")
	  :id 1)
[internal] Sat Apr  3 17:23:48 2021:
(:message "Connection state changed" :change "killed\n")

----------b---y---e---b---y---e----------
[stderr] 
[stderr] 
[stderr] nil
[stderr] nil
[stderr] Process EGLOT (learning-deno/typescript-mode) stderr finished
```

```
$ emacs --version
GNU Emacs 28.0.50
Copyright (C) 2021 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING
```

```
$ deno --version
deno 1.8.3 (release, x86_64-unknown-linux-gnu)
v8 9.0.257.3
typescript 4.2.2
```

**Comment by muffinmad** [comment] 2021-04-04 20:10
Take a look at https://github.com/denoland/deno/issues/9988

Judging from [deno the manual](https://github.com/denoland/deno/blob/main/docs/getting_started/setup_your_environment.md#lsp-clients) you need to pass the `enabled` option as the initialization parameter and not as the workspace configuration parameter.

See https://github.com/joaotavora/eglot/blob/master/README.md#handling-quirky-servers

**Comment by danielpza** [comment] 2021-04-04 21:18
Got it to somehow work by following your suggestion:

```elisp
  (add-to-list 'eglot-server-programs '((js-mode typescript-mode) . (eglot-deno "deno" "lsp")))

  (defclass eglot-deno (eglot-lsp-server) ()
    :documentation "A custom class for deno lsp.")

  (cl-defmethod eglot-initialization-options ((server eglot-deno))
    "Passes through required deno initialization options"
    (list :enable t
	  :lint t))
```

However got an error:

```
[eglot] Connected! Server `deno-language-server' now managing `typescript-mode' buffers in project `learning-deno'.
error in process sentinel: apply: Wrong type argument: flymake--backend-state, nil
error in process sentinel: Wrong type argument: flymake--backend-state, nil
```

**Comment by joaotavora** [comment] 2021-04-04 21:19
> However got an error:

Are you using the very latest Eglot?  Can I get a backtrace? Thanks

**Comment by danielpza** [comment] 2021-04-04 21:22
If I disable eglot-ensure it no longer complains :|

**Comment by joaotavora** [comment] 2021-04-04 21:23
Yes, but can you get it to complain and generate a backtrace using `toggle-debug-on-error` and paste it here?  Thanks

**Comment by danielpza** [comment] 2021-04-04 21:23
> Are you using the very latest Eglot?

I installed it yesterday, I'll make sure it's up to date.

> Can I get a backtrace?

is there a command for that or a buffer?

**Comment by danielpza** [comment] 2021-04-04 21:23
I see I'm too slow to respond and you actually responded before I could reply, I'll try that

**Comment by danielpza** [comment] 2021-04-04 21:29
I'm updating all my packages and it's taking a while, in the meantime this is the stacktrace I got:

```
Debugger entered--Lisp error: (wrong-type-argument flymake--backend-state nil)
  #<subr flymake--handle-report>(flymake-eslint--checker backend-token45 nil)
  apply(#<subr flymake--handle-report> (flymake-eslint--checker backend-token45 nil))
  #f(advice-wrapper :after #<subr flymake--handle-report> doom-modeline-update-flymake-icon)(flymake-eslint--checker backend-token45 nil)
  apply(#f(advice-wrapper :after #<subr flymake--handle-report> doom-modeline-update-flymake-icon) (flymake-eslint--checker backend-token45 nil))
  flymake--handle-report(flymake-eslint--checker backend-token45 nil)
  apply(flymake--handle-report flymake-eslint--checker backend-token45 nil)
  #f(compiled-function (&rest args) #<bytecode 0xd698b4eab600427>)(nil)
  #f(compiled-function (eslint-stdout) #<bytecode 0x1ef0e728213e5b8f>)(#<buffer  *flymake-eslint*>)
  #f(compiled-function (proc &rest ignored) #<bytecode -0x1d6545d48f23b74e>)(#<process flymake-eslint> "exited abnormally with code 2\n")
```

I'll report back after I'm done updating

**Comment by joaotavora** [comment] 2021-04-04 21:31
Seems you are using `flymake-eslint` and `eglot` at the same time.  Actually I happen to be using the same and used to get that error.

"updating all your packages" is likely _not_ to bring in the latest Eglot version, which is what we wanted.  But if you don't know how to update a single package from Melpa, doing the brute-force Doom dance is all we got.  Maybe it'll pick up a new package.  Anyway, good luck.

**Comment by joaotavora** [comment] 2021-04-04 21:32
> Actually I happen to be using the same and used to get that error.

(and I don't anymore in the very latest Eglot version)

**Comment by danielpza** [comment] 2021-04-04 21:33
> "updating all your packages" is likely not to bring in the latest Eglot version

why not?

> doing the brute-force Doom dance is all we got

I'm using straight in case that matters, I think doom also uses straight?

**Comment by danielpza** [comment] 2021-04-04 21:35
Got a similar error after updating:

```
Debugger entered--Lisp error: (wrong-type-argument flymake--backend-state nil)
  signal(wrong-type-argument (flymake--backend-state nil))
  #f(compiled-function (arg1 arg2 arg3 &rest rest) "Handle reports from BACKEND identified by TOKEN.\nBACKEND, REPORT-ACTION and EXPLANATION, and FORCE conform to the\ncalling convention described in\n`flymake-diagnostic-functions' (which see).  Optional FORCE says\nto handle a report even if TOKEN was not expected.  REGION is\na (BEG . END) pair of buffer positions indicating that this\nreport applies to that region." #<bytecode 0x19bbf2da544da5bd>)(flymake-eslint--checker backend-token45 nil)
  apply(#f(compiled-function (arg1 arg2 arg3 &rest rest) "Handle reports from BACKEND identified by TOKEN.\nBACKEND, REPORT-ACTION and EXPLANATION, and FORCE conform to the\ncalling convention described in\n`flymake-diagnostic-functions' (which see).  Optional FORCE says\nto handle a report even if TOKEN was not expected.  REGION is\na (BEG . END) pair of buffer positions indicating that this\nreport applies to that region." #<bytecode 0x19bbf2da544da5bd>) (flymake-eslint--checker backend-token45 nil))
  #f(advice-wrapper :after #f(compiled-function (arg1 arg2 arg3 &rest rest) "Handle reports from BACKEND identified by TOKEN.\nBACKEND, REPORT-ACTION and EXPLANATION, and FORCE conform to the\ncalling convention described in\n`flymake-diagnostic-functions' (which see).  Optional FORCE says\nto handle a report even if TOKEN was not expected.  REGION is\na (BEG . END) pair of buffer positions indicating that this\nreport applies to that region." #<bytecode 0x19bbf2da544da5bd>) doom-modeline-update-flymake-icon)(flymake-eslint--checker backend-token45 nil)
  apply(#f(advice-wrapper :after #f(compiled-function (arg1 arg2 arg3 &rest rest) "Handle reports from BACKEND identified by TOKEN.\nBACKEND, REPORT-ACTION and EXPLANATION, and FORCE conform to the\ncalling convention described in\n`flymake-diagnostic-functions' (which see).  Optional FORCE says\nto handle a report even if TOKEN was not expected.  REGION is\na (BEG . END) pair of buffer positions indicating that this\nreport applies to that region." #<bytecode 0x19bbf2da544da5bd>) doom-modeline-update-flymake-icon) (flymake-eslint--checker backend-token45 nil))
  flymake--handle-report(flymake-eslint--checker backend-token45 nil)
  apply(flymake--handle-report flymake-eslint--checker backend-token45 nil)
  #f(compiled-function (&rest args) #<bytecode 0x16fa69b1d517bce7>)(nil)
  #f(compiled-function (eslint-stdout) #<bytecode 0x1ea8a7c7163d378f>)(#<buffer  *flymake-eslint*>)
  #f(compiled-function (proc &rest ignored) #<bytecode -0x1b04c9b6cc26b70c>)(#<process flymake-eslint> "exited abnormally with code 2\n")
```

**Comment by joaotavora** [comment] 2021-04-04 21:35
> why not?

I've heard recently that Doom uses "version pinning" (in unrelated #596).

**Comment by danielpza** [comment] 2021-04-04 21:36
I'm using last commit from 3 days ago https://github.com/joaotavora/eglot/commit/f930a09

**Comment by danielpza** [comment] 2021-04-04 21:36
I'm not using Doom btw in case it wasn't clear

**Comment by danielpza** [comment] 2021-04-04 21:37
ok seems like the deno issue got resolved and it has turned into a new one?

**Comment by joaotavora** [comment] 2021-04-04 21:37
I saw `doom-modeline-update-flymake-icon` in your backtrace so I thought you were.

**Comment by joaotavora** [comment] 2021-04-04 21:39
> and it has turned into a new one?

Seems so, yes. But let's continue here. I'm afraid my last commit (which you are indeed using), has broken something. 

Can you post a failing configuration that:

- includes flymake-eslint
- includes Eglot and basic deno setup
- includes nothing else?

Thanks

**Comment by danielpza** [comment] 2021-04-04 21:49
This is my flymake-eslint + eglot configuration

```
(use-package flymake-eslint
  :straight t
  :config
  (add-hook 'typescript-mode-hook (lambda () (flymake-eslint-enable)))
  (add-hook 'js-mode-hook (lambda () (flymake-eslint-enable))))

(use-package eglot
  :straight t
  :hook ((js-mode typescript-mode) . 'eglot-ensure)
  :config
  (add-to-list 'eglot-server-programs '((js-mode typescript-mode) . (eglot-deno "deno" "lsp")))

  (defclass eglot-deno (eglot-lsp-server) ()
    :documentation "A custom class for deno lsp.")

  (cl-defmethod eglot-initialization-options ((server eglot-deno))
    "Passes through required deno initialization options"
    (list :enable t
	  :lint t)))
```

> includes nothing else?

do you mean create an empty init.el with only above?

**Comment by danielpza** [comment] 2021-04-04 22:11
Sandbox https://github.com/danielpza/eglot-flymake-issue

**Comment by joaotavora** [comment] 2021-04-05 11:43
> do you mean create an empty init.el with only above?

Yes, but maybe it's not necessary.  I briefly reproduced your situation, but now I can't anymore.  Are you sure everything works OK without the `eglot-ensure`?

**Comment by joaotavora** [comment] 2021-04-05 12:22
@danielpza I can't reproduce this.  My guess it that you need to ensure you don't have statle .elc files.

I tried your sandbox, removed the `deno` line to use the default `typescript-language-server`. because I  don't think this is related to the server at all (though you may want to post an event transcript for Deno/LSP debugging)

Another note. Are you sure your sandbox/setup is doing what you want? Without adding `flymake` to `eglot-stay-out-of`, it'll be hard to convince Eglot to let you use a second Flymake backend such as `flymake-eslint`.  

On yet another not, there is `.eslintrc` in your sandbox, so even if `eslint` did kick in, it would turn itself off immediately.

I recommend adding `eglot-stay-out-of` to your configuration somehow.  Maybe this?

```lisp
(use-package eglot
  :straight t
  :hook ((js-mode typescript-mode) . 'eglot-ensure)
  :config
  (add-hook 'js-mode-hook
            (lambda ()
              (setq-local eglot-stay-out-of '(flymake))
              (add-hook 'flymake-diagnostic-functions 'eglot-flymake-backend nil t)))
  
  (defclass eglot-deno (eglot-lsp-server) ()
    :documentation "A custom class for deno lsp.")

  (cl-defmethod eglot-initialization-options ((server eglot-deno))
    "Passes through required deno initialization options"
    (list :enable t
	  :lint t)))
```

**Comment by joaotavora** [comment] 2021-04-10 19:19
Any news on this @danielpza ? I've been using eslint and `typescript-language-server` just fine lately, so I'm going to take your silence to mean this is solved and close this.  Of course, if it's not and you can work on the sandbox recipe so that it reproduces, we can reopen.  In any case we can keep discussing.

**Closed by joaotavora** 2021-04-10 19:19 UTC

**Comment by danielpza** [comment] 2021-04-10 21:45
I've been busy with work lately, I'll take some time to reproduce the issue in an isolated environment, we can keep it closed until then. Thanks for the work
