### ISSUE TITLE
eglot jdt.ls completion add extra text

### ISSUE THREAD

**Issue by zsxh** [joaotavora/eglot#1349] opened 2024-01-12 07:18 UTC
```
emacs master, emacs-repository-version: eac3f2a80778b3904c55ae7b65ff862a79eebf2a
jdt-language-server version: 1.31.0
jdk version: adoptopenjdk-21.0.1+12.0.LTS
```

file /tmp/demo/SingleFile.java
``` java
public class SingleFile {
  public static void main(String[] args) {

  }
}
```

1. Ensure the java `jdt.ls` LSP server is installed and available in path
2. Invoke Emacs master with Eglot master
`emacs -Q -f package-initialize /tmp/demo/SingleFile.java -f global-company-mode -f eglot`
3. line 3 type `Array`, select `Arrays` RET
4. actual result
 ``` java
import java.util.Arrays;

public class SingleFile {
  public static void main(String[] args) {
      Arraysray
  }
}
```
expected result
``` java
import java.util.Arrays;

public class SingleFile {
  public static void main(String[] args) {
      Arrays
  }
}
```

[eglot-jdtls.log](https://github.com/joaotavora/eglot/files/13915767/eglot-jdtls.log)

**Comment by vdcow** [comment] 2024-01-25 06:51
I believe, it is not jdt.ls specific. Have the same issue with clangd. Also found relevant discussion in corfu

https://github.com/minad/corfu/discussions/400

**Comment by joaotavora** [comment] 2024-01-25 08:38
Ok. Then please make a recipe for clangd that I can follow EXACTLY like @zsxh did. I can certainly follow that and come to a conclusion (@zsxh 's much harder to follow because it needs Java, which I don't want to be install)

**Comment by vdcow** [comment] 2024-01-25 11:35
@joaotavora 

**Versions:**

```
Emacs 29.1
eglot 1.16
company 20240107
```
**Test file:**

```C++
#include <vector>

int main(int argc, char *argv[])
{
    std::vector<int> v;
    v.push_back(5);
    return 0;
}
```

**Steps:**

1. Open the file
```
emacs -Q -f package-initialize main.cc -f global-company-mode -f eglot
```
2. Type "v.p" in the line before "return 0"
![image](https://github.com/joaotavora/eglot/assets/1499142/8b146567-a9ab-4997-8c3e-f0b7ef8c9f75)
3. Press Enter
4. Check that there is extra "p" from entered "v.p"
![image](https://github.com/joaotavora/eglot/assets/1499142/489562a3-b742-4da1-9e0d-19af1a2de936)

**Comment by joaotavora** [comment] 2024-01-25 11:46
Thanks. Confirmed.  Doesn't always happen though, have to debug.

**Comment by joaotavora** [comment] 2024-01-25 12:21
Should be fixed in the latest master Emacs and also in the upcoming Eglot 1.17, which should be in GNU ELPA tomorrow

**Closed by joaotavora** 2024-01-25 12:21 UTC
Labels: bug

**Comment by vdcow** [comment] 2024-01-25 12:22
That was fast! Thank you @joaotavora !
