### ISSUE TITLE
eglot + cquery: Killing buffer doesn't kill cquery

### ISSUE THREAD

**Issue by jojojames** [joaotavora/eglot#78] opened 2018-08-18 17:00 UTC
emacs -Q # emacs 27

```
(add-to-list 'load-path "/Users/james/.emacs.d/elpa/27/company-20180802.1207")
(require 'company)
(add-hook 'c-mode-hook 'company-mode)

(add-to-list 'load-path "/Users/james/.emacs.d/elpa/27/eglot-20180817.2356")
(require 'eglot)
(add-hook 'c-mode-hook 'eglot-ensure)
```

Visit a c file in home directory: (~/a.c) with find-file.

```
// Random c file with scratch code.

static void
pixel_window_scroll (Lisp_Object window, EMACS_INT n, bool whole, bool noerror)
{
  ptrdiff_t count = SPECPDL_INDEX ();

  n = clip_to_bounds (INT_MIN, n, INT_MAX);

  wset_redisplay (XWINDOW (window));

  if (whole && Vfast_but_imprecise_scrolling)
    specbind (Qfontification_functions, Qnil);

  /* If we must, use the pixel-based version which is much slower than
     the line-based one but can handle varying line heights.  */
  window_scroll_pixel_based (window, n, whole, noerror);

  unbind_to (count, Qnil);

  /* Bug#15957.  */
  XWINDOW (window)->window_end_valid = false;
}

static void
pixel_scroll_command (Lisp_Object window, Lisp_Object n, int direction)
{
  struct window *w;
  bool other_window;
  ptrdiff_t count = SPECPDL_INDEX ();

  eassert (eabs (direction) == 1);

  w = XWINDOW (window);
  other_window = !EQ (window, selected_window);

  /* If given window's buffer isn't current, make it current for the
     moment.  If the window's buffer is the same, but it is not the
     selected window, we need to save-excursion to avoid affecting
     point in the selected window (which would cause the selected
     window to scroll).  Don't screw up if window_scroll gets an
     error.  */
  if (other_window || XBUFFER (w->contents) != current_buffer)
    {
      record_unwind_protect_excursion ();
      if (XBUFFER (w->contents) != current_buffer)
        Fset_buffer (w->contents);
    }

  if (other_window)
    {
      SET_PT_BOTH (marker_position (w->pointm),
                   marker_byte_position (w->pointm));
      SET_PT_BOTH (marker_position (w->old_pointm),
                   marker_byte_position (w->old_pointm));
    }

  if (NILP (n))
    pixel_window_scroll (window, direction, true, false);
  else if (EQ (n, Qminus))
    pixel_window_scroll (window, -direction, true, false);
  else
    {
      n = Fprefix_numeric_value (n);
      pixel_window_scroll (window, XINT (n) * direction, false, false);
    }

  if (other_window)
    {
      set_marker_both (w->pointm, Qnil, PT, PT_BYTE);
      set_marker_both (w->old_pointm, Qnil, PT, PT_BYTE);
    }

  unbind_to (count, Qnil);
}

DEFUN ("pixel-scroll-up", Fscroll_up, Sscroll_up, 0, 1, "^P",
       doc: /* Scroll text of selected window upward ARG lines.
If ARG is omitted or nil, scroll upward by a near full screen.
A near full screen is `next-screen-context-lines' less than a full screen.
Negative ARG means scroll downward.
If ARG is the atom `-', scroll downward by nearly full screen.
When calling from a program, supply as argument a number, nil, or `-'.  */)
(Lisp_Object arg)
{
  pixel_scroll_command (selected_window, arg, 1);
  return Qnil;
}

DEFUN ("pixel-scroll-down", Fscroll_down, Sscroll_down, 0, 1, "^P",
       doc: /* Scroll text of selected window down ARG lines.
If ARG is omitted or nil, scroll down by a near full screen.
A near full screen is `next-screen-context-lines' less than a full screen.
Negative ARG means scroll upward.
If ARG is the atom `-', scroll upward by nearly full screen.
When calling from a program, supply as argument a number, nil, or `-'.  */)
(Lisp_Object arg)
{
  pixel_scroll_command (selected_window, arg, -1);
  return Qnil;
}

{
  {
    {
      {
	{
	  {
	    {
	      
	    }
	  }
	}
      }
    }
  }
}

asdfsdffffffffffffsssssssssssssasdfasdfasdfasdffff

```

C-x k (kill-buffer) to kill buffer a.c.
<img width="707" alt="screenshot 2018-08-18 09 52 39" src="https://user-images.githubusercontent.com/1227856/44301513-2191d180-a2cd-11e8-88d9-92c1610c529d.png">
<img width="988" alt="screenshot 2018-08-18 09 52 42" src="https://user-images.githubusercontent.com/1227856/44301515-2f475700-a2cd-11e8-91ce-0fdc8788c144.png">

~~

Second problem I encounter is *if* I kill cquery from the Activity Monitor (using 'Force Quit'), eglot will automatically restart cquery and reconnect to it, even though no buffer exists with eglot enabled (only one having been a.c which was killed earlier.)

<img width="707" alt="screenshot 2018-08-18 09 53 16" src="https://user-images.githubusercontent.com/1227856/44301531-71709880-a2cd-11e8-87bb-89a380010fb7.png">

**Comment by joaotavora** [comment] 2018-08-18 18:32
@jojojames, if you `killall cquery` twice from a console in quick succession it should really kill the server.

**Comment by joaotavora** [comment] 2018-08-19 01:12
> @jojojames, if you killall cquery twice from a console in quick succession it should really kill the server.

Also (and I don't know why I didn't mention this earlier), `M-x eglot-shutdown` is a good way to kill servers for which you don't have any live managed buffers.

**Comment by jojojames** [comment] 2018-08-19 18:06
Thanks, I'll try it out and report back.

**Comment by joaotavora** [comment] 2018-08-19 18:10
Regarding the performance problems, it does seem to be a server issue.  It apparently gets confused when you close the last file.  

1. Have you tried reopening the file? (this should reactivate eglot without spawning a new server).
2. If you customize `eglot-events-buffer-size` to 0, event logging is disabled completely.  You can use that when you suspect the server to be overflowing Emacs with a many useless events, or when you don't need to debug anything.

**Comment by jojojames** [comment] 2018-08-19 18:13
> Have you tried reopening the file? (this should reactivate eglot without spawning a new server).

Yeah, once the server gets into its  bad state, it seems like reconnecting will just eventually bring emacs back to the same performance-degraded state. Cquery also seems to consistently get itself into that state given the file I use. Haven't had the time yet to look on Cquery's end but that will be a good path too.

> If you customize eglot-events-buffer-size to 0, event logging is disabled completely. You can use that when you suspect the server to be overflowing Emacs with a many useless events, or when you don't need to debug anything.

Thanks, I'll try that next time.

**Comment by joaotavora** [comment] 2018-08-19 18:16
Given that the reported behaviour is the behaviour by design. I am closing this issue.  Let me know if I am missing something and this needs to be reopened.

**Closed by joaotavora** 2018-08-19 18:16 UTC
