### ISSUE TITLE
Autoshutdown error leaves garbage when eglot process dies unexpectedly

### ISSUE THREAD

**Issue by tmurph** [joaotavora/eglot#389] opened 2019-12-30 21:53 UTC
Sometimes my language server just dies, or I have to kill it manually.  Ever since enabling `eglot-autoshutdown` I've noticed that when the server dies unexpectedly I get some obnoxious problems.

Most superficially, I see the following error message when the process dies:
> error in process sentinel: Process EGLOT (foo) not running

But it turns out that this error also leaves a garbage server hanging around.  If I say `M-x eglot-shutdown` I can see it in the list of completions, but selecting the server and hitting enter gives me the same `Process EGLOT (foo) not running` error, and the server hangs around forever.  This gets worse if I start up a new connection, because the new server gets the same name as the old garbage server, and `eglot-shutdown` shows both.

I think the issue arises like this:
  1. The process dies, triggering the `eglot--on-shutdown` function.
  2. `eglot--on-shutdown` turns off `eglot--managed-mode` where appropriate.
  3. But!  If `eglot-autoshutdown` is non-nil then disabling the mode on the last managed buffer triggers `eglot-shutdown`.
  4. `eglot-shutdown` implicitly assumes that the server is still alive, and sends a request to a dead process.
  5. This error short-circuits `eglot--on-shutdown`, preventing further cleanup and skipping any auto-reconnect behavior.

I propose modifying `eglot--on-shutdown` to avoid the autoshutdown side effect.

**Comment by joaotavora** [comment] 2019-12-31 00:08
Nice analysis, and fix looks good from very brief analysis. Have you tested with normal and corner cases? Also, let's point @ilohmar who implemented this, I think

**Comment by joaotavora** [comment] 2019-12-31 00:08
I meant ping, not point

**Comment by ilohmar** [comment] 2019-12-31 08:52
I think (from re-reading code several times) this was an actual bug and that the solution is fine, thanks.

That being said, `eglot-shutdown` *also* never triggers the auto-shutdown behavior when it loops over buffers, because it sets the `--shutdown-requested` flag first --- so there are two different ways of achieving the same thing now. How about (instead of the proposed change):

1) remove the check for `--shutdown-requested` in the minor-mode function,
2) add an optional `no-autoshutdown` parameter to `--managed-mode-off`,
3) if this parameter is non-nil, let-bind `-autoshutdown` to nil there?

It seems to me that this would be prefereable (as there would only be one place where this happens and it has cleaner semantics overall).  WDYT?

**Comment by tmurph** [comment] 2019-12-31 17:09
Thanks, Ingo, I see what you're saying.  Agree it's best to avoid two different ways of getting the same thing.

I guess the extra parameter seems unnecessary to me?  I think we get the same result if (instead of the original proposed change) we just replace the check for `--shutdown-requested` in the minor-mode function with a check for `(jsonrpc-running-p server)`.  

In both `eglot--on-shutdown` and `eglot-shutdown` the minor mode only gets turned off after the server process is dead.  (It's already dead by the time `--on-shutdown` is called, and `eglot-shutdown` explicitly kills it before turning off the minor mode).  This means that the `-running-p` check will always fail through those code paths.

**Comment by tmurph** [comment] 2019-12-31 17:17
Yeah, João, unfortunately re: testing I haven't gotten the ERT suite working correctly on my setup.  I've just been manually starting and stopping servers in various ways (killing buffers, manually turning off the mode, and `kill -9` on the server processes).  I'll keep playing with ERT and see if I can get a test case.

**Comment by tmurph** [comment] 2019-12-31 17:27
Oh shoot, sorry for the spam but I just realized I'm dumb.  Just realized my `jsonrpc-running-p` proposal would still need to include the `--shutdown-requested` check anyway, to avoid cases where the shutdown is requested manually and there's some weird jsonrpc communication error that leaves the server running.

Yeah okay, scratch that.  I'll make a PR following Ingo's suggestion.  Thanks!

**Comment by ilohmar** [comment] 2020-01-01 20:44
I think the new PR is fine and should be merged.

**Comment by joaotavora** [comment] 2020-01-01 22:03
I think this is simpler:
```diff
diff --git a/eglot.el b/eglot.el
index 4c0160a..4795304 100644
--- a/eglot.el
+++ b/eglot.el
@@ -593,9 +593,6 @@ SERVER.  ."
         ;; this one is supposed to always fail, because it asks the
         ;; server to exit itself. Hence ignore-errors.
         (ignore-errors (jsonrpc-request server :exit nil :timeout 1)))
-    ;; Turn off `eglot--managed-mode' where appropriate.
-    (dolist (buffer (eglot--managed-buffers server))
-      (eglot--with-live-buffer buffer (eglot--managed-mode-off)))
     ;; Now ask jsonrpc.el to shut down the server (which under normal
     ;; conditions should return immediately).
     (jsonrpc-shutdown server (not preserve-buffers))
@@ -605,7 +602,8 @@ SERVER.  ."
   "Called by jsonrpc.el when SERVER is already dead."
   ;; Turn off `eglot--managed-mode' where appropriate.
   (dolist (buffer (eglot--managed-buffers server))
-    (eglot--with-live-buffer buffer (eglot--managed-mode-off)))
+    (let ((eglot-autoshutdown nil))
+      (eglot--with-live-buffer buffer (eglot--managed-mode-off))))
   ;; Kill any expensive watches
   (maphash (lambda (_id watches)
              (mapcar #'file-notify-rm-watch watches))
```

Admitedly, it has two differences to @tmurph's patch.  
1. It doesn't use a new arg to `eglot--managed-mode-off` which I think is fine.
2. It deletes what seems to be a useless two lines in `eglot-shutdown`, those lines will eventually get called anyway.

I'm slightly wary of 2.  Can either of you give me an opinion?

**Comment by joaotavora** [comment] 2020-01-01 22:06
7098fe3 seems to work for me, but my testing was very limited.

**Comment by ilohmar** [comment] 2020-01-01 22:47
The duplication of the buffer looping has bugged me since I first read it, and I thought about it again in this context.  My assumption has always been that the code was duplicated for a good reason, ie, that there might be cases where the shutdown fails or is incomplete, and the sentinel never runs as intended.  It would be bad indeed if the buffers were still in the managed state in such a case.

I did never look into the jsonrpc details yet --- if you're confident that the above scenario cannot happen, I am all for your approach, of course.

**Comment by ilohmar** [comment] 2020-01-02 09:49
Well, one more thing: If you're going that route, I think the check for `--shutdown-requested` in the minor-mode function should still be dropped.  It was only effective when triggered from within the regular `-shutdown` command, which no longer happens then.

**Comment by tmurph** [comment] 2020-01-02 18:19
I think it should be fine to dedupe the buffer cleanup.  `eglot-shutdown` calls `jsonrpc-shutdown` which calls `delete-process` in a loop until the sentinel runs.  So I think it's fair to assume that `eglot--on-shutdown` will always run before `eglot-shutdown` returns.

There is a risk that somebody writes a new `jsonrpc-shutdown` that's specialized to an eglot lsp server or descendent class and forgets to call next method, but I think that's really unlikely.

+1 for Ingo's suggestion to remove `--shutdown-requested` from the minor mode check.

**Comment by joaotavora** [comment] 2020-01-02 18:25
> There is a risk that somebody writes a new jsonrpc-shutdown that's specialized to an eglot lsp server or descendent class and forgets to call next method, but I think that's really unlikely.

Yes it is.  But you're right, it's a (minimal) risk. A way to avoid that would be to use a `:before` or an `:after` or another method combination (maybe `progn`?) _if elisp supported method combinations_.

**Comment by joaotavora** [comment] 2020-01-02 18:39
> Edit: nvm, I didn't realize that Emacs auto-combines applicable methods.

Hmmm.  I don't think it does.  It uses the `standard` method combination, I think.

**Closed** 2020-01-02 18:44 UTC
