### ISSUE TITLE
trying to get preamble for non-added document (clangd) with melpa eglot

### ISSUE THREAD

**Issue by gmbuell** [joaotavora/eglot#462] opened 2020-05-07 20:42 UTC
When using eglot from melpa (20200506.2135) with clangd as the c++ server program and yasnippet enabled, selecting any completion (even a variable completion that doesn't trigger snippet expansion) causes eglot to report an error from clangd "trying to get preamble for non-added document". This error repeats with everything eglot tries to do.
Restarting eglot with M-x eglot (even reconnecting to the live clangd process) allows another completion and then fails in the same manner.

Minimum init:

```emacs
(require 'package)
(add-to-list 'package-archives (cons "melpa" "https://melpa.org/packages/") t)

(package-initialize)
(package-refresh-contents)
(package-install 'yasnippet)
(package-install 'company)
(package-install 'eglot)

(require 'yasnippet)
(yas-global-mode 1)

(require 'company)
(setq company-backends '(company-capf))
(global-company-mode)

(require 'eglot)
(add-hook 'c++-mode-hook 'eglot-ensure)
(add-to-list 'eglot-server-programs '(c++-mode . ("clangd")))
```

Running eglot from elpa (version 1.6) does not exhibit this problem
Minimum successful init:
```emacs
(require 'package)

(package-initialize)
(package-refresh-contents)
(package-install 'yasnippet)
(package-install 'company)
(package-install 'eglot)

(require 'yasnippet)
(yas-global-mode 1)

(require 'company)
(setq company-backends '(company-capf))
(global-company-mode)

(require 'eglot)
(add-hook 'c++-mode-hook 'eglot-ensure)
(add-to-list 'eglot-server-programs '(c++-mode . ("clangd")))
```

Not loading yasnippet also seems to not exhibit this problem though it could be that yasnippet is just guaranteed to trigger the failure scenario.
Successful init loading from melpa without yasnippet
```emacs
(require 'package)
(add-to-list 'package-archives (cons "melpa" "https://melpa.org/packages/") t)

(package-initialize)
(package-refresh-contents)
(package-install 'company)
(package-install 'eglot)

(require 'company)
(setq company-backends '(company-capf))
(global-company-mode)

(require 'eglot)
(add-hook 'c++-mode-hook 'eglot-ensure)
(add-to-list 'eglot-server-programs '(c++-mode . ("clangd")))
```

**Comment by muffinmad** [comment] 2020-05-07 20:48
This error fired by language server. See similar issue https://github.com/emacs-lsp/lsp-mode/issues/582

**Comment by joaotavora** [comment] 2020-05-07 20:48
Exactly what `clagnd` are you using? Can you start it with `clangd --log=verbose` (using `C-u M-x eglot RET clangd --log=verbose`)  and post the contents of the events buffer here?  You can get to it with `M-x eglot-events-buffer`.

**Comment by joaotavora** [comment] 2020-05-07 21:03
According to @muffinmad 's comments this is a server bug.

**Comment by gmbuell** [comment] 2020-05-07 21:23
clangd is built at revision [f9106e85c424](https://reviews.llvm.org/rGf9106e85c424756bcd1378d6a00bb582cc2114bb) from August 29, 2020.

The clangd fix for the linked issue was Oct 22 2018.

I've been messing around more and it seems this issue is actually an interaction with new yasnippet. If I run company and eglot from melpa but yasnippet from elpa (version 0.14) the errors aren't triggered (at least not immediately).

Tail section of my eglot-events-buffer
```
server-reply (id:7) Thu May  7 14:18:28 2020:
(:id 7 :jsonrpc "2.0" :result
     (:contents
      (:kind "plaintext" :value "variable features\n\nType: int\n\n// In FillFeatureSet\nint features")
      :range
      (:end
       (:character 6 :line 147)
       :start
       (:character 2 :line 147))))

server-reply (id:8) Thu May  7 14:18:28 2020:
(:id 8 :jsonrpc "2.0" :result
     [(:kind 1 :range
	     (:end
	      (:character 10 :line 148)
	      :start
	      (:character 2 :line 148)))])

server-reply (id:6) Thu May  7 14:18:28 2020:
(:id 6 :jsonrpc "2.0" :result
     (:activeParameter 0 :activeSignature 0 :signatures
		       []))

client-notification Thu May  7 14:18:29 2020:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
	  (:textDocument
	   (:uri "file:///home/gmbuell/Code/logs.cc" :version 11)
	   :contentChanges
	   [(:range
	     (:start
	      (:line 147 :character 2)
	      :end
	      (:line 147 :character 6))
	     :rangeLength 4 :text "")
	    (:range
	     (:start
	      (:line 147 :character 2)
	      :end
	      (:line 147 :character 2))
	     :rangeLength 0 :text "features")
	    (:range
	     (:start
	      (:line 147 :character 6)
	      :end
	      (:line 147 :character 10))
	     :rangeLength 4 :text "")
	    (:range
	     (:start
	      (:line 147 :character 2)
	      :end
	      (:line 147 :character 6))
	     :rangeLength 4 :text "")
	    (:range
	     (:start
	      (:line 147 :character 2)
	      :end
	      (:line 147 :character 10))
	     :rangeLength 8 :text "features")]))

client-request (id:9) Thu May  7 14:18:29 2020:
(:jsonrpc "2.0" :id 9 :method "textDocument/signatureHelp" :params
	  (:textDocument
	   (:uri "file:///home/gmbuell/Code/logs.cc")
	   :position
	   (:line 147 :character 10)))

client-request (id:10) Thu May  7 14:18:29 2020:
(:jsonrpc "2.0" :id 10 :method "textDocument/hover" :params
	  (:textDocument
	   (:uri "file:///home/gmbuell/Code/logs.cc")
	   :position
	   (:line 147 :character 10)))

client-request (id:11) Thu May  7 14:18:29 2020:
(:jsonrpc "2.0" :id 11 :method "textDocument/documentHighlight" :params
	  (:textDocument
	   (:uri "file:///home/gmbuell/Code/logs.cc")
	   :position
	   (:line 147 :character 10)))

server-reply (id:9) ERROR Thu May  7 14:18:29 2020:
(:error
 (:code -32602 :message "trying to get preamble for non-added document")
 :id 9 :jsonrpc "2.0")

internal (id:9) ERROR Thu May  7 14:18:29 2020:
(:message "error ignored, status set (trying to get preamble for non-added document)" :id 9 :error -32602)

server-reply (id:10) ERROR Thu May  7 14:18:29 2020:
(:error
 (:code -32602 :message "trying to get AST for non-added document")
 :id 10 :jsonrpc "2.0")

internal (id:10) ERROR Thu May  7 14:18:29 2020:
(:message "error ignored, status set (trying to get AST for non-added document)" :id 10 :error -32602)

server-reply (id:11) ERROR Thu May  7 14:18:29 2020:
(:error
 (:code -32602 :message "trying to get AST for non-added document")
 :id 11 :jsonrpc "2.0")

internal (id:11) ERROR Thu May  7 14:18:29 2020:
(:message "error ignored, status set (trying to get AST for non-added document)" :id 11 :error -32602)

client-notification Thu May  7 14:18:31 2020:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
	  (:textDocument
	   (:uri "file:///home/gmbuell/Code/logs.cc" :version 16)
	   :contentChanges
	   [(:range
	     (:start
	      (:line 147 :character 10)
	      :end
	      (:line 147 :character 10))
	     :rangeLength 0 :text "-")
	    (:range
	     (:start
	      (:line 147 :character 11)
	      :end
	      (:line 147 :character 11))
	     :rangeLength 0 :text ">")
	    (:range
	     (:start
	      (:line 147 :character 12)
	      :end
	      (:line 147 :character 12))
	     :rangeLength 0 :text "i")
	    (:range
	     (:start
	      (:line 147 :character 13)
	      :end
	      (:line 147 :character 13))
	     :rangeLength 0 :text "n")
	    (:range
	     (:start
	      (:line 147 :character 14)
	      :end
	      (:line 147 :character 14))
	     :rangeLength 0 :text "s")]))

client-request (id:12) Thu May  7 14:18:31 2020:
(:jsonrpc "2.0" :id 12 :method "textDocument/completion" :params
	  (:textDocument
	   (:uri "file:///home/gmbuell/Code/logs.cc")
	   :position
	   (:line 147 :character 15)
	   :context
	   (:triggerKind 1)))

server-reply (id:12) ERROR Thu May  7 14:18:31 2020:
(:error
 (:code -32602 :message "trying to get preamble for non-added document")
 :id 12 :jsonrpc "2.0")

client-request (id:13) Thu May  7 14:18:31 2020:
(:jsonrpc "2.0" :id 13 :method "textDocument/completion" :params
	  (:textDocument
	   (:uri "file:///home/gmbuell/Code/logs.cc")
	   :position
	   (:line 147 :character 15)
	   :context
	   (:triggerKind 1)))

client-request (id:14) Thu May  7 14:18:31 2020:
(:jsonrpc "2.0" :id 14 :method "textDocument/signatureHelp" :params
	  (:textDocument
	   (:uri "file:///home/gmbuell/Code/logs.cc")
	   :position
	   (:line 147 :character 15)))

client-request (id:15) Thu May  7 14:18:31 2020:
(:jsonrpc "2.0" :id 15 :method "textDocument/hover" :params
	  (:textDocument
	   (:uri "file:///home/gmbuell/Code/logs.cc")
	   :position
	   (:line 147 :character 15)))

client-request (id:16) Thu May  7 14:18:31 2020:
(:jsonrpc "2.0" :id 16 :method "textDocument/documentHighlight" :params
	  (:textDocument
	   (:uri "file:///home/gmbuell/Code/logs.cc")
	   :position
	   (:line 147 :character 15)))

server-reply (id:13) ERROR Thu May  7 14:18:31 2020:
(:error
 (:code -32602 :message "trying to get preamble for non-added document")
 :id 13 :jsonrpc "2.0")

client-request (id:17) Thu May  7 14:18:31 2020:
(:jsonrpc "2.0" :id 17 :method "textDocument/completion" :params
	  (:textDocument
	   (:uri "file:///home/gmbuell/Code/logs.cc")
	   :position
	   (:line 147 :character 15)
	   :context
	   (:triggerKind 1)))

server-reply (id:14) ERROR Thu May  7 14:18:31 2020:
(:error
 (:code -32602 :message "trying to get preamble for non-added document")
 :id 14 :jsonrpc "2.0")

internal (id:14) ERROR Thu May  7 14:18:31 2020:
(:message "error ignored, status set (trying to get preamble for non-added document)" :id 14 :error -32602)

server-reply (id:15) ERROR Thu May  7 14:18:31 2020:
(:error
 (:code -32602 :message "trying to get AST for non-added document")
 :id 15 :jsonrpc "2.0")

internal (id:15) ERROR Thu May  7 14:18:31 2020:
(:message "error ignored, status set (trying to get AST for non-added document)" :id 15 :error -32602)

server-reply (id:16) ERROR Thu May  7 14:18:31 2020:
(:error
 (:code -32602 :message "trying to get AST for non-added document")
 :id 16 :jsonrpc "2.0")

internal (id:16) ERROR Thu May  7 14:18:31 2020:
(:message "error ignored, status set (trying to get AST for non-added document)" :id 16 :error -32602)

server-reply (id:17) ERROR Thu May  7 14:18:31 2020:
(:error
 (:code -32602 :message "trying to get preamble for non-added document")
 :id 17 :jsonrpc "2.0")
```

**Comment by joaotavora** [comment] 2020-05-07 21:48
Can you please try upgrading your version of the `jsonrpc` package from GNU Elpa?  If you do so, I believe the events buffer will have much more information. Then you can edit your post and put the new version, no need to make a new post.  

I will remove the "server-bug" label, since it's not necessarily a server bug.

**Comment by gmbuell** [comment] 2020-05-07 22:06
Hows this?
```
[stderr] V[15:02:15.609] Building first preamble for /home/gmbuell/Code/logs.cc version 0
[client-notification] Thu May  7 15:02:16 2020:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
	  (:textDocument
	   (:uri "file:///home/gmbuell/Code/logs.cc" :version 16)
	   :contentChanges
	   [(:range
	     (:start
	      (:line 147 :character 2)
	      :end
	      (:line 147 :character 5))
	     :rangeLength 3 :text "")
	    (:range
	     (:start
	      (:line 147 :character 2)
	      :end
	      (:line 147 :character 2))
	     :rangeLength 0 :text "features")
	    (:range
	     (:start
	      (:line 147 :character 5)
	      :end
	      (:line 147 :character 10))
	     :rangeLength 5 :text "")
	    (:range
	     (:start
	      (:line 147 :character 2)
	      :end
	      (:line 147 :character 5))
	     :rangeLength 3 :text "")
	    (:range
	     (:start
	      (:line 147 :character 2)
	      :end
	      (:line 147 :character 10))
	     :rangeLength 8 :text "features")]))
[client-request] (id:6) Thu May  7 15:02:16 2020:
(:jsonrpc "2.0" :id 6 :method "textDocument/signatureHelp" :params
	  (:textDocument
	   (:uri "file:///home/gmbuell/Code/logs.cc")
	   :position
	   (:line 147 :character 10)))
[client-request] (id:7) Thu May  7 15:02:16 2020:
(:jsonrpc "2.0" :id 7 :method "textDocument/hover" :params
	  (:textDocument
	   (:uri "file:///home/gmbuell/Code/logs.cc")
	   :position
	   (:line 147 :character 10)))
[client-request] (id:8) Thu May  7 15:02:16 2020:
(:jsonrpc "2.0" :id 8 :method "textDocument/documentHighlight" :params
	  (:textDocument
	   (:uri "file:///home/gmbuell/Code/logs.cc")
	   :position
	   (:line 147 :character 10)))
[stderr] V[15:02:16.135] <<< {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end":{"character":5,"line":147},"start":{"character":2,"line":147}},"rangeLength":3,"text":""},{"range":{"end":{"character":2,"line":147},"start":{"character":2,"line":147}},"rangeLength":0,"text":"features"},{"range":{"end":{"character":10,"line":147},"start":{"character":5,"line":147}},"rangeLength":5,"text":""},{"range":{"end":{"character":5,"line":147},"start":{"character":2,"line":147}},"rangeLength":3,"text":""},{"range":{"end":{"character":10,"line":147},"start":{"character":2,"line":147}},"rangeLength":8,"text":"features"}],"textDocument":{"uri":"file:///home/gmbuell/Code/logs.cc","version":16}}}
[stderr] 
[stderr] I[15:02:16.135] <-- textDocument/didChange
[stderr] E[15:02:16.135] Failed to update /home/gmbuell/Code/logs.cc utf-16 offset 10 is invalid for line 147
[stderr] V[15:02:16.136] <<< {"id":6,"jsonrpc":"2.0","method":"textDocument/signatureHelp","params":{"position":{"character":10,"line":147},"textDocument":{"uri":"file:///home/gmbuell/Code/logs.cc"}}}
[stderr] 
[stderr] I[15:02:16.136] <-- textDocument/signatureHelp(6)
[stderr] I[15:02:16.136] --> reply:textDocument/signatureHelp(6) 0 ms, error: -32602: trying to get preamble for non-added document
[stderr] V[15:02:16.136] >>> {"error":{"code":-32602,"message":"trying to get preamble for non-added document"},"id":6,"jsonrpc":"2.0"}
[stderr] 
[stderr] V[15:02:16.137] <<< {"id":7,"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":10,"line":147},"textDocument":{"uri":"file:///home/gmbuell/Code/logs.cc"}}}
[stderr] 
[stderr] I[15:02:16.137] <-- textDocument/hover(7)
[stderr] I[15:02:16.137] --> reply:textDocument/hover(7) 0 ms, error: -32602: trying to get AST for non-added document
[stderr] V[15:02:16.137] >>> {"error":{"code":-32602,"message":"trying to get AST for non-added document"},"id":7,"jsonrpc":"2.0"}
[stderr] 
[stderr] V[15:02:16.137] <<< {"id":8,"jsonrpc":"2.0","method":"textDocument/documentHighlight","params":{"position":{"character":10,"line":147},"textDocument":{"uri":"file:///home/gmbuell/Code/logs.cc"}}}
[stderr] 
```

**Comment by joaotavora** [comment] 2020-05-07 22:18
niice.  Now can you paste it into your other report by editing the comment so we don't lose ourselves here?

**Comment by joaotavora** [comment] 2020-05-07 22:22
Bah, this looks like a return of the non lsp-abiding column thing.   I'll try to reproduce/analyse this tomorrow or this weekend, unless someone beats me to it.

**Comment by Swassie** [comment] 2020-05-23 12:39
I have also experienced this issue using:
eglot-20200521.920
yasnippet-20200413.2221
clangd 9.0.0

It only occurs when using yasnippet and it can be reproduced with the following example:
`
int foo(int addr) {
    return 1;
}

int main() {
    fo // Completing foo here triggers the error.
    return 0;
}
`

**Comment by joaotavora** [comment] 2020-05-23 12:40
Thanks, I was going to look at this this weekend.  Hopefully your clear reproduction recipe helps.

**Comment by Swassie** [comment] 2020-05-23 12:58
Great work with eglot and yasnippet btw. Do you accept donations?

**Comment by joaotavora** [comment] 2020-05-23 13:28
> Great work with eglot and yasnippet btw. 

Thanks.  Yasnippet is now maintained by Noam Postavsky, has been for some years.

> Do you accept donations?

No.  You can buy me an actual coffee if you ever come to Lisbon :-) Until then, the only donation I can accept is your patience that I do this on my free time. Of course, if you or a group of people want to hire me in the future to do some specific work, we can look at it.

**Comment by joaotavora** [comment] 2020-05-23 14:15
> Until then, the only donation I can accept is your patience that I do this on my free time

Also, forgot to mention that Eglot is the work of many.  I'm the author and the maintainer but not the only developer.

**Comment by joaotavora** [comment] 2020-05-24 10:07
@Swassie, I'm sorry but I can't reproduce this:

This is what I tried. `emacs` is Emacs 26.3, and I assume the packages Eglot depends on are installed, along with `yasnippet` and `company`.  Then I place myself in the directory where eglot lives and type this:
```
emacs -Q -L . -f package-initialize -f yas-global-mode -f global-company-mode -l eglot ~/tmp/coiso.c 
```

here, `coiso.c` is the file you sent me.  After this I type `M-x eglot` and choose `clangd` which is:
```
clangd version 9.0.0-2 (tags/RELEASE_900/final)
```

IThen go to the position you tell me to and do `M-x company-complete`, which gives me `foo` and `for` to choose from.  They are both snippets, even though the first tells you it's an "int". Selecting either of them is unproblematic.

I also tried this without `company` and it works.

Marking this irredproducible for now.  Can you try the above recipe?  If it works for you we have to bisect something in your configuration.

I've read above it might be related to a new yasnippet.  Going to try that...

**Comment by joaotavora** [comment] 2020-05-24 10:27
I really can't reproduce it.  I'm tempted to close this as a server-bug again.

**Comment by joaotavora** [comment] 2020-05-24 10:36
This is relevant, one of the clangd developers seems to have the same issue: https://github.com/llvm/clangd-www/pull/1#issuecomment-629137247

**Comment by joaotavora** [comment] 2020-05-24 10:45
@gmbuell, I've now tried with your recipe exactly and I also can't reproduce this.  Are you still experiencing this?  Can you do an even more precise recipe where you show exactly how to invoke emacs and what to type at each step?

**Comment by Swassie** [comment] 2020-05-24 11:21
I'm using Emacs 27.0.91, that might be why we're getting different results.

**Comment by joaotavora** [comment] 2020-05-24 16:15
@Swassie I've just tried with that version same result.  Did you follow _my_ recipe exactly?

**Comment by joaotavora** [comment] 2020-05-24 18:51
Since I can't reproduce locally, I can only analyse this part.  It look like @gmbuell had just completed the fragment `"fea"` to `"features"` on some line 147 and Eglot produced this change list, which is suspicious, but I'm not 100% sure is wrong.
```
[(:range
	     (:start
	      (:line 147 :character 2)
	      :end
	      (:line 147 :character 5))
	     :rangeLength 3 :text "")
	    (:range
	     (:start
	      (:line 147 :character 2)
	      :end
	      (:line 147 :character 2))
	     :rangeLength 0 :text "features")
	    (:range
	     (:start
	      (:line 147 :character 5)
	      :end
	      (:line 147 :character 10))
	     :rangeLength 5 :text "")
	    (:range
	     (:start
	      (:line 147 :character 2)
	      :end
	      (:line 147 :character 5))
	     :rangeLength 3 :text "")
	    (:range
	     (:start
	      (:line 147 :character 2)
	      :end
	      (:line 147 :character 10))
	     :rangeLength 8 :text "features")]
```

**Comment by joaotavora** [comment] 2020-05-24 18:59
I reproduced it!

**Comment by joaotavora** [comment] 2020-05-24 19:09
Indeed, it is caused by a recent change in yasnippet. When I revert it, I get this list of changes:
```
[(:range
	     (:start
	      (:line 3 :character 2)
	      :end
	      (:line 3 :character 5))
	     :rangeLength 3 :text "")
	    (:range
	     (:start
	      (:line 3 :character 2)
	      :end
	      (:line 3 :character 2))
	     :rangeLength 0 :text "features")
	    (:range
	     (:start
	      (:line 3 :character 5)
	      :end
	      (:line 3 :character 10))
	     :rangeLength 5 :text "")
	    (:range
	     (:start
	      (:line 3 :character 2)
	      :end
	      (:line 3 :character 5))
	     :rangeLength 3 :text "")
	    (:range
	     (:start
	      (:line 3 :character 2)
	      :end
	      (:line 3 :character 2))
	     :rangeLength 0 :text "features")]
```

Of course, I don't know who is the culprit here, but pinging @npostavs anyway.  Noam, the change is:
```
commit 1cc1996074bdd8fa4e94a51171f5f4ae35f6600b
Author: Noam Postavsky <npostavs@users.sourceforge.net>
Date:   Mon Mar 30 21:35:42 2020 -0400

    Don't bind inhibit-modification-hooks in yas--snippet-create
    
    * yasnippet.el (yas--snippet-create): Bind before-change-functions and
    after-change-functions to nil instead of inhibit-modification-hooks to
    t while expanding snippet.  The latter also needlessly blocks overlay
    and text property modification hooks (which we don't call ourselves
    afterwards).  This way we allow packages like iedit to better
    co-operate with yasnippet.
```

Can you shed some light on this?  If you can't i still have some details to analyse anyway, like carefully stepping/tracing each step.  Eglot is calling `yas-expand-snippet` once manually, but the calls to `after-change-function` and `before-change-function`, which yasnippet now undertakes to do manually, have changed.

**Comment by joaotavora** [comment] 2020-05-24 19:11
The temporary workaround is to downgrade yasnippet to not contain that particular change.

**Comment by Swassie** [comment] 2020-05-24 19:56
I followed your instructions, but with Emacs 27, and I get the same result as before. The snippet loads correctly, but immediately it says error next to eglot in the modeline and all LSP interactions fail. Tell me if you need any logs/info.

**Comment by joaotavora** [comment] 2020-05-24 21:36
> I followed your instructions, but with Emacs 27, and I get the same result as before. The snippet loads correctly, but immediately it says error next to eglot in the modeline and all LSP interactions fail. Tell me if you need any logs/info.

In the meantime, I reproduced the problem.  I don't know what I was doing wrong but for the record, it is enough for me to complete the fragment `"fea"` into "`features`".

**Comment by joaotavora** [comment] 2020-05-24 21:42
Continuing with my analysis here it seems it is this last element which doesn't make sense and clangd complains about.  
```
(:range
	     (:start
	      (:line 147 :character 2)
	      :end
	      (:line 147 :character 10))
	     :rangeLength 8 :text "features")]
```

By this point, the fragments `"fea"` and `"features"` have been added and deleted, and line 147 no longer has a column 10.  Therefore telling `clangd` to replace columns 2-10 with the 8-character word `"features"` is an invalid LSP request.  

Before the yasnippet change, `:rangeLength` was 0 and Eglot would ask clang to replace columns 2-2 with the text `"features"` which means "insert `"features"`".  That is correct.

**Comment by joaotavora** [comment] 2020-05-24 22:26
I'm 99% sure the problem was in yasnippet, so I took the liberty of fixing it there (a perk of being former maintainer :-)  ).  @npostavs take a look when you can.

**Comment by joaotavora** [comment] 2020-05-24 22:26
Closing the issue here.  Let me know if the problem isn't fixed with the latest Yasnippet from git (or MELPA).

**Closed by joaotavora** 2020-05-24 22:26 UTC

**Comment by npostavs** [comment] 2020-05-24 23:02
> I'm 99% sure the problem was in yasnippet, so I took the liberty of fixing it there (a perk of being former maintainer :-) )

>     The previous implementation calculated the length of the affected region after that change
>     happened, which is wrong.

Yep, looks like I just had before and after mixed up, thanks for the fix :)

**Comment by joaotavora** [comment] 2020-05-25 00:21
Thanks!
