### ISSUE TITLE
completion crashes after recent commit

### ISSUE THREAD

**Issue by PerMildner** [joaotavora/eglot#278] opened 2019-07-04 14:46 UTC
The current version (80b315b230b50c9dcd4ad358e85dc73708fd5050) of eglot.pl crashes when doing completion.  This does not happen with the [ELPA](https://elpa.gnu.org/packages/eglot.html) version.

The reason seems to be the below change which goes from using `plist-get` (whose documentation says "never signals an error.") to using `cl-getf` which rightly complains that `completion-capability` (which is `t`) is not a proper plist.

An obvious guess is that the change just exposes a preexisting bug. Briefly looking at the code makes be believe that `completion-capability` is never a plist (it is the result of the test `(eglot--server-capable :completionProvider)`).

```
-bash$ git diff d65d1394~1..d65d1394
diff --git a/eglot.el b/eglot.el
index 2d1c367..a4b7f8f 100644
--- a/eglot.el
+++ b/eglot.el
@@ -1911,9 +1911,12 @@ is not active."
                (insert formatted)
                (current-buffer)))))
        :company-prefix-length
-       (cl-some #'looking-back
-                (mapcar #'regexp-quote
-                        (plist-get completion-capability :triggerCharacters)))
+       (save-excursion
+         (when (car bounds) (goto-char (car bounds)))
+         (looking-back
+          (regexp-opt
+           (cl-coerce (cl-getf completion-capability :triggerCharacters) 'list))
+          (line-beginning-position)))
        :exit-function
        (lambda (comp _status)
          (let ((comp (if (get-text-property 0 'eglot--lsp-completion comp)
```

The backtrace is:
```
Debugger entered--Lisp error: (wrong-type-argument plistp t)
  plist-member(t :triggerCharacters)
  cl-getf(t :triggerCharacters)
  (cl-coerce (cl-getf completion-capability :triggerCharacters) (quote list))
  (regexp-opt (cl-coerce (cl-getf completion-capability :triggerCharacters) (quote list)))
  (looking-back (regexp-opt (cl-coerce (cl-getf completion-capability :triggerCharacters) (quote list))) (line-beginning-position))
  (save-excursion (if (car bounds) (progn (goto-char (car bounds)))) (looking-back (regexp-opt (cl-coerce (cl-getf completion-capability :triggerCharacters) (quote list))) (line-beginning-position)))
  (list (or (car bounds) (point)) (or (cdr bounds) (point)) (function (lambda (string pred action) (if (eq action (quote metadata)) metadata (funcall (completion-table-dynamic (function (lambda ... ...))) string pred action)))) :annotation-function (function (lambda (obj) (let ((object-once (get-text-property 0 (quote eglot--lsp-completion) obj))) (let* ((--cl-rest-- object-once) (detail (car ...)) (kind (car ...)) (insertTextFormat (car ...))) (eglot--call-with-interface (assoc (quote CompletionItem) eglot--lsp-interface-alist) object-once (function (lambda nil ...))))))) :company-doc-buffer (function (lambda (obj) (let* ((documentation (let (...) (or ... ...))) (formatted (and documentation (eglot--format-markup documentation)))) (if formatted (progn (save-current-buffer (set-buffer ...) (erase-buffer) (insert formatted) (current-buffer))))))) :company-prefix-length (save-excursion (if (car bounds) (progn (goto-char (car bounds)))) (looking-back (regexp-opt (cl-coerce (cl-getf completion-capability :triggerCharacters) (quote list))) (line-beginning-position))) :exit-function (function (lambda (comp _status) (let ((comp (if (get-text-property 0 ... comp) comp (cl-find comp strings :test ...)))) (let ((object-once (get-text-property 0 ... comp))) (let* ((--cl-rest-- object-once) (insertTextFormat ...) (insertText ...) (textEdit ...) (additionalTextEdits ...)) (eglot--call-with-interface (assoc ... eglot--lsp-interface-alist) object-once (function ...))))))))
  (progn (list (or (car bounds) (point)) (or (cdr bounds) (point)) (function (lambda (string pred action) (if (eq action (quote metadata)) metadata (funcall (completion-table-dynamic (function ...)) string pred action)))) :annotation-function (function (lambda (obj) (let ((object-once (get-text-property 0 ... obj))) (let* ((--cl-rest-- object-once) (detail ...) (kind ...) (insertTextFormat ...)) (eglot--call-with-interface (assoc ... eglot--lsp-interface-alist) object-once (function ...)))))) :company-doc-buffer (function (lambda (obj) (let* ((documentation (let ... ...)) (formatted (and documentation ...))) (if formatted (progn (save-current-buffer ... ... ... ...)))))) :company-prefix-length (save-excursion (if (car bounds) (progn (goto-char (car bounds)))) (looking-back (regexp-opt (cl-coerce (cl-getf completion-capability :triggerCharacters) (quote list))) (line-beginning-position))) :exit-function (function (lambda (comp _status) (let ((comp (if ... comp ...))) (let ((object-once ...)) (let* (... ... ... ... ...) (eglot--call-with-interface ... object-once ...))))))))
  (if completion-capability (progn (list (or (car bounds) (point)) (or (cdr bounds) (point)) (function (lambda (string pred action) (if (eq action (quote metadata)) metadata (funcall (completion-table-dynamic ...) string pred action)))) :annotation-function (function (lambda (obj) (let ((object-once ...)) (let* (... ... ... ...) (eglot--call-with-interface ... object-once ...))))) :company-doc-buffer (function (lambda (obj) (let* ((documentation ...) (formatted ...)) (if formatted (progn ...))))) :company-prefix-length (save-excursion (if (car bounds) (progn (goto-char (car bounds)))) (looking-back (regexp-opt (cl-coerce (cl-getf completion-capability :triggerCharacters) (quote list))) (line-beginning-position))) :exit-function (function (lambda (comp _status) (let ((comp ...)) (let (...) (let* ... ...))))))))
  (let* ((bounds (bounds-of-thing-at-point (quote symbol))) (server (eglot--current-server-or-lose)) (completion-capability (eglot--server-capable :completionProvider)) (sort-completions (function (lambda (completions) (sort completions (function (lambda ... ...)))))) (metadata (list (quote metadata) (cons (quote display-sort-function) sort-completions))) strings) (if completion-capability (progn (list (or (car bounds) (point)) (or (cdr bounds) (point)) (function (lambda (string pred action) (if (eq action ...) metadata (funcall ... string pred action)))) :annotation-function (function (lambda (obj) (let (...) (let* ... ...)))) :company-doc-buffer (function (lambda (obj) (let* (... ...) (if formatted ...)))) :company-prefix-length (save-excursion (if (car bounds) (progn (goto-char ...))) (looking-back (regexp-opt (cl-coerce ... ...)) (line-beginning-position))) :exit-function (function (lambda (comp _status) (let (...) (let ... ...))))))))
  eglot-completion-at-point()
  completion--capf-wrapper(eglot-completion-at-point all)
  run-hook-wrapped(completion--capf-wrapper eglot-completion-at-point all)
  completion-at-point()
  complete-symbol(nil)
  funcall-interactively(complete-symbol nil)
  call-interactively(complete-symbol nil nil)
  command-execute(complete-symbol)
```

**Comment by nemethf** [comment] 2019-09-11 13:39
Can you paste the first part of the events buffer?  I'm curious about the server's capabilities.  Usually it has "(id:1)" and starts with "(:result (:capabilities".  I cannot reproduce the bug, so it would help if you could provide a minimal, self-contained example as well.

**Comment by PerMildner** [comment] 2019-09-11 14:07
I can not do this "soon" (lack of time).

**Comment by nemethf** [comment] 2019-09-11 14:17
No problem.  It just occurred to me that this issue might have server-side aspects as well because in your other issue you used an "exotic" server (prolog, maybe).

**Comment by nemethf** [comment] 2019-09-30 13:27
I think 6d87de16 fixed this, so I'm closing the issue.  If not, please, reopen it and paste the first part of the events buffer.

**Closed by nemethf** 2019-09-30 13:27 UTC
