### ISSUE TITLE
Freezes after connected on certain build

### ISSUE THREAD

**Issue by nree** [joaotavora/eglot#247] opened 2019-04-04 15:50 UTC
See: https://github.com/mooz/js2-mode/issues/522

Or see recap below.

**Comment by eabarbosa** [comment] 2019-04-04 20:17
maybe, the update should be at the top of your issue?!

**Comment by nemethf** [comment] 2019-04-05 09:20
One thing you could try out is to run these experiments on GNU/Linux (or Windows) with official emacs builds to make sure a bug was really introduced between version 26.1 and version 26.2-rc1.

**Comment by nree** [comment] 2019-04-05 15:31
What I did was just added a no-op hook for js2-mode-hook, and it triggered the 2 times opened still.

So now I know at least it's not eglot, I'll open issue for js2-mode.

**Comment by nree** [comment] 2019-04-05 15:45
Reference: https://github.com/mooz/js2-mode/issues/522

Though, the freeze only happens with **js2-modehook & eglot**

It opens twice even with rjsx-mode and company-mode hooking into js2 **but it doesn't freeze my emacs.**

So this is still kind of relevant to eglot.

**Comment by nree** [comment] 2019-04-05 15:59
Just tested with rust-mode and hook with eglot is OK, still see Open ... [2 times]
At this point I don't know how relevant that is anymore since every other situation it doesn't matter. It could be an issue with the emacs port, or emacs version I'm using. 

_But it doesn't affect anything else except eglot & js2-mode and the real issue is the 15-20 second freeze.

**Comment by eabarbosa** [comment] 2019-04-05 20:13
Could not reproduce that with js-mode....

**Comment by nree** [comment] 2019-04-07 12:55
And... we're back. Was hard for me to figure out which piece was at fault. I'm convinced this really is a eglot issue now.

### Recap:
Eglot freezes...
- using railwaycat/homebrew-emacsmacport's mac port of emacs, 26.2-rc1 or 26.1. 
- only for js2-mode-hook , not manually running `eglot`. Not for rust-mode.
- does not happen with js2-mode-hook company or rjsx-mode, **does not happen with lsp-mode.**

Could be an issue with the mac port, but at this point lsp-mode does not freeze and eglot does so I don't know.

**Comment by nemethf** [comment] 2019-04-09 11:59
In your (now deleted) original message, you wrote that it worked with emacs version 26.1.  Now you write it doesn't.  That seems contradictory.

**Comment by nree** [comment] 2019-04-10 18:14
@nemethf there is no conspiracy regarding deleting message, you yourself commented my original message wasn't so great (and then deleted your own comment). I'm just trying to make the issue more concise.

But my original statement can still be viewed at https://github.com/mooz/js2-mode/issues/522
>Doesn't matter if .js or .jsx. Doesn't appear to happen on 26.1-2 pre-compiled binary via https://emacsformacosx.com .

And I didn't contradict myself. Same emacs version **but different builds.**  I pointed out it's related to  railwaycat/homebrew-emacsmacport build regardless emacs 26.1 or 26.2.

### But it doesn't matter either way about versions or builds.
**lsp-mode works fine, eglot doesn't.**

**Comment by joaotavora** [comment] 2019-04-10 19:11
@nree, I don't think @nemethf implied any type of conspiracy or ill-will from your behalf ( just a simple incoherence to previous statement ) so please don't attribute this him. Since I can't look at these issues right now, he is trying to help you here, something I value considerably.

**Comment by eabarbosa** [comment] 2019-04-11 01:13
@nree 
You might not know but Eglot JS Server default is other than the lsp-mode JS default Server!

Do try to use that one with Eglot.

Did you open an issue at lsp-mode? Cause it IS important to them to know that its taking a considerable time to load completions.

It's probably related to eglot issue.

But Eglot takes a different route to "hear" LSP servers than lsp-mode.  and 

Anyway, lets help each other, its a friendly project and "lsp-mode vs eglot" do not exist.

Good development!

**Comment by nemethf** [comment] 2019-04-11 08:12
(I haven't deleted any of my comments.)

At any rate, there seem to be two builds for the same emacs version, one of them exhibits the slow-down, the other does not.  I think that's an important piece of information.

**Comment by iambumblehead** [comment] 2019-08-16 16:36
Yesterday I upgraded all emacs packages on this Mac and now opening files in one of my projects causes emacs to freeze with an eglot message in the single line message area near the bottom,

**[eglot] Connected! Server `Eglot (ivy/rjsx-mode)' now managing `rjsx-mode' buffers in project `ivy'.**

Version details details,
 * eglot, 20190812.2013
 * GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511))
```

I will update emacs to version 26.2 to see if this continues there

**Comment by alexanderbarbosa** [comment] 2019-08-16 17:05
@iambumblehead 

Just pick eglot earlies commits

**Comment by iambumblehead** [comment] 2019-08-16 17:07
I gradually commented things out of my .emacs file and found the issue to occur after removing all references to eglot. I found that rjsx-mode causes the freezing here, so removing this line "solves" the issue
```elisp
(add-to-list 'auto-mode-alist '("\\.m?js$" . rjsx-mode))
```

**Comment by iambumblehead** [comment] 2019-08-16 17:26
I followed @alexanderbarbosa's advice, but for rjsx-mode and now my emacs is fully working again with my mostly original .emacs file. I cloned [rjsx-mode] and checked out v0.3.0, then loaded it through my .emacs file,
```elisp
(load-file "~/software/rjsx-mode/rjsx-mode.el")
```

[0]: https://github.com/felipeochoa/rjsx-mode/tree/v0.3.0

**Comment by joaotavora** [comment] 2019-08-16 18:23
@iambumblehead it seems to be that you confirm the issue is exclusive to rjsx-mode, i.e. it has nothing to do with Eglot. Is this correct?

Anyway, better information can probably be obtained by enabling `debug-on-quit`, quitting the "freeze" with `C-g`, and then posting the resulting backtrace here.

> As for "keeping older versions": pick one of eglot early commits, or even better, use straight.el

@alexanderbarbosa I don't think this would accomplish anything and straight.el is known to cause problems. I understand and thank you for your eagerness and energy, but sometimes too eager advice can actually hurt debugging.

**Comment by alexanderbarbosa** [comment] 2019-08-16 19:50
@joaotavora 

You are right. I'll refrain next time, if all I can offer may not particulary really help!

**Comment by iambumblehead** [comment] 2019-08-24 23:50
@joaotavora I'm trying to collection information to share with you and @felipeochoa. If I start emacs with `emacs -Q`, as suggested [here][0], emacs starts without any configuration and won't load rjsx-mode without the js2 dependency. If I start emacs and try M-x `debug-on-quit`, debug-on-quit is not found but debug-on-entry and debug-on-change are suggested auto-completions of "debug-on-"

I'll follow any suggestion you may have.

[0]: https://github.com/felipeochoa/rjsx-mode/issues/116#issuecomment-522097716

**Comment by iambumblehead** [comment] 2019-08-25 00:03
@joaotavora I found `toggle-debug-on-quit` and toggled that before opening one a file with the newest rjsx-mode. When emacs quits at `C-g`, no stacktrace or message is seen :|

**Comment by iambumblehead** [comment] 2019-08-25 00:06
I was able to get something... I'll continue by updating the issue at the rjsx project --thank you @joaotavora

**Comment by skangas** [comment] 2022-01-09 13:43
So is this a bug in `rjsx-mode` then, or is there still something to do in `eglot`?

**Comment by iambumblehead** [comment] 2022-01-09 14:01
@skangas it was an rjsx-mode issue

**Comment by skangas** [comment] 2022-01-09 15:16
> @skangas it was an rjsx-mode issue

OK, I'm therefore closing this bug report. Please reopen if there is anything more to do on eglot's side.

**Closed by skangas** 2022-01-09 15:16 UTC
Labels: moreinfo
