### ISSUE TITLE
wrong-number-of-arguments error

### ISSUE THREAD

**Issue by takafusui** [joaotavora/eglot#556] opened 2020-10-23 09:51 UTC
Hi,

Thanks for the very promising project, and I am now wondering about moving my python development environment from `elpy` to `eglot`.

So far, I installed the necessary packages following your instruction, and now I can see an `[eglot:<servername>]` in my mode-line.
My issue is that when I, for instance, check the arguments of 'np.linspace()' which supposed to be provided in the mini-buffer provided by `eldoc`, I get the following error messages:

1. `toggle-debug-on-error` option:
```python
Debugger entered--Lisp error: (wrong-number-of-arguments ((t) nil "Print help on symbol at point.\n\nIf symbol is defined in current buffer, jump to it's definition" (interactive) (let* ((py-cleanup-p t) (orig (point)) (beg (and (use-region-p) (region-beginning))) (end (and (use-region-p) (region-end))) (symbol (or (and beg end (buffer-substring-no-properties beg end)) (py-symbol-at-point)))) (if (eq orig (condition-case nil (progn py-last-position) (error nil))) nil (setq py-last-position orig)) (and (looking-back "(" (line-beginning-position)) (not (looking-at "\\sw")) (forward-char -1)) (if (or (eq (face-at-point) (quote font-lock-string-face)) (eq (face-at-point) (quote font-lock-comment-face))) (progn (py-restore-window-configuration) (goto-char orig)) (if (not (string= "" symbol)) (py--help-at-point-intern symbol orig))))) 2)
  py-help-at-point("%s" #("linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0): Return evenly spaced numbers over a specified interval.\nstart: array_like" 0 8 (face font-lock-function-name-face) 9 14 (face eldoc-highlight-function-argument) 137 142 (face eldoc-highlight-function-argument)))
  eldoc--message(#("linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0): Return evenly spaced numbers over a specified interval.\nstart: array_like" 0 8 (face font-lock-function-name-face) 9 14 (face eldoc-highlight-function-argument) 137 142 (face eldoc-highlight-function-argument)))
  eldoc--handle-docs(((#("linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0): Return evenly spaced numbers over a specified interval.\nstart: array_like" 0 8 (face font-lock-function-name-face) 9 14 (face eldoc-highlight-function-argument) 137 142 (face eldoc-highlight-function-argument)))))
  #f(compiled-function () #<bytecode 0xf0fb45>)()
  apply(#f(compiled-function () #<bytecode 0xf0fb45>) nil)
  timer-event-handler([t 24466 42489 268278 nil #f(compiled-function () #<bytecode 0xf0fb45>) nil nil 803999])
```
2. `eglot-events-buffer`:
```python
[server-reply] (id:113) Fri Oct 23 11:44:24 2020:
(:jsonrpc "2.0" :id 113 :result
          (:signatures
           [(:label "linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)" :documentation "Return evenly spaced numbers over a specified interval.\n\nReturns `num` evenly spaced samples, calculated over the\ninterval [`start`, `stop`].\n\nThe endpoint of the interval can optionally be excluded.\n\n.. versionchanged:: 1.16.0\n    Non-scalar `start` and `stop` are now supported.\n\nParameters\n----------\nstart : array_like\n    The starting value of the sequence.\nstop : array_like\n    The end value of the sequence, unless `endpoint` is set to False.\n    In that case, the sequence consists of all but the last of ``num + 1``\n    evenly spaced samples, so that `stop` is excluded.  Note that the step\n    size changes when `endpoint` is False.\nnum : int, optional\n    Number of samples to generate. Default is 50. Must be non-negative.\nendpoint : bool, optional\n    If True, `stop` is the last sample. Otherwise, it is not included.\n    Default is True.\nretstep : bool, optional\n    If True, return (`samples`, `step`), where `step` is the spacing\n    between samples.\ndtype : dtype, optional\n    The type of the output array.  If `dtype` is not given, infer the data\n    type from the other input arguments.\n\n    .. versionadded:: 1.9.0\n\naxis : int, optional\n    The axis in the result to store the samples.  Relevant only if start\n    or stop are array-like.  By default (0), the samples will be along a\n    new axis inserted at the beginning. Use -1 to get an axis at the end.\n\n    .. versionadded:: 1.16.0\n\nReturns\n-------\nsamples : ndarray\n    There are `num` equally spaced samples in the closed interval\n    ``[start, stop]`` or the half-open interval ``[start, stop)``\n    (depending on whether `endpoint` is True or False).\nstep : float, optional\n    Only returned if `retstep` is True\n\n    Size of spacing between samples.\n\n\nSee Also\n--------\narange : Similar to `linspace`, but uses a step size (instead of the\n         number of samples).\ngeomspace : Similar to `linspace`, but with numbers spaced evenly on a log\n            scale (a geometric progression).\nlogspace : Similar to `geomspace`, but with the end points specified as\n           logarithms.\n\nExamples\n--------\n>>> np.linspace(2.0, 3.0, num=5)\narray([2.  , 2.25, 2.5 , 2.75, 3.  ])\n>>> np.linspace(2.0, 3.0, num=5, endpoint=False)\narray([2. ,  2.2,  2.4,  2.6,  2.8])\n>>> np.linspace(2.0, 3.0, num=5, retstep=True)\n(array([2.  ,  2.25,  2.5 ,  2.75,  3.  ]), 0.25)\n\nGraphical illustration:\n\n>>> import matplotlib.pyplot as plt\n>>> N = 8\n>>> y = np.zeros(N)\n>>> x1 = np.linspace(0, 10, N, endpoint=True)\n>>> x2 = np.linspace(0, 10, N, endpoint=False)\n>>> plt.plot(x1, y, 'o')\n[<matplotlib.lines.Line2D object at 0x...>]\n>>> plt.plot(x2, y + 0.5, 'o')\n[<matplotlib.lines.Line2D object at 0x...>]\n>>> plt.ylim([-0.5, 1])\n(-0.5, 1)\n>>> plt.show()" :parameters
                    [(:label "start" :documentation "array_like")
                     (:label "stop" :documentation "array_like")
                     (:label "num" :documentation "int, optional")
                     (:label "endpoint" :documentation "bool, optional")
                     (:label "retstep" :documentation "bool, optional")
                     (:label "dtype" :documentation "dtype, optional")
                     (:label "axis" :documentation "int, optional")])]
           :activeSignature 0 :activeParameter 0))
[server-reply] (id:114) Fri Oct 23 11:44:24 2020:
(:jsonrpc "2.0" :id 114 :result
          (:contents
           ["Built-in immutable sequence.\n\nIf no argument is given, the constructor returns an empty tuple.\nIf iterable is specified the tuple is initialized from iterable's items.\n\nIf the argument is a tuple, the return value is the same object."]))
[server-reply] (id:115) Fri Oct 23 11:44:24 2020:
(:jsonrpc "2.0" :id 115 :result nil)
```

Please let me know if you need further information to debug the issue.
Thank you in advance!

**Comment by joaotavora** [comment] 2020-10-23 09:59
What is `py-help-at-point`? It seems some package (maybe ElPy?) is setting the value of `eldoc-message-function` to some function that does some very odd operations. I would advise against that, so if you're moving from ElPy to Eglot, maybe review that. My guess is that if you stop setting `eldoc-message-function` to that thing, then stuff should work normally.

**Comment by takafusui** [comment] 2020-10-23 10:12
Hi,

thank you for your quick response. I commented out my old setting of `elpy` and now even deleted `elpy` package, the problem is still persisted...
Do you suspect that `py-help-at-point` is the error source?
I quickly googled and found the previous issue: https://github.com/joaotavora/eglot/issues/299

I am using `python-mode-20200608.737`.

**Comment by joaotavora** [comment] 2020-10-23 10:14
> Do you suspect that py-help-at-point is the error source?

Yep I think this is a duplicate of #299.  But where does `py-help-at-point` come from anyway?

**Closed by joaotavora** 2020-10-23 10:14 UTC

**Comment by joaotavora** [comment] 2020-10-23 10:15
> Yep I think this is a duplicate of #299. But where does py-help-at-point come from anyway?

Maybe it comes from your `python-mode` package.  Seems to be different from Emacs's built-in `python.el` and problematic.

**Comment by takafusui** [comment] 2020-10-23 10:18
Is `eglot` by default on top of `python-mode`, not on the Emacs`s built-in `python.el` correct?

**Comment by joaotavora** [comment] 2020-10-23 10:40
I wouldn't say "on top" . 

Its just that `python-mode`, (the non-Emacs package, don't confuse with Emacs's built-in `python-mode` command) is buggy. But Eglot can work with any major-mode.  

Where is python-mode's bug tracker??

**Comment by joaotavora** [comment] 2020-10-23 10:40
In the meantime, I would just uninstall `python-mode`.  I wonder if you're losing out of much.

**Comment by takafusui** [comment] 2020-10-23 11:19
Thanks for your comment. Yes as you suggested, `python-mode` from MELPA has `py-help-at-point` function.
When I remove the package, the error is gone. Thank you for your help!

But I am now confusing.
Given that `python-mode` from MELPA is buggy, could you recommend which packages I should use with `eglot`?

**Comment by joaotavora** [comment] 2020-10-23 11:24
> could you recommend which packages I should use with eglot for python coding?

None.  Just eglot and Emacs work fine, in my experience.

**Comment by takafusui** [comment] 2020-10-23 11:39
Thank you for your comment!
Hopefully, the last question to clarify:
In my `init.el`, if I have
```elisp
(add-hook 'python-mode-hook 'eglot-ensure)
(add-to-list 'eglot-server-programs
	     `(python-mode . ("pyls" "-v" "--tcp" "--host"
			      "localhost" "--port" :autoport)))
```
`eglot` does not start automatically. I need to `M-x eglot` and it is fine.

When I have:
```elisp
(autoload 'python-mode "python-mode" "Python Mode." t)
(add-to-list 'auto-mode-alist '("\\.py\\'" . python-mode))
(add-to-list 'interpreter-mode-alist '("python" . python-mode))

(add-hook 'python-mode-hook 'eglot-ensure)

(add-to-list 'eglot-server-programs
	     `(python-mode . ("pyls" "-v" "--tcp" "--host"
			      "localhost" "--port" :autoport)))
```
`eglot` starts automatically.
It seems that without the first three lines, `eglot` does not know that it is `python-mode` or not.

My questions are:
1. Do I need
```elisp
(autoload 'python-mode "python-mode" "Python Mode." t)
(add-to-list 'auto-mode-alist '("\\.py\\'" . python-mode))
(add-to-list 'interpreter-mode-alist '("python" . python-mode))
```
to hook `eglot` with `python-mode`?

2. and if so, which `python-mode` I am now using?
In the previous thread, you mentioned the Emacs's built-in `python-mode`. Where can I find the `.el` file?

**Comment by joaotavora** [comment] 2020-10-23 11:43
1. No
2. You are using the python mode that comes bundled with Emacs.

**Comment by takafusui** [comment] 2020-10-23 12:02
Thanks due to some unknown reasons, I need to `require 'eglot` to automatically lunch the eglot process when I open a python script:
```elisp
(require 'eglot)
(add-hook 'python-mode-hook 'eglot-ensure)
(add-to-list 'eglot-server-programs
	     `(python-mode . ("pyls" "-v" "--tcp" "--host"
			      "localhost" "--port" :autoport)))
```
Does it make sense for you?

**Comment by joaotavora** [comment] 2020-10-23 12:03
Yes, though I don't think you even need the first and last expressions.  You don't need the first because autoloads should take care of that.  And unless you want pyls to work via TCP, you don't need the last line either.

**Comment by joaotavora** [comment] 2020-10-23 12:04
And if you don't mind pressing `M-x eglot` when starting work in a new python project, you don't need the middle line as well.

**Comment by takafusui** [comment] 2020-10-23 12:13
Thank you @joaotavora for the series of your help.
I will play with `eglot` library. Thank you again!!

**Comment by gleblobanov** [comment] 2022-11-19 09:07
@takafusui Hi! I have the same issue with `haskell-mode`. Thank you for the hint to add `(require 'eglot)`. Have you figured out why we should add `(require 'eglot)`?
