### ISSUE TITLE
Wrong argument completion for gopls with yasnippet

### ISSUE THREAD

**Issue by xuchunyang** [joaotavora/eglot#336] opened 2019-11-01 06:08 UTC
For example, [reflect.DeepEqual](https://golang.org/pkg/reflect/#DeepEqual)'s signature is

    func DeepEqual(x, y interface{}) bool

I'm also using company-mode and yasnippet. When I complete `reflect.DeepEqual`, the result is wrong:

![Screen Shot 2019-11-01 at 14 01 12](https://user-images.githubusercontent.com/4550353/68005467-5f033480-fcb0-11e9-8ac2-8b534a7bf434.png)

here is the text it inserts

    	reflect.DeepEqual(${1:x interface{}}, y interface{})

The eglot event buffer contains

```el
(:label "DeepEqual" :kind 3 :detail "func(x interface{}, y interface{}) bool" :documentation "..." :sortText "00012" :insertTextFormat 2 :textEdit
        (:range
         (:start
          (:line 18 :character 13)
          :end
          (:line 18 :character 13))
         :newText "DeepEqual(${1:x interface{\\}}, ${2:y interface{\\}})")
        :command
        (:title "" :command "editor.action.triggerParameterHints"))
```

and `yas-expand-snippet` doesn't work for that `:newText`, e.g.,

```el
(yas-expand-snippet "DeepEqual(${1:x interface{\\}}, ${2:y interface{\\}})")
```

**Comment by s-kostyaev** [comment] 2019-11-01 07:51
this solution: https://github.com/joaotavora/eglot/issues/332#issuecomment-547888669 also fix this issue

**Comment by xuchunyang** [comment] 2019-11-01 08:25
Maybe #333 is related (though that issue does not involve yasnippet) as both of them are about eglot has trouble handling escape from gopls.

**Comment by joaotavora** [comment] 2019-11-01 13:48
Hmmm, maybe we have to take the @s-kostyaev's solution after all, but ideally put it in yasnippet.  @npostavs can you jump here quick?

**Comment by npostavs** [comment] 2019-11-06 17:40
> Hmmm, maybe we have to take the @s-kostyaev's solution after all, but ideally put it in yasnippet. 

It looks like the idea there is to remove the backslashes before the curly braces, but I don't quite understand where the backslashes came from in the first place.

**Comment by s-kostyaev** [comment] 2019-11-06 18:01
From LSP standart. According to it closing curly braces should be escaped.

**Comment by s-kostyaev** [comment] 2019-11-06 18:13
https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_completion

**Comment by npostavs** [comment] 2019-11-06 18:55
> From LSP standart. According to it closing curly braces inside snippets should be escaped.

Ah, it makes sense to remove those escapes then.

> but ideally put it in yasnippet. 

I guess the function which removes the escapes (and potentially does some other LSP-specific translation stuff) could go in yasnippet, but it should be called by elgot, since yasnippet wouldn't otherwise know whether the escapes should be removed or not.

**Comment by joaotavora** [comment] 2019-11-06 19:08
> I guess the function which removes the escapes (and potentially does some other LSP-specific translation stuff) could go in yasnippet, but it should be called by elgot, since yasnippet wouldn't otherwise know whether the escapes should be removed or not.

That's not bad. Let's do that.

But can't really yasnippet know that `\\}` means "a literal closing brace"?  Yasnippet was designed from Textmate's snippet syntax.  And so was LSP (you can spot this because they support "TM_TEXT" and such variables)  Textmate was a long time ago, but theoretically the syntaxes should match, or maybe could be made to match.

**Comment by npostavs** [comment] 2019-12-13 21:14
> But can't really yasnippet know that `\\}` means "a literal closing brace"?

What about current snippets using it to mean "a backslash followed by a brace"?

> Yasnippet was designed from Textmate's snippet syntax. And so was LSP

Ah, you mean yasnippet ought to have interpreted that way from the beginning? Since they've diverged for a while it's a bit dicey to change, but I wouldn't be entirely opposed to it. Maybe have a user option (although that makes it difficult to share snippets between users)?

**Comment by joaotavora** [comment] 2019-12-14 10:31
> Maybe have a user option (although that makes it difficult to share snippets between users)?

I think only a minute portion of such snippets would be unshareable anyway.  Yasnippet has been around a long time, so the user option probably makes sense, but I would default it to `t`, by the way, meaning, by default Yasnippet would respect the original Textmate syntax.

That is of course, if we are sure that it wasn't LSP that messed up.  If it was, then we have to rethink (because I don't think the LSP/VsCode folks are going to budge for us).

**Comment by npostavs** [comment] 2020-03-26 01:10
I'm revisiting some backlog; it seems that `"\\}"` actually does already mean "literal closing brace" to yasnippet. It's just that yasnippet cat get confused about the nesting of field constructs in that case. So I'd say this is pretty much just a plain bug in yasnippet and won't need any user options.

Example, `(yas-expand-snippet "a{\\}b")` => `a{}b`

**Comment by skangas** [comment] 2022-01-09 01:34
This seems to have been fixed in yasnippet, so I'm closing this bug. If that conclusion is incorrect, please speak up and we can re-open. Thanks.

**Closed by skangas** 2022-01-09 01:34 UTC
