### ISSUE TITLE
Incorrect implementation of "textDocument/documentSymbol"?

### ISSUE THREAD

**Issue by sstepashka** [joaotavora/eglot#451] opened 2020-05-01 03:50 UTC
I have the following error for my (corporate clangd) LSP server when I try to use imenu. 

>>>
bugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  eglot--lsp-position-to-point(nil)
  #f(compiled-function () #<bytecode 0xee9cc9>)()
  eglot--call-with-interface((SymbolInformation (:name :kind :location) (:deprecated :containerName)) ...
>>>

I was able to find some flag and debug it more:

(setq eglot-strict-mode '(disallow-non-standard-keys enforce-required-keys))

Now when I run imenu I see the following error:
>>>
In ‘Imenu’ source: ‘helm-imenu-candidates’ 
 (error "[eglot] A `SymbolInformation' must have (:location)")
>>>

Looks like eglot uses |SymbolInformation| interface to handle |DocumentSymbol| and seems like it's incorrect because |DocumentSymbol| doesn't contain "location" (by this specification: https://microsoft.github.io/language-server-protocol/specifications/specification-current/), but does contain "children". In eglot code I didn't fine any mention of "children".

That would be great to have "code outline" through LSP, since emacs embedded imenu functionality (And any I could find) doesn't work with C++ well.

Thank you.

**Comment by galeo** [comment] 2020-05-01 15:57
You may want to have a look at #303, although the problem is still not solved.

**Comment by joaotavora** [comment] 2020-05-03 00:03
Can you try with the newest master?  I fixed #303 recently, but I didn't test much. Thanks.

**Comment by joaotavora** [comment] 2020-05-03 20:14
I'm reasonably sure this was fixed in recent commits ef6c48328836434fa4dca68450c72aba2601a357 and da04fdcf62b622f7d7e6ddba0ea3e95e9143270f.  But I'll reopen if I'm mistaken.

**Closed by joaotavora** 2020-05-03 20:14 UTC

**Comment by sstepashka** [comment] 2020-05-06 16:09
Sorry fo delay. It works! thank you very much!
