### ISSUE TITLE
How do I refresh flymake errors (C++ with ccls)?

### ISSUE THREAD

**Issue by amosnier** [joaotavora/eglot#170] opened 2018-11-24 20:33 UTC
Still very happy with eglot, and I am currently using ccls for C++ with it. After I have corrected an error reported by flymake, how do I refresh the flymake errors? Apparently, closing the file and reopening it works, but is there a way without closing the file? Please note that my correction could for instance be in a macro located in an included header file.

**Comment by joaotavora** [comment] 2018-12-02 11:09
This appears to be a dupe of #159. Closing it in favor or that other bug.  Let me know if it's not a duplicate and I will reopen.

**Closed by joaotavora** 2018-12-02 11:09 UTC
