### ISSUE TITLE
Eglot mustn't have data is wrong

### ISSUE THREAD

**Issue by theothornhill** [joaotavora/eglot#628] opened 2021-02-26 20:17 UTC
Eglot is reporting that diagnostics mustnt have :data, which also is wrong: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#diagnostic

```
(:message "Parsing error." :source "Elm" :severity 1 :range
                           (:start
                            (:line 122 :character 84)
                            :end
                            (:line 122 :character 88))
                           :data
                           (:uri "file:///Users/theodor/Git/mypage/elm/Navigation.elm" :code "parsing"))
```

**Comment by joaotavora** [comment] 2021-02-26 20:18
I think if you compile the `eglot.el` file it will go away.  you are probably evaluating the buffer, which means you want to develop eglot and it sets `eglot-strict-mode` to `disallow-non-standard-keys`. (non standard according to the understading of Eglot of the standard, which admittedly is outdated).

Closing this, as I'm fairly sure this is the cause, but will reopen if it isn't.

**Closed by joaotavora** 2021-02-26 20:18 UTC

**Comment by theothornhill** [comment] 2021-02-26 20:23
Yeah, you are right. 

(Should we still update the interfaces, though?)

**Comment by joaotavora** [comment] 2021-02-26 20:24
> Should we still update the interfaces, though?

Yes, that doesn't hurt. 

Normally we do that when we plan to use the information contained therein.    I designed this to catch non-conforming or typoed fields from servers, but indeed it's pretty useless if the interfaces aren't up-to-date.  PR welcome!

**Comment by theothornhill** [comment] 2021-02-26 20:26
Would you want all of them in one or one by one?

**Comment by joaotavora** [comment] 2021-02-26 20:28
As many as you can find!  Even better, and perhaps less boring, generate the Lisp automatically from some JSON spec document. 

But doing it manually is fine.

**Comment by theothornhill** [comment] 2021-02-26 20:29
Ok :) Thanks for your attention!
