### ISSUE TITLE
Render Markdown in help buffer

### ISSUE THREAD

**Issue by dhess** [joaotavora/eglot#271] opened 2019-06-01 00:28 UTC
`haskell-ide-engine` delivers docs as Markdown, but when these are rendered in the  *eglot-help* buffer (`eglot-put-doc-in-help-buffer` and `eglot-auto-display-help-buffer` enabled), it appears as though Eglot is trying to syntax-highlight the contents as Haskell code, rather than Markdown.

Here's an example server-reply:

```
server-reply (id:148) Sat Jun  1 01:26:57 2019:
(:result
 (:contents
  (:kind "markdown" :value "\n```haskell\nGeneric :: GHC.Generics.Rep AwsVaultExecOptions x -> AwsVaultExecOptions\n```\nRepresentable types of kind `*`.\n This class is derivable in GHC with the `DeriveGeneric` flag on.\n\nA `Generic` instance must satisfy the following laws:\n\n\n```haskell\n`from` . `to` ≡ `id`\n`to` . `from` ≡ `id`\n\n```\n\n\n[Documentation](file:///nix/store/wyh4xaffa9dilp5szi9lvc64ggrpz0ds-ghc-8.6.5-doc/share/doc/ghc/html/libraries/base-4.12.0.0/GHC-Generics.html#t:Generic)\n\n[Source](file:///nix/store/wyh4xaffa9dilp5szi9lvc64ggrpz0ds-ghc-8.6.5-doc/share/doc/ghc/html/libraries/base-4.12.0.0/src/GHC-Generics.html#Generic)\n\nbase GHC.Generics")
  :range
  (:start
   (:line 52 :character 18)
   :end
   (:line 52 :character 25)))
 :jsonrpc "2.0" :id 148)
```

And a screenshot of the help buffer:

<img width="709" alt="Screen Shot 2019-06-01 at 1 27 41 AM" src="https://user-images.githubusercontent.com/2438/58741006-878ab800-840c-11e9-9c0f-47494a0b37fa.png">

**Comment by nemethf** [comment] 2020-01-13 17:10
If I'm correct this is a bug on the server side.  Because I think when you submitted this bug report, Eglot did not specified it was capable of handling "markdown" texts.  But fear not, #329 added markdown support for hover texts.  So hopefully, your problem have been solved.  Can you check if the help is now formatted with gfm-view-mode?

**Comment by nemethf** [comment] 2020-05-10 09:27
I assume the problem is now solved and close this issue.  If you disagree, comment here and I'll reopen.

**Closed by nemethf** 2020-05-10 09:27 UTC
