### ISSUE TITLE
Feature Request: show code actions in modeline

### ISSUE THREAD

**Issue by chmouel** [joaotavora/eglot#1073] opened 2022-10-07 09:25 UTC
More of a Feature Request than a bug report. It would be nice if we were able to show the "code actions" available at point in the modeline.

Currently we need to "request" for it via elgot-code-actions to figure out if one is available at point.

**Comment by joaotavora** [comment] 2022-10-07 09:44
Did you read the instructions at all before deleting them?

**Comment by joaotavora** [comment] 2022-10-07 09:44
Duplicate of #1070 .

**Closed by joaotavora** 2022-10-07 09:44 UTC

**Comment by chmouel** [comment] 2022-10-07 09:45
oops very sorry i was looking for modeline string and could not find the string anywhere, i did search on reddit/stackoverflow and github issues

**Comment by chmouel** [comment] 2022-10-07 09:48
sorry about that should have read this better,
