### ISSUE TITLE
Undefined function project-root when using eglot

### ISSUE THREAD

**Issue by notmgsk** [joaotavora/eglot#518] opened 2020-07-27 23:45 UTC
Backtrace upon `eglot`:

```
Debugger entered--Lisp error: (void-function project-root)
  (project-root project)
  (let* ((default-directory (project-root project)) (nickname (file-name-base (directory-file-name default-directory))) (readable-name (format "EGLOT (%s/%s)" nickname managed-major-mode)) autostart-inferior-process (contact (if (functionp contact) (funcall contact) contact)) (initargs (cond ((keywordp (car contact)) contact) ((integerp (car (cdr contact))) (list (quote :process) (function (lambda nil ...)))) ((and (stringp (car contact)) (memq :autoport contact)) (list (quote :process) (function (lambda nil ...)))) ((stringp (car contact)) (list (quote :process) (function (lambda nil ...)))))) (spread (function (lambda (fn) (function (lambda (server method params) (apply fn server method ...)))))) (server (apply (function make-instance) class :name readable-name :events-buffer-scrollback-size eglot-events-buffer-size :notification-dispatcher (funcall spread (function eglot-handle-notification)) :request-dispatcher (funcall spread (function eglot-handle-request)) :on-shutdown (function eglot--on-shutdown) initargs)) (cancelled nil) (tag (make-symbol "connected-catch-tag"))) (let* ((v server)) (\(setf\ eglot--saved-initargs\) initargs v)) (let* ((v server)) (\(setf\ eglot--project\) project v)) (let* ((v server)) (\(setf\ eglot--project-nickname\) nickname v)) (let* ((v server)) (\(setf\ eglot--major-mode\) managed-major-mode v)) (let* ((v server)) (\(setf\ eglot--inferior-process\) autostart-inferior-process v)) (run-hook-with-args (quote eglot-server-initialized-hook) server) (unwind-protect (condition-case _quit (let ((retval (catch tag (jsonrpc-async-request server :initialize ... :success-fn ... :timeout eglot-connect-timeout :error-fn ... :timeout-fn ...) (cond ... ...)))) (cond ((consp retval) (let* (...) (if ... ... server))) ((null retval) (eglot--message "Waiting in background for server `%s'" (jsonrpc-name server)) nil) (t server))) (quit (jsonrpc-shutdown server) (setq cancelled (quote quit)))) (setq tag nil)))
  eglot--connect(python-mode (vc . "~/hackery/python/lodgepole/") eglot-lsp-server ("pyls"))
  (if (and live-p interactive (y-or-n-p "[eglot] Live process found, reconnect instead? ")) (eglot-reconnect current-server interactive) (if live-p (progn (condition-case nil (progn (eglot-shutdown current-server)) (error nil)))) (eglot--connect managed-major-mode project class contact))
  (let* ((current-server (eglot-current-server)) (live-p (and current-server (jsonrpc-running-p current-server)))) (if (and live-p interactive (y-or-n-p "[eglot] Live process found, reconnect instead? ")) (eglot-reconnect current-server interactive) (if live-p (progn (condition-case nil (progn (eglot-shutdown current-server)) (error nil)))) (eglot--connect managed-major-mode project class contact)))
  eglot(python-mode (vc . "~/hackery/python/lodgepole/") eglot-lsp-server ("pyls") t)
  funcall-interactively(eglot python-mode (vc . "~/hackery/python/lodgepole/") eglot-lsp-server ("pyls") t)
  call-interactively(eglot record nil)
  command-execute(eglot record)
  counsel-M-x-action("eglot")
  ivy-call()
  ivy-read("M-x " [lispy-brackets-auto-wrap Post\ Handshake\ Auth ada-ref-man epg-context-signers -flatten-n 0 -is-infix\? message-required-headers magit-submodule-update avy-words epg--status-VALIDSIG tramp-find-user markdown-xhtml-body-preamble markdown-match-bold eglot--dbind mml-secure-smime-sign-with-sender :filterText tramp-do-copy-or-rename-file-out-of-band want vc-src-log-switches _message mixal dired-at-point local-only cl-print--preprocess -deferred-actions \(setf\ eglot--project-nickname\) mml-pgp-sign-buffer -some\? vc-git-conflicted-files 0 0 cl--struct-epg-signature-p being odb-editor-suite 0 message-kill-actions time-format eshell-output-filter vc-bzr-shelve 0 lispy-braces-barf-to-point-or-jump-nostring :contents rx-trans-forms eglot-autoshutdown magit-diff-wash-hunk not-at-beginning-of-line log-edit-set-header expired message-send-mail-function ...] :predicate #f(compiled-function (sym) #<bytecode 0x40e2c885>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
```

`GNU Emacs 26.3 (build 1, x86_64-apple-darwin19.5.0, Carbon Version 162 AppKit 1894.5) of 2020-07-15`

**Comment by caleb-allen** [comment] 2020-07-28 01:18
I'm encountering the same

`GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20) of 2020-05-19`

It looks like it's expecting a function `project-root` where the implementation is of `project-roots`

**Comment by notmgsk** [comment] 2020-07-28 01:20
It just occurred to me that it might be defined by a dependency. Turns out yes, https://github.com/jorgenschaefer/project-el

**Comment by joaotavora** [comment] 2020-07-28 08:30
> It just occurred to me that it might be defined by a dependency. 

Yes, it is defined by a dependency

> Turns out yes, https://github.com/jorgenschaefer/project-el

No that is not it, although it is similarly named.  The dependency is this one: http://elpa.gnu.org/packages/project.html

**Comment by joaotavora** [comment] 2020-07-28 08:34
This looks like a duplicate of #491.  Make sure you install Eglot using `M-x package-install` or `M-x list-packages`.  There are reports of successfull ways to install Eglot otherwise, but that is the only supported way.

**Closed by joaotavora** 2020-07-28 08:34 UTC
