### ISSUE TITLE
Typescript with jsx fails due to incorrect `:languageId`

### ISSUE THREAD

**Issue by mohkale** [joaotavora/eglot#624] opened 2021-02-18 23:27 UTC
The current implementation of `eglot--TextDocumentItem` doesn't work satisfactorily with jsx/tsx buffers.

https://github.com/joaotavora/eglot/blob/398b81eeec44b35b39480a38f1b1357bc8550a1c/eglot.el#L1685-L1695

Here languageId is set by stripping the mode suffix from the major-mode symbol which works reasonably well in most situations but not when there isn't a specific major mode for the kind of file your editing. I'm writing React files in typescript with `typescript-mode` (typescript files usually have a `ts` extension and typescript with React stuff has `tsx`). The `typescript-language-server` supports the following possible [languageIds](https://github.com/theia-ide/typescript-language-server/blob/3a8ea0f04bde047e2f60b9f68ef7816e3a41aa10/server/src/lsp-server.ts#L269-L277) but eglot only ever sends `js` or `typescript` (for `js-mode` and `typescript-mode`) which causes me to get some pretty glaring errors whenever I edit `tsx`.

[Here's](https://github.com/joaotavora/eglot/files/6006520/tslog.log) my log file.

`eglot` should probably introduce a user-option to configure the languageId or add a method `eglot--LanguageId` which users can advise to handle corner cases like this.

**Comment by joaotavora** [comment] 2021-02-21 00:43
Thanks for the report.  I think this should work out of the box, and ideally not need a user option.  Will look into this as soon as possible.

**Comment by joaotavora** [comment] 2021-02-24 10:49
Hello @mohkale .  I understand the problem now.  Is there any hint in your text file that the language you're using is `tsx`?  If there is, we could create a user-programmable endpoint to it.  But maybe that endpoint already exists?

```lisp
(define-derived-mode tsx-mode typescript-mode
  "typescript but better because such X")

(add-to-list 'auto-mode-alist '("\\.tsx\\'" . tsx-mode))
```

**Comment by joaotavora** [comment] 2021-02-24 11:23
In fact, those lines should probably live in `https://github.com/emacs-typescript/typescript.el`?  Pinging @josteink

**Comment by joaotavora** [comment] 2021-02-24 11:24
Closing, but feel free to comment if the workaround doesn't do what you want, or any other reason.

**Closed** 2021-02-24 11:23 UTC
Labels: workaround

**Comment by mohkale** [comment] 2021-02-24 12:06
Shouldn't it be `typescriptreact-mode` instead of simply `tsx-mode` just to match the languageId expected by `typescript-language-server`?

**Comment by joaotavora** [comment] 2021-02-24 12:09
I guess if the language server understands what the string `typescriptreact` is, then fine.  Check with your language server to know what it thinks "language Ids" are.  Then name your mode accordingly.  I think my JS language server understands both "js" and "javascript".

What I'm also saying is: we don't _need_ another indirection, much less an user option.

**Comment by josteink** [comment] 2021-02-25 09:30
> In fact, those lines should probably live in https://github.com/emacs-typescript/typescript.el?

I mean... Yes and no.

It's a known "issue" that none of the Emacs typescript-maintainers use react much, and thus don't have a need for better JSX/TSX-support. There's nobody there scratching that itch. And for that reason, this has been [a very long standing bug](https://github.com/emacs-typescript/typescript.el/issues/4), almost since the  very beginning.

I guess we *could* add such a line to our major-mode, if it makes something better for someone, but we would not really be able to maintain it, support it, or even claim it works.

If somebody really thinks adding these things to our mode will make their lives better, feel free to create a PR explaining in detail what your change does (in the wider context of the Emacs-verse), and how that enables things to work better for users, like for instance in combination with eglot.

For now though, this is not a change we're going to be adding our selves.

**Comment by joaotavora** [comment] 2021-02-25 10:48
> Explaining in detail what your change does

Heh, it's two lines and pretty self explanatory right?  But here goes: 'it puts files with the `.tsx` extension in `tsx-mode`, which is a derivation of `typescript-mode` which adds absolutely nothing'

**Comment by joaotavora** [comment] 2021-02-25 10:53
> which adds absolutely nothing

The derivation it is.  The addition of these two lines allows other systems to detect the language  better and also users to add tsx specific hooks and stuff.

I'm not proposing you _add_ any tsx stuff, just create a basic scaffold for others to do.  I'm not scratching my itch here either, but it seems kinda to add that.  Or maybe someone wants to add a 4 line `tsx-mode.el` package to MELPA, I dunno.  Just seems simpler to do that in your thing.

**Comment by josteink** [comment] 2021-02-25 11:30
>  But here goes: 'it puts files with the .tsx extension in tsx-mode, which is a derivation of typescript-mode which adds absolutely nothing'

But looking at the code from a typescript-mode side of things, knowing nothing about eglot, or this issue, or anything... It doesn't tell you why this was added, and how or why that is useful.

Which was why I specifically said "in detail".

Basically, as I said, none of the maintainers there are using TSX, so I would like for someone with an actual stake in the game to file the PR and explain what it is good for, maybe even with a link to a repo/config which that change can be tested upon, to make it even easier for us "dumb" non-react users to verify the need and the fix.

I don't think that's an unreasonable requirement.

**Comment by joaotavora** [comment] 2021-02-25 11:32
> why that is useful.

So programmers can add hooks to kick in .tsx files that don't kick in in .ts files.  I figured since you're a major mode maintainer this part would be obvious to you.

**Comment by josteink** [comment] 2021-02-25 11:35
But why would we need a new mode to kick in for that extension. Why would adding that extension to *regular* typescript-mode not be sufficient?

What does this derived mode add us?

Please take my word when I say I'm not trying to be difficult. I just trying to understand what actual need is being covered here.

**Comment by josteink** [comment] 2021-02-25 11:51
Looking at the issue in detail it says this:

> Here languageId is set by stripping the mode suffix from the major-mode symbol which works reasonably well in most situations but not when there isn't a specific major mode for the kind of file your editing. I'm writing React files in typescript with typescript-mode (typescript files usually have a ts extension and typescript with React stuff has tsx). The typescript-language-server supports the following possible languageIds but eglot only ever sends js or typescript (for js-mode and typescript-mode) which causes me to get some pretty glaring errors whenever I edit tsx.

So basically, eglot needs to be able to craft a languageId for thelanguage being used, but for some particular types of documents (JSX/TSX) the current implementation in eglot is too simplistic to correctly resolve the right language-id?

If so, I'm sorry, but to me that sounds like an eglot-internal implementation detail, and not a reason to create a new derived-mode which has no function outside eglot itself, in other major-modes.

Can't you just create a `eglot--get-language-id` function which special-cases the JSX/TSX variants instead? That really doesn't sound like a big job either?

**Comment by joaotavora** [comment] 2021-02-25 11:51
Look, let's say a user has function that frobs tsx thingies in the buffer, whatever they are, and highlights them in color of the rainbow. User adds that function to `tsx-mode-hook` and not `typescript-mode-hook`. Or users wants `M-x ibuffer` organization.  Or `font-lock-keywords`, or fancy Imenu expressions, or special Flymake configuration, etcetcetc.  Eglot is just another client of this longstanding generic way to associate buffers with major modes, but there are potentially many more clients that we might not even know of. 

> What does this derived mode add us?

To you, nothing apparently. And neither to me.  But presumably we open source our itch-scratching programs so that others can use them, and this seems to be useful for all the above reasons, which are just very common Emacsy things.

More derivation is just inheritance.  If a file contains source of a different language, it should use a different major mode. Is direct derivation the right thing here?  I dunno, but people seem to be using `typescript-mode` for `.tsx` files which suggests that `typescript-mode` feature don't break there, in other words that `.tsx` is a subset of `.ts`.  Again, I have no idea if this is true, it just seems to be the status quo.  

There, I've spilled all I know on this subject, I don't know if this is "detailed" enough.  But maybe @mohkale can just go make that `tsx-mode.el` package that depends on `typescript-mode.el` and we leave you alone :-)

**Comment by joaotavora** [comment] 2021-02-25 11:53
> eglot-internal implementation detail

Sure it's an implementation detail that relies on the major-mode API.  Eglot _does have_ an implementation, it is not vapourware :-)

**Comment by josteink** [comment] 2021-02-25 11:53
I mean... Adding a generic function to resolve the correct language ID can have uses outside JSX/TSX too.

There's a ton on JSON/YAML-based document-formats which has their own domain-specific grammar, and that might also be something you in the future would decide to add there?

**Comment by joaotavora** [comment] 2021-02-25 11:54
> Can't you just create a eglot--get-language-id function which special-cases the JSX/TSX variants instead? 

Why should the strings `jsx/tsx` even be in `eglot.el`, that's just reinventing major modes.

**Comment by josteink** [comment] 2021-02-25 11:55
Clearly the error in eglot is the assumption that a single major-mode can only map to a single document-type.

You wouldn't expect anyone to go create a major-mode (or derived ones?) specific for web.config (xml-mode), tsconfig.json (json-mode), or azure-pipelines.yaml (yaml-mode), right?

**Comment by joaotavora** [comment] 2021-02-25 11:55
> There's a ton on JSON/YAML-based document-formats which has their own domain-specific grammar, and that might also be something you in the future would decide to add there?

Then there should be major modes for them.  Major modes are the Emacs programming constructs for editing files of different types.  I think they've been here for around 40 years, let's not reinvent them with `get-language-id`

**Comment by joaotavora** [comment] 2021-02-25 12:00
> You wouldn't expect anyone to go create a major-mode (or derived ones?) specific for web.config (xml-mode), tsconfig.json (json-mode), or azure-pipelines.yaml (yaml-mode), right?

No idea what these creatures are, but they seem to pertain to the languages xml, json and yaml, respectively.  So no need.  But if they represent a subset of the language, then yes, a major mode, of course.  With `derived-major-mode`.

**Comment by josteink** [comment] 2021-02-25 12:01
I don't want to sound uncooperative, but I really don't see how this code belongs in `typescript-mode`, so I guess we have to agree to disagree.

I can ping the other maintainers/contributors and see what they think.

cc: @ananthakumaran @lddubeau @tam5

If that too leads nowhere, I guess someone who really wants to work around this eglot-bug feels like it, thet can do so by creating a new package on its own.

**Comment by joaotavora** [comment] 2021-02-25 12:01
no prob. Have fun!

**Comment by mohkale** [comment] 2021-02-25 14:15
I suppose I'd say I don't think major-modes map to languageIds very well... mostly because I don't really see the point of languageIds. Like 99% of the time I assume the server should be able to infer it and when it can't we can probably configure it to go with what we want. I'm assuming there's some LSP reason for it.

But the bigger issue from my POV is that each server seems to define its own set of what it sees as acceptable languageIds and I don't recall seeing some sort of recommeneded convention in that regards. The server I'm using has `typescript`, `typescriptreact`, `javascript` and `javascriptreact`. If we add a `typescriptreact-mode` derived mode (which honestly seems fine to me (apart from my OCD raging at the lack of a seperating hyphen `typescript-react` :rage:)) then that's all good to me but how do we avoid having to create a `TypescriptReact-mode` or `Typescript-React-mode` or `Typescript-TSX-mode` when a new server pops along and decides it wants a different list/form of languageIds arbitrarily.

I do agree emacs needs a `typescript-react-mode` and deriving it from `typescript-mode` seems fine for now. Just thought I'd give my two sense on the matter.

**Comment by joaotavora** [comment] 2021-02-25 14:39
> ff we add a typescriptreact-mode derived mode (which honestly seems fine to me (apart from my OCD raging at the lack of a seperating hyphen typescript-react rage))

Exactly, and to fix your OCD rage (which I fully sympathize with) eventually, we can have some sort of indirection, whereby you set a property on the major-mode symbol that is some kind of LSP-approved nickname.  If it doesn't find anything it falls back to the sniffing strategy.  But that's quite different to reinventing `auto-mode-alist` and extensions in Eglot, which would just be ridiculously silly.  Major modes are the thing that Emacs uses to associate source code files with languages, and that's the way it should be.

**Comment by joaotavora** [comment] 2021-03-26 10:11
> Exactly, and to fix your OCD rage (which I fully sympathize with) eventually, we can have some sort of indirection, whereby you set a property on the major-mode symbol that is some kind of LSP-approved nickname. If it doesn't find anything it falls back to the sniffing strategy.

I just implemented this in the fix to #525 .  In fact that fix had been lying there for quite some time.  If I had remembered this it would have saved some discussion here, maybe.

**Comment by joaotavora** [comment] 2021-03-26 10:12
Actually, (I didn't implement it, https://github.com/joaotavora/eglot/commits?author=rvs314 did).

**Comment by mohkale** [comment] 2021-03-26 13:23
@joaotavora 

oh, nice, thanks for sharing.

**Comment by danielpza** [comment] 2021-04-13 22:12
I'm having a hard time finding a solution in this thread and the following snippet didn't do it for me:

```elisp
(define-derived-mode tsx-mode typescript-mode
  "typescript but better because such X")

(add-to-list 'auto-mode-alist '("\\.tsx\\'" . tsx-mode))
```

Is there anything else to make it work with typescript and react? Sorry if the answer it's clear am still learning my elisp

**Comment by terlar** [comment] 2021-04-13 22:24
It depends on what language server you use and what it expects.

If you are using the same as @mohkale it would be the following:

> The server I'm using has typescript, typescriptreact, javascript and javascriptreact.

So either use the defined derived mode or use the new feature `eglot-language-id` by @rvs314 that was linked, which can map major modes to the strings expected by the language servers. The commit includes a description on how to use it, but to reiterate:
```
(put 'favourite-major-mode 'eglot-language-id "foobarbaz")
```

So all you have to figure out is what is your major mode called and what does the Language server accept and then map those accordingly.

**Comment by joaotavora** [comment] 2021-04-13 22:29
@danielpza , it's like @terlar says.  Eglot is for LSP so it's a game between two programs: Emacs and the LSP server.  You have to find out what server you are trying to use.  Just running that snippet,  by itself only accomplishes the following, the `languageId` sent to the server will be the string `"tsx"` instead of the string `"typescript"`.   It that the right string for configuring the server for React?  I don't know.  

Another method is to use:

```lisp
(put `typescript-mode-or-whatever-mode-you-use-for-react-files 'eglot-language-id "language-id-string-that-the-lsp-server-expects")
```

**Comment by danielpza** [comment] 2021-04-13 22:30
I think I'm using the same language server, it's the typescript-javascript one https://github.com/theia-ide/typescript-language-server

```elisp
(use-package typescript-mode
  :straight t
  :demand
  :mode "\\.ts\\'"
  :config
  ;; https://github.com/joaotavora/eglot/issues/624
  ;; https://github.com/mohkale/emacs/blob/master/init.org#typescript
  (define-derived-mode typescript-react-mode typescript-mode
    "Typescript JSX")

  (add-to-list 'auto-mode-alist '("\\.tsx\\'" . typescript-react-mode)))

(use-package eglot
  :straight t
  :demand
  :hook ((js-mode typescript-mode typescript-react-mode) . eglot-ensure)
  :custom
  (eglot-confirm-server-initiated-edits . nil)
  :config
  (put 'typescript-react-mode 'eglot-language-id "typescriptreact")
  (add-to-list 'eglot-server-programs `(typescript-react-mode . ("typescript-language-server" "--stdio"))))
```

When I visit a .tsx file a error is shown `File mode specification error: (error No language registered for major mode ‘typescript-react-mode’)`. Eglot seems to be working and further executing `eglot` doesn't throw any error. Reverting/reloading the buffer howvers shows the same error again.

**Comment by joaotavora** [comment] 2021-04-13 22:31
By the way, I've tried to convince the `typescript-mode` maintainer to put a snippet to the same effect in `typescript-mode`, so users wouldn't be so confused, but I was unsuccessful.  The snippet doesn't belong in Eglot, because Eglot is language-agnostic (not 100%, but very close).

**Comment by joaotavora** [comment] 2021-04-13 22:33
@danielpza either make a new bug (and clearly and closely follow the instructions there) or start a discussion.

**Comment by danielpza** [comment] 2021-04-13 23:05
After further investigations the error/message might have been caused by another package and it's not related to eglot. Thanks for the help.

**Comment by purcell** [comment] 2021-04-30 02:05
Now that #678 has been merged, perhaps there are more `:language-id` settings that should be added to the default value of `eglot-server-programs` in the light of this issue?

**Comment by Lyonsclay** [comment] 2022-09-08 02:52
I know this thread is quite old and my suggestion doesn't necessarily solve the stated problem, but I have found a way to view `.tsx` files with eglot. I use web-mode and then manually run eglot which then asks for the path to server or host:port. I type in `typescript-language-server --stdio` and everything seems to work quite nicely.  [TODO] I need to figure out a way to automatically set this for all `.tsx` file.

**Comment by mangkoran** [comment] 2022-10-01 09:47
Recently switching from `lsp-mode` to `eglot`, and tried @Lyonsclay solution (or workaround?) and confirm it works flawlessly!

**Comment by pbgc** [comment] 2022-12-30 12:15
In my opinion the best solution for this problem (maybe it helps someone) is:

`(define-derived-mode pbgc-tsx-mode web-mode "pbTSX"
  "A major mode derived from web-mode, for editing .tsx files with LSP support.")

(add-to-list 'auto-mode-alist '("\\.tsx\\'" . pbgc-tsx-mode))

(defun pbgc-tsx-custom ()
  (company-mode)
  (eglot-ensure))
(add-hook 'pbgc-tsx-mode-hook 'pbgc-tsx-custom)

(add-to-list 'eglot-server-programs '(pbgc-tsx-mode . ("typescript-language-server" "--stdio")))`

**Comment by ramnes** [comment] 2023-01-31 14:23
Another quick variation of what's above, that plays nicely with other modes by not overriding `eglot-server-programs`:

```elisp
(add-to-list 'auto-mode-alist '("\\.tsx?\\'" . web-mode))
(add-to-list 'eglot-server-programs '(web-mode . ("typescript-language-server" "--stdio")))
(add-hook 'web-mode-hook 'eglot-ensure)
```

**Comment by pbgc** [comment] 2023-01-31 14:47
> Another quick variation of what's above, that plays nicely with other modes 

With your variation .. typescript-language-server is always used with web-mode .. and I don't want that! I use several other Language Servers with web-mode for editing other type of files and I just want to use typescript-language-server for .tsx files ...
> by not overriding `eglot-server-programs`
I'm not overriding eglot-server-programs .. I'm just adding a new definition for a derived mode created with  define-derived-mode in the same way you are doing it for web-mode ...

**Comment by ramnes** [comment] 2023-01-31 14:51
I wasn't referring to your suggestion when I said "what's above". :)

**Comment by danking** [comment] 2024-07-15 20:58
I'm not using web-mode and, although all the pieces are present in this thread (thank you mokhale, terlar, joaotavora, and danielpza), there was no single copy-pasteable-into-dot-emacs chunk that Just Works. Here's what I use. I don't really know how to create Emacs packages, unfortunately, otherwise this indeed would be a good four-line package.

```elisp
;; TypeScript with react components is an extension to TypeScript and therefore
;; needs a different major mode and associated langauge ID. Eglot, by default,
;; removes "-mode" from the major mode name to discover the langauge ID. For
;; typescript-mode, this produces "typescript" which is incorrect. In
;; particular, the typescript-language-server expects the language ID
;; "typescriptreact".
;;
;; We use the eglot-language-id property to overide the default language ID
;; deduction behavior. See the full list of supported language IDs for
;; typescript-language-server here:
;; https://github.com/typescript-language-server/typescript-language-server/blob/master/docs/configuration.md
(define-derived-mode tsx-mode typescript-mode
  "TypeScript[TSX]")
(put 'typescript-mode 'eglot-language-id "typescriptreact")

(add-to-list 'auto-mode-alist '("\\.tsx\\'" . tsx-mode))
```

Ensure you have `typescript-mode` installed in Emacs and ensure you've installed the typescript-langauage-server too:
```sh
npm install -g typescript-language-server typescript
```
