### ISSUE TITLE
Doing `c-fill-paragraph` in comments causes eglot to parse comments as code and produce errors

### ISSUE THREAD

**Issue by finalpatch** [joaotavora/eglot#367] opened 2019-12-07 11:13 UTC
Steps to reproduce:

1. Open a well formatted C++ file, where eglot shows no errors and warnings.
2. Add 2 lines of comments, for example
   ```
   // comment1
   // comment2
   class MyClass {
   ...
   more code
   ...
   ```
3. Put cursor in the comments, and press `M-q` (c-fill-paragraph)
4. Observe flymake now shows some errors even though there is no change in actual code
5. Keep pressing `M-q` and we can observe the error lines move down

It feels as if eglot didn't realize the input command happens in comment and doesn't affect code at all.  Instead, eglot seems to send comments as code for incremental parsing and generated errors.

The errors can be fixed by reverting the buffer.

**Comment by joaotavora** [comment] 2019-12-08 00:32
Hmmm.  I'd venture to say this is a bug in C mode. You see, the way eglot "catches" changed text is by relying on before- and after- modification hooks, and `cc-mode` sometime has some special behaviour. 

Can you try a similar thing in `js-mode`? (I mean, I know you don't want `js-mode`, but you could make Eglot run the same C langserver in `js-mode` and try out the same paragraph-filling thing).  If the bug happens, it's probably Eglot's bug, if it doesn't, it's probably `cc-mode`'s fault

Anyway, I'll try to have a look, but it might take a while.

**Comment by finalpatch** [comment] 2019-12-08 02:41
I tried to get eglot to run ccls in js-mode but it didn't work.  I'm happy to try again if you could tell me the steps to follow.

I tested c-fill-paragraph in comments with lsp-mode and it doesn't show this bug.  I don't know whether it has some workaround for this special case or it just does things differently.

**Comment by finalpatch** [comment] 2019-12-08 02:46
Also, the funny thing is, `c-fill-paragraph` doesn't have to actually change the text to trigger the bug.  Pressing M-q on an already filled paragraph results in no text change at all but will still cause the errors to appear.

**Comment by joaotavora** [comment] 2019-12-08 09:28
> I tried to get eglot to run ccls in js-mode but it didn't work. I'm happy to try again if you could tell me the steps to follow.

It should be as simple as `C-u M-x eglot RET ccls RET` in a `.cpp` that you happened to put in `js-mode` before by typing `M-x js-mode`.

But never mind... I just saw `js-fill-paragraph` uses `c-fill-paragraph`, too.  So this experiment would tell us nothing.

**Comment by joaotavora** [comment] 2019-12-08 09:32
You know what I'd do? Just set `fill-paragraph-function` to `nil` in `c++-mode-hook` or something.  It stills fills basic paragraphs (like the one you showed me), though it'll probably fail on fancy `\*` comments.

But it that works with `ccls` at least we can know that the problem in is `c-fill-paragraph`, or rather that it is closer to `c-fill-paragraph`.

**Comment by finalpatch** [comment] 2019-12-10 09:59
Hi @joaotavora , I just tested setting fill-paragraph-function to nil in a c++ buffer and I'm still seeing this bug

**Comment by joaotavora** [comment] 2019-12-10 10:00
That's good! Probably means the bug is in Eglot, or Emacs. I'll have a
look later on.

On Tue, Dec 10, 2019 at 10:59 AM finalpatch <notifications@github.com> wrote:
>
> Hi @joaotavora , I just tested setting fill-paragraph-function to nil in a c++ buffer and I'm still seeing this bug
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
João Távora

**Comment by casouri** [comment] 2019-12-11 12:47
I want to add that this bug also occurs occasionally when third party functions modifies the buffer, but I cannot reliably reproduce it.

**Comment by casouri** [comment] 2020-03-03 19:04
Any news?

**Comment by joaotavora** [comment] 2020-03-03 19:13
> Any news?

No sorry, nothing.  You can help by coming up with a reliable reproduction recipe.  Try to spot when it happens, and then isolate the case.

**Comment by casouri** [comment] 2020-03-03 19:31
I thought we already have a reliable way to reproduce (fill-paragraph)?

**Comment by joaotavora** [comment] 2020-03-03 19:33
> I thought we already have a reliable way to reproduce (fill-paragraph)?

That is correct, Indeed I misread this thread and focused on your own comment.  Then if you can reliably reproduce "your bug", it would be of help.

**Comment by casouri** [comment] 2020-03-18 04:10
I had a look at `c-fiil-paragraph` and found that it messes with `after-change-function`. To be exact, it calls `c-mask-paragraph` which uses `c-save-buffer-state` which uses `with-silent-modifications`. Then I went to yasnippet and found inhibit-modification-hooks setting to nil deep in a function called by `yas--move-to-field`.

I'm not an expert but I think that's why eglot breaks when I fill paragraph and use signature expansion for functions in C.

**Comment by joaotavora** [comment] 2020-03-18 09:49
> I had a look at c-fiil-paragraph and found that it messes with after-change-function. To be exact, it calls c-mask-paragraph which uses c-save-buffer-state which uses with-silent-modifications. Then I went to yasnippet and found inhibit-modification-hooks setting to nil deep in a function called by yas--move-to-field.

Thanks for this analysis, it is very promising, but I don't understand some of your sentences, you need to write a bit more.

What is the relation with Yasnippet here? Are you saying yasnippet already has a fix for this similar problem?  If so, that would be great and wouldn't suprise me, as I (but mostly @npostavs) dealed with a lot of c-mode problems in Yasnippet.

**Comment by casouri** [comment] 2020-03-18 12:41
I have the problem when 1) I use `c-fill-paragraph` and 2) I use function signature expansion (if I'm not mistaken it is handled by yasnippet). After I found `c-fill-paragraph` using `with-silent-modifications` I thought I'd see if yanippet does similar stuff and it does. That more or less backs my theory that these functions messing with after-change-functions being the culprit.

**Comment by joaotavora** [comment] 2020-03-18 12:43
Ahh, so you see a similar problem in two distinct situations?  And both of them point to a use of `with-silent-modifications`.  Can you confirm this?

**Comment by casouri** [comment] 2020-03-18 12:46
Let me have a try :-)

**Comment by Miciah** [comment] 2020-08-25 00:29
I see a similar problem with go-mode.  The following steps can be used to reproduce the problem:

1. Create a file with the name `/tmp/go-mode/main.go` and the following content:
```go
package main

import (
	"fmt"
)

// main prints,
// "Hello, world!"
func main() {
	fmt.Println("Hello, world!")
}
```
2. Start Emacs with the go-mode and eglot packages loaded and the `/tmp/go-test/main.go` file open: `emacs -Q -l ~/.cache/emacs/elpa/go-mode-20200822.1936/go-mode.el -l ~/.cache/emacs/elpa/eglot-20200821.2227/eglot.el /tmp/go-test/main.go`
3. Start eglot: <kbd>M-x</kbd> `eglot` <kbd>RET</kbd>.
4. Move to the comment and press <kbd>M-q</kbd>.

Eglot marks the line after the comment (`func main() {`) with two red exclamation marks in the fringe and a red squiggle running under the line.  Flymake reports an error: `syntax: expected declaration, found "Hello, world!"`.

The value of `fill-paragraph-function` is `go--fill-paragraph`, which is defined in the go-mode package as follows:
```emacs-lisp
(defun go--fill-paragraph (&rest args)
  "Wrap fill-paragraph to set custom fill-prefix."
  (let ((fill-prefix (go--fill-prefix))
        (fill-paragraph-function nil))
    (apply 'fill-paragraph args)))
```

**Comment by stephe-ada-guru** [comment] 2020-08-25 17:12
I had the same problem with the ada-mode parser; the problem is that an
intermediate step in fill-paragraph leaves the comment lines with no
comment-start syntax; then the parser gets triggered by change hooks and
reports that error.

This is actually a bug in fill-comment; it might be better to fix it.

I worked around this in ada-mode by writing my own
ada-fill-comment-paragraph, and inhibiting parsing until it was done;
there is a flag wisi-inhibit-parse for this purpose (also used in a
couple other places, notably inserting skeletons).

Does eglot have a similar inhibit?

-- 
-- Stephe

**Comment by joaotavora** [comment] 2020-08-25 18:18
Thanks Miciah and Stephen.  Stephen, your insight might be the clue to fix
this. I'll have a better read later on.

**Comment by bcmills** [comment] 2020-10-08 20:06
> the problem is that an intermediate step in fill-paragraph leaves the comment lines with no comment-start syntax; then the parser gets triggered by change hooks and reports that error.

For me these errors are sticky. Shouldn't the change hook fire again after `fill-comment` completes if the contents have changed relative to the last invocation? (That is, shouldn't any errors from the intermediate state be ephemeral and very short-lived?)

**Comment by bcmills** [comment] 2020-10-08 20:18
`fill-paragraph` does not appear to use `with-silent-modifications`, but it does use `set-buffer-modified-p` to set the buffer back to unmodified after making the edit:
https://github.com/emacs-mirror/emacs/blob/d0e2a341dd9a9a365fd311748df024ecb25b70ec/lisp/textmodes/fill.el#L896-L901

**Comment by muffinmad** [comment] 2020-10-08 21:02
**Offtopic** I have a dream: all LSP servers stops publishing diagnostic on every document change.

Sorry for the noise :)

**Comment by andschwa** [comment] 2020-12-13 03:15
I can confirm that the OP's repro steps work, but also with just about any Python file instead of a C++ file. `python-mode` sets `fill-paragraph-function` (used by `fill-paragraph`) to `python-fill-paragraph`.

Emacs "27.1.50"

```elisp
;; Version: 1.6
;; Package-Version: 20201103.1026
;; Package-Commit: 21726416e6e580b20dfa90833c6dab2a8a15ea48
```

**Comment by andschwa** [comment] 2020-12-13 04:07
Ok, I have a repro of something _related_ to this, but worse. I want to note that I have also seen the effect of a ghost flymake error being introduced on the use of `fill-paragraph` in Python mode. But this next thing is bonkers:

Start with buffer contents, and cursor at that first docstring, which is too long and needs to be filled, say before the 'T' in 'The':

```python
class Foo:
    """The `SSH` platform simply connects to existing targets. The `SSH` platform simply connects to existing targets. The `SSH` platform simply connects to existing targets.

    It does not deploy nor delete the target. The default ``host`` is
    ``localhost`` so this can be used for testing against the user's
    system (if SSH is enabled).

    """

    def foo(self) -> str:
        return "foo"

```
Run `eglot-format-buffer` just and assert that nothing changes.

Run `fill-paragraph` (or `python-fill-paragraph`, which calls the former), and either do or do nor save the buffer (it repros both ways, I know because I found this since due adding `eglot-format-buffer` to `before-save-hook`, and then `after-save-hook`, and then took saving out of the equation). Get:

```
class Foo:
    """The `SSH` platform simply connects to existing targets. The `SSH`
platform simply connects to existing targets. The `SSH` platform
simply connects to existing targets.

    It does not deploy nor delete the target. The default ``host`` is
    ``localhost`` so this can be used for testing against the user's
    system (if SSH is enabled).

    """

    def foo(self) -> str:
        return "foo"

```

(Cool, it's filled, it's just wrong for a Python docstring since it should be indented.) Now run `eglot-format-buffer`:

```python
class Foo:
    """The `SSH` platform simply connects to existing targets. The `SSH`
    platform simply connects to existing targets. The `SSH` platform
    simply connects to existing targets.

        It does not deploy nor delete the target. The default ``host`` is
        ``localhost`` so this can be used for testing against the user's
        system (if SSH is enabled).

    """

    def foo(self) -> str:
        return "foo"
```

It applied the indents to the paragraph below too! And this isn't the thing I've seen. I was first trying to repo the `fill-paragraph` which causes the ghost flymake error, which I have seen, then I was trying to repro where the last N lines get duplicated (I saw it as I was making this repro, and then undid and didn't see it again, WTF, wasn't able to repro again):

```python
    def foo(self) -> str:
        return "foo"
        return "foo"
```

I futzed around with a different example, and got that to repro, but then as I undid and tried to copy the pieces out, it stopped repro'ing again.

So something is up with `eglot-format-buffer` and `fill-paragraph`, and something else is up with `fill-paragraph` alone.

**Comment by notmgsk** [comment] 2020-12-14 12:32
This is hella annoying. The most frustrating thing about it is that the "error" persists, and, at least in `go-mode`, it means that the rest of the buffer is no longer type-checked, etc. Essentially it renders eglot/LSP useless until I issue `eglot-reconnect`. Is there a work-around? don't use `fill-paragraph`?

**Comment by joaotavora** [comment] 2020-12-14 12:34
@notmgsk Understood, I guess I have to put some hours into this. I think we have sufficient repros here.  I'll just quickly try out hailing @monnier in case he has some world-shattering insight into fill-paragraph's purported mischiefs.

**Comment by notmgsk** [comment] 2020-12-14 12:38
Do let me know if there's anything I can add here to help, logs etc. I'm not sure how to locate all that stuff, so some instruction would be helpful :)

**Comment by joaotavora** [comment] 2020-12-14 13:15
OK, I installed a bunch of Go stuff and I can reproduce the problem described here https://github.com/joaotavora/eglot/issues/367#issuecomment-679433398

I turned on most other LSP comms and when doing M-q on the comment got this stupid didChange event from Eglot -> server:

Also, I have `fill-paragraph-function` set to `nil`, so it seems to be a problem in `fill-paragraph` itself (as many already suspected).

```lisp
[client-notification] Mon Dec 14 13:11:10 2020:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
          (:textDocument
           (:uri "file:///home/capitaomorte/tmp/coiso.go" :version 4)
           :contentChanges
           [(:range
             (:start
              (:line 7 :character 0)
              :end
              (:line 7 :character 3))
             :rangeLength 3 :text "")
            (:range
             (:start
              (:line 6 :character 15)
              :end
              (:line 6 :character 16))
             :rangeLength 1 :text " ")]))
[server-notification] Mon Dec 14 13:11:10 2020:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:uri "file:///home/capitaomorte/tmp/coiso.go" :version 4 :diagnostics
                [(:range
                  (:start
                   (:line 7 :character 0)
                   :end
                   (:line 7 :character 0))
                  :severity 1 :source "syntax" :message "expected declaration, found \"Hello, world!\"")]))
```

Note that the buffer went from 
```go
package main

import (
	"fmt"
)

// main prints,
// "Hello, world!"
func main() {
	fmt.Println("Hello, world!")
}
```

to 

```
package main

import (
	"fmt"
)

// main prints, "Hello, world!"
func main() {
	fmt.Println("Hello, world!")
}
```

Also note that LSP's line-numbering is 0 based, so its line 7 is Emacs's 8

**Comment by joaotavora** [comment] 2020-12-14 13:16
@notmgsk, to help, you can read the source and debug this :-D

**Comment by monnier** [comment] 2020-12-14 14:08
> I'll just quickly try out hailing @monnier in case he has some
> world-shattering insight into fill-paragraph's purported mischiefs.

I think I left my world shatterer in the office, so it'll have to wait
for after-Covid, sorry.  The session you posted seems to indicate that
what you're seeing is similar to what Stephen saw with ada-mode,
i.e. the LSP server ends up analyzing the code in its intermediate state.

I can't guess why it starts at that particular moment.  It's actually
rather odd: the `:contentChange` indicates Eglot doesn't send the
notification right after the first modification, instead it's delayed
until after the second.  The delay is a good thing but why is it not
delayed yet further until the end of the whole command?  Is it because
the next modification touches text affected by earlier modifications, so
Eglot would otherwise have to go through the trouble of combining the
modifications before sending them to the server?

I also can't guess why Eglot doesn't send another `:contentChange`
afterwards (or maybe it does and you just didn't send that part of the
trace?).

**Comment by joaotavora** [comment] 2020-12-14 15:10
> I also can't guess why Eglot doesn't send another `:contentChange`
afterwards (or maybe it does and you just didn't send that part of the
trace?).

Nope, that's all she wrote, which would indicate no more before/after
change hooks calls after that.

**Comment by joaotavora** [comment] 2020-12-14 15:48
For the record, here's what that LSIP `didChange` dialog _could_ look like.  This is what Emacs does if I fill the paragraph manually.
```lisp
[client-notification] Mon Dec 14 15:46:48 2020:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
          (:textDocument
           (:uri "file:///home/capitaomorte/tmp/coiso.go" :version 15)
           :contentChanges
           [(:range
             (:start
              (:line 3 :character 0)
              :end
              (:line 3 :character 3))
             :rangeLength 3 :text "")
            (:range
             (:start
              (:line 2 :character 15)
              :end
              (:line 3 :character 0))
             :rangeLength 1 :text "")
            (:range
             (:start
              (:line 2 :character 15)
              :end
              (:line 2 :character 15))
             :rangeLength 0 :text " ")]))
```

**Comment by monnier** [comment] 2020-12-14 15:49
> Nope, that's all she wrote, which would indicate no more before/after
> change hooks calls after that.

Somehow I find it hard to believe.  Please double check that it's really
the case.


        Stefan

**Comment by joaotavora** [comment] 2020-12-14 15:52
> Somehow I find it hard to believe.  Please double check that it's really
the case.

Quadruple checked.  See the examples above for a shorter `.go` file.  This is the trace of some the before/after members after filling the paragaph:

```
======================================================================
1 -> (fill-paragraph nil t)
| 2 -> (fill-comment-paragraph nil)
| | 3 -> (eglot--before-change 31 34)
| | 3 <- eglot--before-change: nil
| | 3 -> (eglot--after-change 31 31 3)
| | 3 <- eglot--after-change: nil
| | 3 -> (eglot--before-change 30 46)
| | 3 <- eglot--before-change: nil
| | 3 -> (eglot--after-change 30 31 1)
| | 3 <- eglot--after-change: nil
| 2 <- fill-comment-paragraph: "// "
1 <- fill-paragraph: "// "
```

**Comment by joaotavora** [comment] 2020-12-14 15:54
Again this is for bringing a buffer from:
```go
package main

// main prints,
// "Hello, world!"
func main() {
}
```

to 

```go
package main

// main prints, "Hello, world!"
func main() {
}
```

**Comment by joaotavora** [comment] 2020-12-14 16:22
May have found the bug, when I comment the fix for #259, I can't reproduce anymore:
```diff
diff --git a/eglot.el b/eglot.el
index b0bd213..4a3f46f 100644
--- a/eglot.el
+++ b/eglot.el
@@ -1747,10 +1747,10 @@ Records BEG, END and PRE-CHANGE-LENGTH locally."
      ;; `beg' and `end'.  Not only is this longer than needed but
      ;; conflicts with the args received here.  Detect this using
      ;; markers recorded earlier and `pre-change-len', then fix it.
-     (when (and (= b-end b-end-marker) (= b-beg b-beg-marker)
-                (not (zerop pre-change-length)))
-       (setq lsp-end (eglot--pos-to-lsp-position end)
-             lsp-beg (eglot--pos-to-lsp-position beg)))
+     ;; (when (and (= b-end b-end-marker) (= b-beg b-beg-marker)
+     ;;            (not (zerop pre-change-length)))
+     ;;   (setq lsp-end (eglot--pos-to-lsp-position end)
+     ;;         lsp-beg (eglot--pos-to-lsp-position beg)))
      (setcar eglot--recent-changes
              `(,lsp-beg ,lsp-end ,pre-change-length
                         ,(buffer-substring-no-properties beg end))))
```

**Comment by monnier** [comment] 2020-12-14 16:52
>> Somehow I find it hard to believe.  Please double check that it's really
>> the case.
> Quadruple checked.

I was confused: there are only two modifications taking place during the
command (the first one removes the "//" on the second line (it actually
removes the "//" on all the lines except the first), and the second one
replaces the \n with a \s), so it's all delayed properly and there's no
before/after hook call missing.

**Comment by joaotavora** [comment] 2020-12-14 16:55
> I was confused: there are only two modifications taking place during the
> command (the first one removes the "//" on the second line (it actually
> removes the "//" on all the lines except the first), and the second one
> replaces the \n with a \s), so it's all delayed properly and there's no
> before/after hook call missing.

Yes, I came to that conclusion too.  This is likely related to a bad fix for #259.

That's where the likely Emacs bug lies.  I worked around in Eglot, but I the 
workaround is too greedy.  Working on a fix.

**Comment by joaotavora** [comment] 2020-12-14 17:10
Would everyone affected by this bug try the commit above and report back results?

**Comment by notmgsk** [comment] 2020-12-14 18:31
@joaotavora Appears to be fixed on my end :) thanks

**Comment by bcmills** [comment] 2020-12-14 18:53
That appears to fix it for me too.

**Comment by joaotavora** [comment] 2020-12-14 18:54
Alright, 3's the magic number, pushing... 

https://www.youtube.com/watch?v=aU4pyiB-kq0

**Comment by bcmills** [comment] 2020-12-14 18:55
But I will confess that I don't really understand how or why the fix works. Won't it just mask an analogous bug for intra-line edits? (I don't really follow how the fix for #259 was supposed to work to begin with...)

**Comment by andschwa** [comment] 2020-12-14 18:55
Wait!

**Comment by andschwa** [comment] 2020-12-14 18:55
This commit introduces a new bug for me, with `eglot-format-buffer` on some of the code shared above, I get a traceback:

```
[eglot] applying 0 edits to `foo.py'...done
jsonrpc-error: "request id=13 failed:", (jsonrpc-error-code . -32602), (jsonrpc-error-message . "blib2to3.pgen2.tokenize.TokenError: ('EOF in multi-line string', (2, 4))"), (jsonrpc-error-data :traceback ["  File \"/home/andschwa/.cache/pypoetry/virtualenvs/lisa-smHTVCg6-py3.8/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py\", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
" "  File \"/home/andschwa/.cache/pypoetry/virtualenvs/lisa-smHTVCg6-py3.8/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py\", line 182, in _handle_request
    handler_result = handler(params)
" "  File \"/home/andschwa/.cache/pypoetry/virtualenvs/lisa-smHTVCg6-py3.8/lib/python3.8/site-packages/pyls_jsonrpc/dispatchers.py\", line 23, in handler
    return method(**(params or {}))
" "  File \"/home/andschwa/.cache/pypoetry/virtualenvs/lisa-smHTVCg6-py3.8/lib/python3.8/site-packages/pyls/python_ls.py\", line 338, in m_text_document__formatting
    return self.format_document(textDocument['uri'])
" "  File \"/home/andschwa/.cache/pypoetry/virtualenvs/lisa-smHTVCg6-py3.8/lib/python3.8/site-packages/pyls/python_ls.py\", line 256, in format_document
    return self._hook('pyls_format_document', doc_uri)
" "  File \"/home/andschwa/.cache/pypoetry/virtualenvs/lisa-smHTVCg6-py3.8/lib/python3.8/site-packages/pyls/python_ls.py\", line 156, in _hook
    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
" "  File \"/home/andschwa/.cache/pypoetry/virtualenvs/lisa-smHTVCg6-py3.8/lib/python3.8/site-packages/pluggy/hooks.py\", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
" "  File \"/home/andschwa/.cache/pypoetry/virtualenvs/lisa-smHTVCg6-py3.8/lib/python3.8/site-packages/pluggy/manager.py\", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
" "  File \"/home/andschwa/.cache/pypoetry/virtualenvs/lisa-smHTVCg6-py3.8/lib/python3.8/site-packages/pluggy/manager.py\", line 337, in traced_hookexec
    return outcome.get_result()
" "  File \"/home/andschwa/.cache/pypoetry/virtualenvs/lisa-smHTVCg6-py3.8/lib/python3.8/site-packages/pluggy/callers.py\", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
" ...])
```

**Comment by joaotavora** [comment] 2020-12-14 18:55
auwight, waiting

**Comment by andschwa** [comment] 2020-12-14 18:57
I have no idea why, but all I know is on `master`, I can format fine, and with this commit, I get that jsonrpc error `('EOF in multi-line string', (2, 4))` which is strange? The buffer is the same, the whole multi-line string is there, there's no EOF in it, so I feel like the start of the string and not the entirety of it is being sent.

**Comment by joaotavora** [comment] 2020-12-14 18:57
@andschwa , I tried to run your thing, and I did it with the `pyls` server, since you don't point to a precise one.  What server are you using?  Can you post a fool-proof reproduction recipe from Emacs -Q?

**Comment by andschwa** [comment] 2020-12-14 18:58
Oh yeah, I'm using:  "python-language-server" version = "0.35.1"

**Comment by joaotavora** [comment] 2020-12-14 18:59
> But I will confess that I don't really understand how or why the fix works. Won't it just mask an analogous bug for intra-line edits? (I don't really follow how the fix for #259 was supposed to work to begin with...)

I don't know how familar you are with the code, so if you have a precise question. go for it.  But as you stated it the answer is no, no it wont.  To the best of my understanding.

**Comment by joaotavora** [comment] 2020-12-14 18:59
Right @andschwa , now can you put all of that together in a way that my dog can follow those instructions (if I had a dog, of course)?

**Comment by andschwa** [comment] 2020-12-14 18:59
> What server are you using? Can you post a fool-proof reproduction recipe from Emacs -Q?

I'm gonna try!

**Comment by joaotavora** [comment] 2020-12-14 19:02
Anyway, from that traceback, it seems like your python language server is confused. Almost as much as I am.

**Comment by andschwa** [comment] 2020-12-14 19:10
Ok, I've isolated a minimal Python project and env that repros this, now isolating a bare init to setup eglot.

**Comment by joaotavora** [comment] 2020-12-14 19:11
Don't forget to include the simplest instructions you can on how to download your python ls.

**Comment by andschwa** [comment] 2020-12-14 19:24
Wah, trying to get an emacs -Q to load eglot is...not going well...getting `(void-function project-root)` even though I put `(require 'project)` into the simple init.el file.

**Comment by joaotavora** [comment] 2020-12-14 19:25
Look in the Makefile.  You need packages if you're not using the latest nightly or something equivalent.

**Comment by andschwa** [comment] 2020-12-14 19:26
Oh shoot, yeah that makes sense. Thanks! Forgot that just how much gets wiped by `-Q` 😅

**Comment by joaotavora** [comment] 2020-12-14 19:26
Though you should have those packages. Then again, if you're completely sandboxing this init, you need to reinstall them.  

-Q doesn't wipe packages, as far as I know.  But you have to `package-initialize` or something like that.

**Comment by andschwa** [comment] 2020-12-14 19:43
Hope this helps: https://github.com/andschwa/eglot-repro

**Comment by andschwa** [comment] 2020-12-14 19:44
I can repro all the things from https://github.com/joaotavora/eglot/issues/367#issuecomment-743945487 reliably in this, it's just that the actual sequence of edits which confuses eglot/lsp/pyls are strange. Usually consists of `fill-paragraph` and `undo` and `eglot-format-buffer`.

**Comment by joaotavora** [comment] 2020-12-14 20:31
Gotta say a whole repo for a reproduction recipe is a first! But I'll take it!  :-D

**Comment by joaotavora** [comment] 2020-12-14 21:11
@andschwa I tried your recipe and idneed I reproduced, _something_.  However, I don't think I reproduced this particular bug.  There doesn't seem to be anything inconsistent when you `M-x fill-paragraph`, rather the problem seems to come from `M-x eglot-format-buffer`.  It might or might not be a server bug. I probably have to turn on super-extra debugging in the pyls server so I can see its version of the file.

Anyway, that's for another issue. Closing this one.

**Comment by andschwa** [comment] 2020-12-14 21:18
_Something_'s wrong is about where I'm at too, when I sat down trying to repro the OP's issue (which I have _also_ seen while working in Python projects). Thanks @joaotavora!

**Comment by andschwa** [comment] 2020-12-15 00:47
For what it's worth, while working today, I found that the OP repro does repro for me in Python. Not when filling docstrings, but when filling comments, and it doesn't seem fixed with that commit 😢

**Comment by joaotavora** [comment] 2020-12-15 08:29
I've reproduced the problem in terms of a simple repro

```
emacs -Q -f package-initialize -L . -l eglot ~/tmp/coiso.py -f eglot
```

Where `~/tmp/coiso.py` is a simple Python file:
```
class Foo:
    """Pellentesque dapibus suscipit ligula. Nullam tempus. Nullam
tristique diam non turpis. Aliquam feugiat tellus ut neque.

Cras placerat accumsan nulla. Curabitur lacinia pulvinar nibh. Proin
neque massa, cursus ut, gravida ut, lobortis eget, lacus. Donec
pretium posuere tellus.

    """

    def foo():
        x = 1
        if x == 1:
            # indented four spaces
            print("x is 1.")
```

and Emacs version is 26.3 and all the packages are up to date.  I played around filling those docstrings and eventually the program below broke.  @andschwa you can delete that repo.

**Comment by joaotavora** [comment] 2020-12-15 09:58
And this is what Emacs sends pyls for filling in that paragraph.  IT's exactly what it sends for the Go server, as explained here https://github.com/joaotavora/eglot/issues/367#issuecomment-744432159, but the Go server can deal with it correctly, and the Python `pyls` server can't.  It seems to think we've reported a deletion of the second line _and_ its entire contents.
```lisp
[client-notification] Tue Dec 15 08:35:30 2020:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
          (:textDocument
           (:uri "file:///home/capitaomorte/tmp/coiso.py" :version 2)
           :contentChanges
           [(:range
             (:start
              (:line 1 :character 0)
              :end
              (:line 1 :character 2))
             :rangeLength 2 :text "")
            (:range
             (:start
              (:line 0 :character 10)
              :end
              (:line 1 :character 11))
             :rangeLength 1 :text " ")]))
[server-notification] Tue Dec 15 08:35:31 2020:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:uri "file:///home/capitaomorte/tmp/coiso.py" :diagnostics
                [(:source "pycodestyle" :range
                          (:start
                           (:line 0 :character 10)
                           :end
                           (:line 0 :character 12))
                          :message "W291 trailing whitespace" :code "W291" :severity 2)]))
```

**Comment by joaotavora** [comment] 2020-12-15 12:37
Alright, I pushed a new, more ambitious fix, which I've tested manually in Python and Go modes.  Please everybody try that out.

**Closed** 2020-12-15 12:36 UTC
Labels: bug, emacs-bug

**Comment by notmgsk** [comment] 2020-12-15 12:46
Cannot reproduce in either `gopls` or `python-language-server`. :+1:

**Comment by andschwa** [comment] 2020-12-15 22:29
This seems to have done it! I haven't run into a single issue today. Thank you SO MUCH @joaotavora. 🤩

**Comment by joaotavora** [comment] 2020-12-15 22:31
Thanks.  You're very welcome.  I'll soon be doing some go myself, and it seems to have an excellent LS, so likely I'll devote some more time to Eglot in the near future.
