### ISSUE TITLE
Issue when trying to complete

### ISSUE THREAD

**Issue by L42y** [joaotavora/eglot#5] opened 2018-05-21 04:23 UTC
without company-mode:
```
eglot--error: [eglot] Ooops: -32001: ~/**/**/node_modules/@types/react/package.json is not an absolute path
```

with company-mode:
```
Company: An error occurred in auto-begin
Company: backend company-capf error "[eglot] Ooops: -32001: ~/**/**/node_modules/@types/react/package.json is not an absolute path" with args (candidates im)
```

**Comment by joaotavora** [comment] 2018-05-21 07:19
My crystal ball guesses that you are version 0.3. In 0.4 this problem should be fixed.0.4 isn't available yet from ELPA but should be very soon. So the alternative is to try the latest from github.

BTW I might be wrong, but it's very hard to discover what the problem is if you don't provide more context. eglot version, server name and version, etc, and most importantly, a clear explanation of what you did before reaching the unexpected situation.

**Closed as completed** 2018-05-21 09:21 UTC

**Comment by joaotavora** [comment] 2018-05-21 09:41
good to hear that. 0.4 is now on available on ELPA, btw
