### ISSUE TITLE
eglot + ediff-regions-wordwise errors out

### ISSUE THREAD

**Issue by jojojames** [joaotavora/eglot#116] opened 2018-09-16 20:34 UTC
```
(setq package-enable-at-startup nil
      package-archives
      '(("melpa" . "http://melpa.milkbox.net/packages/")
        ("gnu" . "http://elpa.gnu.org/packages/")))

(require 'package)
(package-initialize)
(package-install 'eglot)

;; Visit python file.
;; M-x toggle-debug-on-error
;; M-x eglot
;; M-x ediff-regions-wordwise
;; Move cursor around to trigger eldoc.
```

```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  file-truename(nil)
  eglot--path-to-uri(nil)
  eglot--TextDocumentIdentifier()
  eglot--TextDocumentPositionParams()
  eglot-eldoc-function()
  apply(eglot-eldoc-function nil)
  #f(advice-wrapper :before-until #f(advice-wrapper :before-until #f(compiled-function (&rest args) #<bytecode 0x406be941>) python-eldoc-function) eglot-eldoc-function)()
  eldoc-print-current-symbol-info()
  #f(compiled-function () #<bytecode 0x400def01>)()
  apply(#f(compiled-function () #<bytecode 0x400def01>) nil)
  timer-event-handler([t 0 0 500000 nil #f(compiled-function () #<bytecode 0x400def01>) nil idle 0])
  recursive-edit()
  ediff-clone-buffer-for-region-comparison("TestPython.py" "-Region.A-")
  ediff-regions-wordwise("TestPython.py" "TestPython.py")
  funcall-interactively(ediff-regions-wordwise "TestPython.py" "TestPython.py")
  call-interactively(ediff-regions-wordwise record nil)
  command-execute(ediff-regions-wordwise record)
  execute-extended-command(nil "ediff-regions-wordwise" "ediff-regions-wo")
  funcall-interactively(execute-extended-command nil "ediff-regions-wordwise" "ediff-regions-wo")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

;; M-x kill-buffer
```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  file-truename(nil)
  eglot--path-to-uri(nil)
  eglot--TextDocumentIdentifier()
  eglot--signal-textDocument/didClose()
  kill-buffer("TestPython.py-Region.A-")
  funcall-interactively(kill-buffer "TestPython.py-Region.A-")
  call-interactively(kill-buffer nil nil)
  command-execute(kill-buffer)
```

**Comment by joaotavora** [comment] 2018-09-17 09:15
Confirmed.

**Comment by mkcms** [comment] 2018-11-07 11:00
The issue is that the buffers created by ediff are not actually visiting any files, and eglot wants to use their filename.

A couple of solutions could be:
1. Don't enable eglot in non-file-visiting buffers
2. Don't use features that require knowing the buffer file name
3. Assume that the filename of current buffer is the buffer name.

I've opened #150 using the third option.

**Comment by joaotavora** [comment] 2018-12-01 22:48
The problem is actually indirect buffers. Pushed a fix for this.

**Closed** 2018-12-01 22:48 UTC
Labels: bug
