### ISSUE TITLE
args-out-of-range using clangd

### ISSUE THREAD

**Issue by abroekhof** [joaotavora/eglot#867] opened 2022-03-11 02:22 UTC
I'm getting this as soon as I start typing, so maybe something related to flymake? I've tried installing the latest flymake using use-package.

Backtrace
```
Debugger entered--Lisp error: (args-out-of-range #<buffer assert_test.cc> 812 1033)
  eglot-lsp-abiding-column(812)
  eglot-move-to-lsp-abiding-column(2)
  eglot--lsp-position-to-point((:character 2 :line 23) nil)
  eglot--range-region((:end (:character 11 :line 23) :start (:character 2 :line 23)))
  #f(compiled-function (arg1 arg2 &rest rest) "Handle notification publishDiagnostics." #<bytecode -0x31a6687ce725321>)(#<eglot-lsp-server eglot-lsp-server-1fdf4be3ab14> textDocument/publishDiagnostics :diagnostics [(:code "pp_file_not_found" :message "'gtest/gtest.h' file not found" :range (:end (:character 24 :line 16) :start (:character 9 :line 16)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 19) :start (:character 5 :line 19)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'AssertTrue'" :range (:end (:character 23 :line 19) :start (:character 13 :line 19)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 19) :start (:character 0 :line 19)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'bb'" :range (:end (:character 4 :line 21) :start (:character 2 :line 21)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'EXPECT_EQ'" :range (:end (:character 11 :line 23) :start (:character 2 :line 23)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 27) :start (:character 5 :line 27)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'DebugAssertTrue'" :range (:end (:character 28 :line 27) :start (:character 13 :line 27)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 27) :start (:character 0 :line 27)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'EXPECT_EQ'" :range (:end (:character 13 :line 31) :start (:character 4 :line 31)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'EXPECT_EQ'" :range (:end (:character 13 :line 33) :start (:character 4 :line 33)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 42) :start (:character 5 :line 42)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'AssertFalse'" :range (:end (:character 24 :line 42) :start (:character 13 :line 42)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 42) :start (:character 0 :line 42)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 48) :start (:character 5 :line 48)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'DebugAssertFalse'" :range (:end (:character 29 :line 48) :start (:character 13 :line 48)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 48) :start (:character 0 :line 48)) :severity 1 :source "clang")] :uri "<redacted>" :version 9)
  apply(#f(compiled-function (arg1 arg2 &rest rest) "Handle notification publishDiagnostics." #<bytecode -0x31a6687ce725321>) #<eglot-lsp-server eglot-lsp-server-1fdf4be3ab14> textDocument/publishDiagnostics (:diagnostics [(:code "pp_file_not_found" :message "'gtest/gtest.h' file not found" :range (:end (:character 24 :line 16) :start (:character 9 :line 16)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 19) :start (:character 5 :line 19)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'AssertTrue'" :range (:end (:character 23 :line 19) :start (:character 13 :line 19)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 19) :start (:character 0 :line 19)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'bb'" :range (:end (:character 4 :line 21) :start (:character 2 :line 21)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'EXPECT_EQ'" :range (:end (:character 11 :line 23) :start (:character 2 :line 23)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 27) :start (:character 5 :line 27)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'DebugAssertTrue'" :range (:end (:character 28 :line 27) :start (:character 13 :line 27)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 27) :start (:character 0 :line 27)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'EXPECT_EQ'" :range (:end (:character 13 :line 31) :start (:character 4 :line 31)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'EXPECT_EQ'" :range (:end (:character 13 :line 33) :start (:character 4 :line 33)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 42) :start (:character 5 :line 42)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'AssertFalse'" :range (:end (:character 24 :line 42) :start (:character 13 :line 42)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 42) :start (:character 0 :line 42)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 48) :start (:character 5 :line 48)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'DebugAssertFalse'" :range (:end (:character 29 :line 48) :start (:character 13 :line 48)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 48) :start (:character 0 :line 48)) :severity 1 :source "clang")] :uri "<redacted>" :version 9))
  eglot-handle-notification(#<eglot-lsp-server eglot-lsp-server-1fdf4be3ab14> textDocument/publishDiagnostics :diagnostics [(:code "pp_file_not_found" :message "'gtest/gtest.h' file not found" :range (:end (:character 24 :line 16) :start (:character 9 :line 16)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 19) :start (:character 5 :line 19)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'AssertTrue'" :range (:end (:character 23 :line 19) :start (:character 13 :line 19)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 19) :start (:character 0 :line 19)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'bb'" :range (:end (:character 4 :line 21) :start (:character 2 :line 21)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'EXPECT_EQ'" :range (:end (:character 11 :line 23) :start (:character 2 :line 23)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 27) :start (:character 5 :line 27)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'DebugAssertTrue'" :range (:end (:character 28 :line 27) :start (:character 13 :line 27)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 27) :start (:character 0 :line 27)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'EXPECT_EQ'" :range (:end (:character 13 :line 31) :start (:character 4 :line 31)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'EXPECT_EQ'" :range (:end (:character 13 :line 33) :start (:character 4 :line 33)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 42) :start (:character 5 :line 42)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'AssertFalse'" :range (:end (:character 24 :line 42) :start (:character 13 :line 42)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 42) :start (:character 0 :line 42)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 48) :start (:character 5 :line 48)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'DebugAssertFalse'" :range (:end (:character 29 :line 48) :start (:character 13 :line 48)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 48) :start (:character 0 :line 48)) :severity 1 :source "clang")] :uri "<redacted>" :version 9)
  apply(eglot-handle-notification #<eglot-lsp-server eglot-lsp-server-1fdf4be3ab14> textDocument/publishDiagnostics (:diagnostics [(:code "pp_file_not_found" :message "'gtest/gtest.h' file not found" :range (:end (:character 24 :line 16) :start (:character 9 :line 16)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 19) :start (:character 5 :line 19)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'AssertTrue'" :range (:end (:character 23 :line 19) :start (:character 13 :line 19)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 19) :start (:character 0 :line 19)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'bb'" :range (:end (:character 4 :line 21) :start (:character 2 :line 21)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'EXPECT_EQ'" :range (:end (:character 11 :line 23) :start (:character 2 :line 23)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 27) :start (:character 5 :line 27)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'DebugAssertTrue'" :range (:end (:character 28 :line 27) :start (:character 13 :line 27)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 27) :start (:character 0 :line 27)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'EXPECT_EQ'" :range (:end (:character 13 :line 31) :start (:character 4 :line 31)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'EXPECT_EQ'" :range (:end (:character 13 :line 33) :start (:character 4 :line 33)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 42) :start (:character 5 :line 42)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'AssertFalse'" :range (:end (:character 24 :line 42) :start (:character 13 :line 42)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 42) :start (:character 0 :line 42)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 48) :start (:character 5 :line 48)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'DebugAssertFalse'" :range (:end (:character 29 :line 48) :start (:character 13 :line 48)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 48) :start (:character 0 :line 48)) :severity 1 :source "clang")] :uri "<redacted>" :version 9))
  #f(compiled-function (server method params) #<bytecode 0x1c90d1a72a4e5f94>)(#<eglot-lsp-server eglot-lsp-server-1fdf4be3ab14> textDocument/publishDiagnostics (:diagnostics [(:code "pp_file_not_found" :message "'gtest/gtest.h' file not found" :range (:end (:character 24 :line 16) :start (:character 9 :line 16)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 19) :start (:character 5 :line 19)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'AssertTrue'" :range (:end (:character 23 :line 19) :start (:character 13 :line 19)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 19) :start (:character 0 :line 19)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'bb'" :range (:end (:character 4 :line 21) :start (:character 2 :line 21)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'EXPECT_EQ'" :range (:end (:character 11 :line 23) :start (:character 2 :line 23)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 27) :start (:character 5 :line 27)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'DebugAssertTrue'" :range (:end (:character 28 :line 27) :start (:character 13 :line 27)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 27) :start (:character 0 :line 27)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'EXPECT_EQ'" :range (:end (:character 13 :line 31) :start (:character 4 :line 31)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'EXPECT_EQ'" :range (:end (:character 13 :line 33) :start (:character 4 :line 33)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 42) :start (:character 5 :line 42)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'AssertFalse'" :range (:end (:character 24 :line 42) :start (:character 13 :line 42)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 42) :start (:character 0 :line 42)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 48) :start (:character 5 :line 48)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'DebugAssertFalse'" :range (:end (:character 29 :line 48) :start (:character 13 :line 48)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 48) :start (:character 0 :line 48)) :severity 1 :source "clang")] :uri "<redacted>" :version 9))
  jsonrpc-connection-receive(#<eglot-lsp-server eglot-lsp-server-1fdf4be3ab14> (:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params (:diagnostics [(:code "pp_file_not_found" :message "'gtest/gtest.h' file not found" :range (:end (:character 24 :line 16) :start (:character 9 :line 16)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 19) :start (:character 5 :line 19)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'AssertTrue'" :range (:end (:character 23 :line 19) :start (:character 13 :line 19)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 19) :start (:character 0 :line 19)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'bb'" :range (:end (:character 4 :line 21) :start (:character 2 :line 21)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'EXPECT_EQ'" :range (:end (:character 11 :line 23) :start (:character 2 :line 23)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 27) :start (:character 5 :line 27)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'DebugAssertTrue'" :range (:end (:character 28 :line 27) :start (:character 13 :line 27)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 27) :start (:character 0 :line 27)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'EXPECT_EQ'" :range (:end (:character 13 :line 31) :start (:character 4 :line 31)) :severity 1 :source "clang") (:code "undeclared_var_use" :message "Use of undeclared identifier 'EXPECT_EQ'" :range (:end (:character 13 :line 33) :start (:character 4 :line 33)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 42) :start (:character 5 :line 42)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'AssertFalse'" :range (:end (:character 24 :line 42) :start (:character 13 :line 42)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 42) :start (:character 0 :line 42)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'Assert'" :range (:end (:character 11 :line 48) :start (:character 5 :line 48)) :severity 1 :source "clang") (:code "unknown_typename" :message "Unknown type name 'DebugAssertFalse'" :range (:end (:character 29 :line 48) :start (:character 13 :line 48)) :severity 1 :source "clang") (:code "missing_type_specifier" :message "C++ requires a type specifier for all declarations" :range (:end (:character 4 :line 48) :start (:character 0 :line 48)) :severity 1 :source "clang")] :uri "<redacted>" :version 9)))
  jsonrpc--process-filter(#<process EGLOT (a10a20/c++-mode)> "Content-Length: 3348\15\n\15\n{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/publishDiagnostics\",\"params\":{\"diagnostics\":[{\"code\":\"pp_file_not_found\",\"message\":\"'gtest/gtest.h' file not found\",\"range\":{\"end\":{\"cha...")

```

Relevant config:
```
(use-package flymake)
  (use-package eglot
        :ensure t
        :commands (eglot eglot-ensure)
        :hook ((c-mode . eglot-ensure)
               (c++-mode . eglot-ensure))
        :config
        (add-to-list 'eglot-server-programs '((c-mode c++-mode) . ("~/.environment/packages/pigweed/bin/clangd" "--compile-commands-dir=/Users/abroekhof/out" "--query-driver=/Users/abroekhof/.environment/packages/**/*"
                                                                   "--background-index" "--log=verbose" "--clang-tidy"))))
```

**Comment by vladimir-didenko** [comment] 2022-03-11 08:01
I have the same issue. I could reproduce it with the following program
```C++
#include <iostream>

using std::cout;

int main(int argc, char *argv[])
{
    auto badbit = cout.eofbit;
    return 0;
}
```
In this program error could be triggered by the line 
```C++
   auto badbit = cout.eofbit;
```
when I type cout. (sometimes, it is cout.e) I see the following error reported 
```
error in process filter: Args out of range: #<buffer main.cc>, 100, 116
```

**Comment by joaotavora** [comment] 2022-03-11 08:04
Duplicate of #860

**Closed by joaotavora** 2022-03-11 08:04 UTC
