### ISSUE TITLE
Setting up: [eglot] -1: Server died; possibly (probably) user error

### ISSUE THREAD

**Issue by thor314** [joaotavora/eglot#543] opened 2020-09-22 10:35 UTC
In my emacs config file, after following the [rls server instructions](https://github.com/rust-lang/rls):
```emacs-lisp
(use-package eglot)
(add-to-list 'eglot-server-programs '(rust-mode . ("rls" ""))) 
```
On `M-x eglot` in a .rs file, got the error 
```
[jsonrpc] Server exited with status 101
eglot--error: [eglot] -1: Server died
```
I then tried to setup eglot for `bash-mode`. I succeeded doing a similar procedure. In my config:
```emacs-lisp
(use-package eglot
	:commands eglot
	:hook
	(sh-mode . eglot))
	(add-to-list 'eglot-server-programs '(bash-mode . ("bash-language-server" "")))
```
which worked. 

*SUGGESTED FIX*
More setup examples would be rather useful.

**Comment by joaotavora** [comment] 2020-09-22 10:39
> More setup examples would be rather useful.

Maybe, but your case is as simple as it is.  I think it is more useful to give you this tip, which is in the README I think.  Use `M-x eglot-events-buffer` to see a log of what might have gone wrong.

And for "rls", I don't think you need to do your `add-to-list`.  It's supported out of the box in Eglot., so your `add-to-list` line probably isn't needed.

**Comment by thor314** [comment] 2020-09-22 10:50
Hmm, I'm getting this message:
File mode specification error: (wrong-number-of-arguments (4 . 5) 0)

```emacs-lisp
		(use-package eglot
		:commands eglot
		:hook
	(rust-mode . eglot))
```
and when I use `M-x eglot-events-buffer`, I'm getting the message 
[eglot] Can't find an Eglot events buffer!

**Comment by joaotavora** [comment] 2020-09-22 11:17
`use-package` is something alien to me, it's not a part of Emacs, but that `hook` is fishy (I don't know what it does).

Can you switch to the events buffer manually?  Use `C-x b` for that.  The Eglot events buffer is suitably named `*EGLOT (<project>) events*`.

**Comment by muffinmad** [comment] 2020-09-22 11:26
>Can you switch to the events buffer manually?

There be no events buffer. The error `(wrong-number-of-arguments (4 . 5) 0)` is coming from attempt to run eglot with `M-: (eglot)`.

@thor314 Please try to replace `(rust-mode . eglot)` with `(rust-mode . eglot-ensure)` or start eglot manually by `M-x eglot`.

**Comment by thor314** [comment] 2020-09-22 11:34
@joaotavora : `use-package` is just a somewhat common package-manager, with a bit more macro fanciness than `require`.
The equivalent would be
```
(require `eglot)
(add-hook rust-mode-hook #'eglot))
```

@muffinmad manually `M-x eglot` results in the `-1 server died` error message I mentioned at the top, but I now have an `eglot events log`. The file is a little long. Is there something I should be looking for in the `events` buffer? Its output:
```
[client-request] (id:1) Tue Sep 22 13:33:31 2020:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
					(:processId 40346 :rootPath "/Users/thor/rust/franklin-crypto/" :rootUri "file:///Users/thor/rust/franklin-crypto/" :initializationOptions nil :capabilities
											(:workspace
											 (:applyEdit t :executeCommand
																	 (:dynamicRegistration :json-false)
																	 :workspaceEdit
																	 (:documentChanges :json-false)
																	 :didChangeWatchedFiles
																	 (:dynamicRegistration t)
																	 :symbol
																	 (:dynamicRegistration :json-false)
																	 :configuration t)
											 :textDocument
											 (:synchronization
												(:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
												:completion
												(:dynamicRegistration :json-false :completionItem
																							(:snippetSupport :json-false)
																							:contextSupport t)
												:hover
												(:dynamicRegistration :json-false :contentFormat
																							["markdown" "plaintext"])
												:signatureHelp
												(:dynamicRegistration :json-false :signatureInformation
																							(:parameterInformation
																							 (:labelOffsetSupport t)))
												:references
												(:dynamicRegistration :json-false)
												:definition
												(:dynamicRegistration :json-false)
												:declaration
												(:dynamicRegistration :json-false)
												:implementation
												(:dynamicRegistration :json-false)
												:typeDefinition
												(:dynamicRegistration :json-false)
												:documentSymbol
												(:dynamicRegistration :json-false :hierarchicalDocumentSymbolSupport t :symbolKind
																							(:valueSet
																							 [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
												:documentHighlight
												(:dynamicRegistration :json-false)
												:codeAction
												(:dynamicRegistration :json-false :codeActionLiteralSupport
																							(:codeActionKind
																							 (:valueSet
																								["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"])))
												:formatting
												(:dynamicRegistration :json-false)
												:rangeFormatting
												(:dynamicRegistration :json-false)
												:rename
												(:dynamicRegistration :json-false)
												:publishDiagnostics
												(:relatedInformation :json-false))
											 :experimental nil)))
[internal] Tue Sep 22 13:33:31 2020:
(:message "Connection state changed" :change "exited abnormally with code 101\n")

----------b---y---e---b---y---e----------
```

**Comment by joaotavora** [comment] 2020-09-22 11:40
> @joaotavora : use-package is just a somewhat common package-manager, with a bit more macro fanciness than require.

I know what it is, but I don't like macro fancinesses because they introduce uncertainty in bug reproduction recipes.  The equivalent form is much simpler and is universally understood by Emacs developers.

As to the events buffer, it seems to be missing the "stderr" output.  All we know is that your program exited abruptly with code 101, and no idea what that is. Either:

1. the "rls" server didn't output any stderr output;

2.  it did and we're not seeing it (you may be running an older Eglot version, so look for the `*EGLOT (<project> stderr*` or likely named buffer.

A better way to debug is, maybe, is to execute the "rls" executable in the source directory of your project.

**Comment by thor314** [comment] 2020-09-22 12:33
Okay, so things seem to be working now. The brilliant solution appears to be to just not use `use-package`. Thanks for helping. It's actually very impressive that installation is this simple.

I ended up with these lines, 
```
	(use-package eglot)
	(add-hook 'sh-mode-hook 'eglot-ensure)
	(add-hook 'rust-mode-hook 'eglot-ensure)
```
I think my problem was that instead of this line:
`(add-to-list 'eglot-server-programs '(rust-mode . ("rls")))`
I had this line:
`(add-to-list 'eglot-server-programs '(rust-mode . ("rls" "")))`
Thanks for the help.

**Comment by joaotavora** [comment] 2020-09-22 13:26
> The brilliant solution appears to be to just not use use-package

As you note below, it's not the solution per se.  But it isn't required.

>  It's actually very impressive that installation is this simple.

I (we) put substantial work into just this.

> (add-to-list 'eglot-server-programs '(rust-mode . ("rls" "")))

Which means to add call Rls with an extra argument of an empty string.  Not sure how that broke `rls` but it did.

Notice that you should have slightly more success if you use the default entry for `rust-mode` in Eglot, which is `(rust-mode . (eglot-rls "rls"))`.  This is an exception: most other language servers will use an entry just like you fashioned, but `rls` in particular works slightly better with the one I gave you (at least it did when I designed it).

**Comment by muffinmad** [comment] 2020-10-07 19:49
> Okay, so things seem to be working now

In this case I'm closing this issue.

**Closed by muffinmad** 2020-10-07 19:49 UTC
