### ISSUE TITLE
Eglot wont add functions parenthesis 

### ISSUE THREAD

**Issue by lxbarbosa** [joaotavora/eglot#292] opened 2019-08-04 01:03 UTC
Hi,

Most editors add a parens when functions/methods completions are selected. Eglot aint adding it.

I can confirm that the same issue happens with other LSP servers as gopls, ccls, eclipse...

Reproducing
---

what happens:
``` python
pri|
print 
```

expected :
```python
pri|
print()
```

---
Emacs: master(27) upstream
eglot: 1.4  20190910.1347
Debian 10 SID

**Comment by nemethf** [comment] 2019-09-20 10:11
Isn't this a server-side issue?  In python2, you don't need to use parentheses after print.  Pressing C-M-i after pr, I get 
```
print Keyword
property Class (snippet)
```
and sure enough I have parentheses if I select "property" (with yas-global-mode enabled).

**Comment by lxbarbosa** [comment] 2019-09-20 14:55
@nemethf  

Cant say if its a server-side issue.  I was expecting that LSP covers that feature too.

I can confirm that with company no parens is add when functions/methods are selected!

**Comment by GabCamarda** [comment] 2019-09-21 20:34
Also having this issue using company with Java. Alternatives such as lsp-java automatically adds parentheses and the import statement at the top of the file. Is this something that can be implemented in Eglot?

**Comment by joaotavora** [comment] 2019-09-22 04:15
> Is this something that can be implemented in Eglot?

Probably, but I need to understand exactly what you are trying to achieve. Is this similar to what is described in #301? I.e. are you trying to select a "snippet completion"?

**Comment by GabCamarda** [comment] 2019-09-22 15:41
Thanks for your reply. 
It looks similar to that issue you linked. Thinking about it, lsp-java probably uses yas-snippets to autocomplete the method call. The auto-adding imports may be related to another feature that lsp-java supports. I've also noticed eglot does not provide support for finding the implementation of a method defined in an interface (only noticed this with Java, haven't tried other languages). With LSP this is bound do `lsp-goto-implementation`. I appreciate this is another matter though so I will open a new issue.

**Comment by nemethf** [comment] 2019-09-23 12:41
But there is snippet support in eglot: https://raw.githubusercontent.com/joaotavora/eglot/master/gif-examples/eglot-snippets-on-completion.gif

However, I think it is not well documented.  yas-global-mode or (yas-minor-mode in the buffer) should be enabled before eglot contacts the lsp server.  As the gif shows, snippet support works with company as well.  (But you won't get parentheses after 'print', because pyls doesn't send them: 'print' is a statement and not a function/method in python2.)

**Comment by GabCamarda** [comment] 2019-09-23 20:10
I do have yas-snippet turned on globally, but it still does not autocomplete like in the gif you linked. I've only tested eglot with Java.

**Comment by lxbarbosa** [comment] 2019-09-24 11:38
@nemethf 
As said, its not a pyls issue but in most LSP servers using Eglot.

Cant say if eglot and editors should be the one to auto-add parens to functions/methods or statements as you said.

Still, it fairless boring to have to add by ourselves parens that are always required by programming languages syntax parsers!

**Comment by lxbarbosa** [comment] 2019-09-24 15:11
oh boy, I think I will to screencast it... :D

**Comment by nemethf** [comment] 2019-09-24 16:33
I don't use java, therefore can't help @GabCamarda; and it seems we have a miscommunication with @lxbarbosa,  so the following might not belong here, but...

> Maybe we could change that, i.e. always say `t` to `SnippetSuppport` and then maybe filter out snippet completions if it turns out we don't have it enabled.

... I think that won't work.  pyls, for example, sends only one completion item for a given function when SnippetSupport is enabled, so if eglot filters that out, then the completion item will be missing from the result. 

However, one possibility might be to dynamically register/unregister the snippet support capability right before requesting a completion.  That is if yas-mode is now enabled and it wasn't previously, then register the capability and vice versa.  (I'm not really familiar with this part of the specification to tell whether this is feasible.)

**Comment by joaotavora** [comment] 2019-09-24 16:43
> ... I think that won't work. pyls, for example, sends only one completion item for a given function when SnippetSupport is enabled, so if eglot filters that out, then the completion item will be missing from the result.

Make senses. There won't be any way to complete that function's name, snippet or non-snippet.

> However, one possibility might be to dynamically register/unregister the snippet support capability right before requesting a completion. That is if yas-mode is now enabled and it wasn't previously, then register the capability and vice versa. (I'm not really familiar with this part of the specification to tell whether this is feasible.)

I think the registering/unregistering starts from the server, so it's no use here.  But I'm not too sure either.

Anyway, this was a just an attempt to ameliorate the situation, **supposing** that it would improve something.  I just noticed the "should be enabled before eglot contacts the lsp server" and wondered if that is the cause for some of these bug reports. If it isn't, then we shouldn't change anything there.

**Comment by GabCamarda** [comment] 2019-09-24 19:52
It does indeed sound like the snippets are not working as they're supposed to. I have `yas-snippets` turned on globally and I've tested this by manually enabling `eglot` in a buffer and the functions are definitely not autocompleted like in the gif @nemethf linked. `company-mode` works fine though. I'm going to keep testing it and see if I can debug it somehow.

**Comment by joaotavora** [comment] 2019-09-25 10:25
> It does indeed sound like the snippets are not working as they're supposed to.

The snippets in the gif are snippets **that have** parenthesis, I have no idea if the snippets you are using **also** have them.  If they don't, then it's probably **not** Eglot's fault (unless there is something in the LSP protocol that escapes me).

So let's find out if the LSP server is sending snippets with parenthesis. @GabCamarda, can you post the contents of the `*Eglot events*` buffer around the time of the `textDocument/completion` request?

**Comment by GabCamarda** [comment] 2019-10-05 13:54
This is the output when I tried to autocomplete a method call. The method is `toDate()`.
```
 client-request (id:25) Sat Oct  5 14:49:21 2019:
 (:jsonrpc "2.0" :id 25 :method "textDocument/completion" :params
           (:textDocument
            (:uri "file:///path/to/file/App.java")
            :position
            (:line 20 :character 20)
            :context
            (:triggerKind 1)))

 server-reply (id:25) Sat Oct  5 14:49:21 2019:
 (:jsonrpc "2.0" :id 25 :result
           (:isIncomplete :json-false :items
                          [(:label "toDate : String" :kind 5 :detail "Flags" :sortText "999998970" :insertText "toDate" :data
                                   (:decl_signature "Lcom.github.gabcamarda.app.Flags;" :name "toDate" :pid "0" :rid "11" :uri "file:///path/to/file/App.java"))]))
```

**Comment by joaotavora** [comment] 2019-10-05 16:50
@GabCamarda thanks.  Your output shows that your LSP server is **not** sending snippets with parenthesis. The first and only completion item of `:label` `"toDate"` has no `insertTextFormat`, that the `:insertText` field is to be taken literally.  

To have parenthesis, `insertTextFormat` would have to be `2` and `insertText` would have to be something like `toDate($0)`.

Please read https://github.com/joaotavora/eglot#reporting-bugs before continuing to report on this problem.

**Comment by joaotavora** [comment] 2019-10-05 17:05
Closing as a server side issue, will reopen once more information is available (particularly event and stderr logs). Thanks

**Closed by joaotavora** 2019-10-05 17:05 UTC
