### ISSUE TITLE
Snippet based completion inserts text twice

### ISSUE THREAD

**Issue by amol-mandhane** [joaotavora/eglot#82] opened 2018-08-20 18:09 UTC
When snippet based completion is triggered, the completion text is inserted twice with snippets enabled on second text.

I think the part of `(delete-region (car bounds) (point))` in `:exit-function` is the culprit.  I locally replaced it with `(delete-backward-char (length obj))` and it works fine.

**Comment by joaotavora** [comment] 2018-08-20 18:15
It's very odd that I can't reproduce this.  Can you present a reproduction recipe from `Emacs -Q`? Still I will consider your solution, which isn't bad.

**Comment by amol-mandhane** [comment] 2018-08-20 18:18
I'm running this in a stripped down version of emacs with only helm, company, yas, and eglot packages.  I'm doing this with eglot master HEAD code with clangd language server in C++.

**Comment by amol-mandhane** [comment] 2018-08-20 18:37
Same issue with emacs -Q

**Comment by joaotavora** [comment] 2018-08-20 18:54
> Same issue with emacs -Q

That's very odd. Also, normally when I request an `emacs -Q` recipe I am requesting a way to reproduce the problem exactly as it happened to you, so that I can rule out external interference.  By just saying you have the same issue, it doesn't help me much. 

Can you provide the actual line you used and the steps to start eglot?  Alternatively, can you start with the steps that I give below, in the Eglot checkout directory and with Emacs 26.1?
```
PATH+=':~/Downloads/2018-05/cquery-v20180302-x86_64-unknown-linux-gnu/bin' \
emacs -Q -f package-initialize -f yas-global-mode -f global-company-mode -L . -l eglot ~/Source/Arduino/avr-tutorial/stepper.cpp -f eglot
```

The result, in a gif:

![peek 2018-08-20 19-50](https://user-images.githubusercontent.com/387011/44360336-822e3380-a4b2-11e8-9fcb-4f028a6e5993.gif)


By the way, clangd-6.0 doesn't provide any snippets for me, so I had to use cquery, as you see above. Which exact version of `clangd` are you using?

**Comment by amol-mandhane** [comment] 2018-08-20 21:16
Figured out the issue.  The solution I suggested should solve it.

The command I'm running is
```
emacs -Q  -f package-initialize -l eglot --eval "(progn (add-to-list 'eglot-server-programs '(c++-mode . (\"/usr/bin/clangd\" \"--limit-results=50\"))) (setq company-backends '(company-capf)))" -f global-company-mode -f yas-global-mode <cpp-file-name> -f eglot
```

I also added some `message` statements to the exit-function and I discovered that the `bounds` variable is incorrect.  So, delete-region is not deleting what we want to delete.  Tracing the bound variable reveals that it is taken from `bounds-of-thing-at-point`.  What is actually happening is that exit-function is taking the bounds-of-thing-at-point to delete **after** completion, not before.  So, if the inserted completion label to delete contains multiple "things", exit-function is going to delete just one of them and insert the snippet.

For instance, following is the relevant stuff in my completionItem.
```
(...
:insertText "AppendPartialToCord(${1:Cord *output})"
:label " AppendPartialToCord(Cord *output) const"
...)
```
So, eglot inserts the label and puts point at the end of "const" in the label it just inserted.  Then, it takes bounds-of-thing-at-point, which returns the bounds of "const" and deletes the const instead of deleting the entire completion label that it just inserted.  Then it inserts the snippet text.  The combined result of which renders the effect of inserting the text twice.

The solution I suggested doesn't make the assumption that the label will contain exactly one "thing".  That's why it should work.

**Comment by joaotavora** [comment] 2018-08-20 22:52
> What is actually happening is that exit-function is taking the bounds-of-thing-at-point to delete after 

Indeed. Company unexpectedly (and needlessly) calls this function more than once.

>  That's why it should work.

I never said it didn't. But I make it a point to understand a problem before I apply any solution.

Should be fixed with a fix similar to yours.

**Closed** 2018-08-20 22:53 UTC
Labels: can't reproduce
