### ISSUE TITLE
Incorrect TAB region for interface{}

### ISSUE THREAD

**Issue by seagle0128** [joaotavora/eglot#119] opened 2018-09-22 05:37 UTC
I am trying `eglot` instead of `lsp-mode`, and I fount eh 
https://github.com/tigersoldier/company-lsp/issues/55.

![company-lsp](https://user-images.githubusercontent.com/140797/45410791-37fd3400-b6a5-11e8-81b9-1380df98feba.gif)

Please check. Thanks!

**Comment by joaotavora** [comment] 2018-09-22 09:33
Please explain new what the problem is. What server you are using.
What versions of the software you are using.
What is happening and what should be happening in your opinion.

**Comment by seagle0128** [comment] 2018-09-22 15:53
As the screenshot, in (..., interface{}), press TAB and input some characters, the `)` will be deleted incorrectly. I am using Emacs 26.1 with `eglot` on Ubuntu LTS 18.04. This issue exists on all OS platforms.

I attached [company-diag.txt](https://github.com/joaotavora/eglot/files/2407944/company-diag.txt).
You can see completion items with `interface{}`as parameters. As https://github.com/tigersoldier/company-lsp/issues/55#issuecomment-422152061, 
> The snippet sent from Go language server doesn't escape {. The snippet is like panic(${1:interface{\\}})$0, which can't be handled by yasnippet. Changing that to panic(${1:interface\\{\\}})$0 works fine.

Obviously `{` should be escaped in `eglot`.

Hope it's clear.

**Comment by joaotavora** [comment] 2018-09-24 12:29
> Obviously { should be escaped in eglot.

Why do you say this is "obvious"?

To me, it makes more sense to handle this in yasnippet or in the Go language server.

**Comment by seagle0128** [comment] 2018-09-24 13:30
According to https://github.com/tigersoldier/company-lsp/issues/55, the LSP clients of VScode and other editors including `lsp-mode` handle this case, so I said obviously. Of course, itt's fine hanle it in langservers, but I am afraid not all langservers handle this case. It's better handle in clients IMO.

**Comment by joaotavora** [comment] 2023-03-26 19:36
Closing this.  I don't think this problem exists anymore in the `gopls` I just tried. Let me know if I should reopen..

**Closed by joaotavora** 2023-03-26 19:36 UTC
