### ISSUE TITLE
Diagnostics error

### ISSUE THREAD

**Issue by julienfantin** [joaotavora/eglot#28] opened 2018-06-22 04:25 UTC
I'm getting an error which seems to be caused by [this line](https://github.com/joaotavora/eglot/blob/master/eglot.el#L1137) where `eglot--make-diag` is invoked with an extra argument.

**Comment by joaotavora** [comment] 2018-06-22 08:35
Duplicate of #21. Update and recompile emacs if you must use master, or just use 26.1

**Closed by joaotavora** 2018-06-22 08:35 UTC

**Comment by joaotavora** [comment] 2018-06-22 08:54
Perhaps I should use another way of telling if the user has a recent enough master

**Comment by bradyt** [comment] 2018-12-26 21:08
This occurs on Windows build of 26.1, built 2018-05-30. See last-modified column at http://ftp.gnu.org/gnu/emacs/windows/emacs-26/.

If I understand correctly, relevant change to flymake did not occur until June 5th of 2018, if this is the relevant commit: https://github.com/emacs-mirror/emacs/commit/fb759a75007d38a8aea6e8c1a22bbc004453a73f.

**Comment by bradyt** [comment] 2018-12-26 21:38
Hmm, for `GNU Emacs 26.1.90 (build 1, x86_64-w64-mingw32) of 2018-11-21`, there are still only five arguments for `flymake-make-diagnostic`.

**Comment by joaotavora** [comment] 2018-12-26 22:56
> If I understand correctly, relevant change to flymake did not occur until June 5th of 2018, if this is the relevant commit: emacs-mirror/emacs@fb759a7.

That is true.  That change is *not* in Emacs 26.1.  However, recent versions of Eglot,when installed via package.el, pull in a new `flymake` package that does have that change.  So in those systems, flymake-make-diagnostic` has a new prototype.

The question is: how are you installing Eglot for Emacs 26.1?

**Comment by bradyt** [comment] 2018-12-28 04:06
Ah, I'm installing via a new package`straight.el`. I believe `(setq straight-recipes-gnu-elpa-use-mirror t)` is now the solution.
