### ISSUE TITLE
Error using Puppet-Language Server

### ISSUE THREAD

**Issue by jleechpe** [joaotavora/eglot#99] opened 2018-09-04 16:05 UTC
When running: [Puppet Language Server](https://github.com/lingua-pupuli/puppet-editor-services) on Windows I get the following error (I can test later on Linux to see if the same issue occurs):

```lisp
(find-file "c:/path/to/file.pp)
(setq debug-on-error t)
(eglot) ;; bundle exec ruby c:\\git\\puppet-editor-services\\puppet-languageserver --stdio --debug=c:\\temp\\eglot-puppet.txt
```

I get the following backtrace (actual path/workspace sanitized).  This error repeats multiple times if debug isn't turned on during editing.  On occasion I get the appropriate docstrings/suggestions echoed out, but often enough they are immediately replaced with the error so I cannot even see their content.

```lisp
Debugger entered--Lisp error: (wrong-number-of-arguments (5 . 5) 6)
  eglot--make-diag(#<buffer proget.pp> 911 933 eglot-warning "Puppet: double quoted string containing no variables" ((eglot-lsp-diag :source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 35 :character 30) :end (:line 35 :character 52)) :code "double_quoted_strings" :severity 2)))
  #f(compiled-function (arg1 arg2 &rest rest) "Handle notification publishDiagnostics" #<bytecode 0x21f4bad>)(#<eglot-lsp-server eglot-lsp-server-2429718> textDocument/publishDiagnostics :uri "file:///c:/path/to/file.pp" :diagnostics [(:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 35 :character 30) :end (:line 35 :character 52)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 38 :character 30) :end (:line 38 :character 108)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 43 :character 23) :end (:line 43 :character 35)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 49 :character 23) :end (:line 49 :character 32)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 55 :character 23) :end (:line 55 :character 36)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 65 :character 12) :end (:line 65 :character 32)) :code "double_quoted_strings" :severity 2)])
  apply(#f(compiled-function (arg1 arg2 &rest rest) "Handle notification publishDiagnostics" #<bytecode 0x21f4bad>) #<eglot-lsp-server eglot-lsp-server-2429718> (textDocument/publishDiagnostics :uri "file:///c:/path/to/file.pp" :diagnostics [(:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 35 :character 30) :end (:line 35 :character 52)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 38 :character 30) :end (:line 38 :character 108)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 43 :character 23) :end (:line 43 :character 35)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 49 :character 23) :end (:line 49 :character 32)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 55 :character 23) :end (:line 55 :character 36)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 65 :character 12) :end (:line 65 :character 32)) :code "double_quoted_strings" :severity 2)]))
  #f(compiled-function (arg &rest args) #<bytecode 0x2420bfd>)(#<eglot-lsp-server eglot-lsp-server-2429718> textDocument/publishDiagnostics :uri "file:///c:/path/to/file.pp" :diagnostics [(:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 35 :character 30) :end (:line 35 :character 52)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 38 :character 30) :end (:line 38 :character 108)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 43 :character 23) :end (:line 43 :character 35)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 49 :character 23) :end (:line 49 :character 32)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 55 :character 23) :end (:line 55 :character 36)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 65 :character 12) :end (:line 65 :character 32)) :code "double_quoted_strings" :severity 2)])
  apply(#f(compiled-function (arg &rest args) #<bytecode 0x2420bfd>) #<eglot-lsp-server eglot-lsp-server-2429718> textDocument/publishDiagnostics (:uri "file:///c:/path/to/file.pp" :diagnostics [(:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 35 :character 30) :end (:line 35 :character 52)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 38 :character 30) :end (:line 38 :character 108)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 43 :character 23) :end (:line 43 :character 35)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 49 :character 23) :end (:line 49 :character 32)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 55 :character 23) :end (:line 55 :character 36)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 65 :character 12) :end (:line 65 :character 32)) :code "double_quoted_strings" :severity 2)]))
  eglot-handle-notification(#<eglot-lsp-server eglot-lsp-server-2429718> textDocument/publishDiagnostics :uri "file:///c:/path/to/file.pp" :diagnostics [(:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 35 :character 30) :end (:line 35 :character 52)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 38 :character 30) :end (:line 38 :character 108)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 43 :character 23) :end (:line 43 :character 35)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 49 :character 23) :end (:line 49 :character 32)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 55 :character 23) :end (:line 55 :character 36)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 65 :character 12) :end (:line 65 :character 32)) :code "double_quoted_strings" :severity 2)])
  apply(eglot-handle-notification (#<eglot-lsp-server eglot-lsp-server-2429718> textDocument/publishDiagnostics :uri "file:///c:/path/to/file.pp" :diagnostics [(:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 35 :character 30) :end (:line 35 :character 52)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 38 :character 30) :end (:line 38 :character 108)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 43 :character 23) :end (:line 43 :character 35)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 49 :character 23) :end (:line 49 :character 32)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 55 :character 23) :end (:line 55 :character 36)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 65 :character 12) :end (:line 65 :character 32)) :code "double_quoted_strings" :severity 2)]))
  #f(compiled-function (&rest args) #<bytecode 0x24296f5>)(#<eglot-lsp-server eglot-lsp-server-2429718> textDocument/publishDiagnostics (:uri "file:///c:/path/to/file.pp" :diagnostics [(:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 35 :character 30) :end (:line 35 :character 52)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 38 :character 30) :end (:line 38 :character 108)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 43 :character 23) :end (:line 43 :character 35)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 49 :character 23) :end (:line 49 :character 32)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 55 :character 23) :end (:line 55 :character 36)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 65 :character 12) :end (:line 65 :character 32)) :code "double_quoted_strings" :severity 2)]))
  jsonrpc-connection-receive(#<eglot-lsp-server eglot-lsp-server-2429718> (:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params (:uri "file:///c:/path/to/file.pp" :diagnostics [(:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 35 :character 30) :end (:line 35 :character 52)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 38 :character 30) :end (:line 38 :character 108)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 43 :character 23) :end (:line 43 :character 35)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 49 :character 23) :end (:line 49 :character 32)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 55 :character 23) :end (:line 55 :character 36)) :code "double_quoted_strings" :severity 2) (:source "Puppet" :message "double quoted string containing no variables" :range (:start (:line 65 :character 12) :end (:line 65 :character 32)) :code "double_quoted_strings" :severity 2)])))
  jsonrpc--process-filter(#<process EGLOT (puppet/puppet-mode)> "Content-Length: 1378\15\n\15\n{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/publishDiagnostics\",\"params\":{\"uri\":\"file:///c:/path/to/file.pp\",\"diagnostics\":[{\"source\":\"Puppet\",\"message\":\"double quoted string containing no variables\",\"range\":{\"start\":{\"line\":35,\"character\":30},\"end\":{\"line\":35,\"character\":52}},\"code\":\"double_quoted_strings\",\"severity\":2},{\"source\":\"Puppet\",\"message\":\"double quoted string containing no variables\",\"range\":{\"start\":{\"line\":38,\"character\":30},\"end\":{\"line\":38,\"character\":108}},\"code\":\"double_quoted_strings\",\"severity\":2},{\"source\":\"Puppet\",\"message\":\"double quoted string containing no variables\",\"range\":{\"start\":{\"line\":43,\"character\":23},\"end\":{\"line\":43,\"character\":35}},\"code\":\"double_quoted_strings\",\"severity\":2},{\"source\":\"Puppet\",\"message\":\"double quoted string containing no variables\",\"range\":{\"start\":{\"line\":49,\"character\":23},\"end\":{\"line\":49,\"character\":32}},\"code\":\"double_quoted_strings\",\"severity\":2},{\"source\":\"Puppet\",\"message\":\"double quoted string containing no variables\",\"range\":{\"start\":{\"line\":55,\"character\":23},\"end\":{\"line\":55,\"character\":36}},\"code\":\"double_quoted_strings\",\"severity\":2},{\"source\":\"Puppet\",\"message\":\"double quoted string containing no variables\",\"range\":{\"start\":{\"line\":65,\"character\":12},\"end\":{\"line\":65,\"character\":32}},\"code\":\"double_quoted_strings\",\"severity\":2}]}}")
```

**Comment by joaotavora** [comment] 2018-09-07 11:08
This is most probably a duplicate of #21 and #28.  Please check those issues and the version of Emacs you are using: it shouldn't happen either with the release 26.1 or with a recent enough 27.0 (master).  Thanks.

**Comment by joaotavora** [comment] 2018-09-07 11:10
Also, what's up with the programatic `(eglot)` call? It doesn't work like that.  

Are you sure you're not calling it interactively with `M-x eglot` or some other variation?

**Comment by bradyt** [comment] 2018-12-26 21:51
@jleechpe, I added to discussion at https://github.com/joaotavora/eglot/issues/28. Can you try the [emacs-27 snapshot installer](http://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-27/emacs-27.0.50-snapshot-2018-10-05-x86_64-installer.exe) at http://alpha.gnu.org/gnu/emacs/pretest/windows/? I think the number or arguments error is resolved there.

**Comment by nemethf** [comment] 2020-01-14 18:35
All of the referenced issues are now closed.  @jleechpe, do you still see the problem or can we close this issue as well?

**Comment by nemethf** [comment] 2020-05-10 09:21
I go ahead and close this issue.  If you still see the problem, comment here and I reopen it.

**Closed by nemethf** 2020-05-10 09:21 UTC
