### ISSUE TITLE
Ocasional emacs crash with company-mode and company-quickhelp

### ISSUE THREAD

**Issue by lxbarbosa** [joaotavora/eglot#183] opened 2018-12-12 02:48 UTC
**EDITED:**
Hi, 

I have been experiencing company randomly crashing Emacs that I can not always reproduce..

I did try six times to reproduce this issue.

The first two and six attempt crashed emacs. 

After that, Emacs did not crash anymore! Talk about weird! 

FIRST: https://streamable.com/4oie3 (crash emacs)
THIRD: https://streamable.com/1gokd (dont crash emacs)
_30s each video_ 

Following your instruction I have installed **company**, **company-quickhelp** and **eglot** with  _emacs -Q_.

**Steps to reproduce:**

```
(package-initialize)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)
(package-refresh-contents)
(package-install 'eglot)
(package-install 'company-mode)
(package-install 'company-quickhelp)
```  
_Open java file_
```  
(require 'company-mode)
(require 'company-quick-mode)
(require 'eglot)
```  

_java servers loads_
type "Sys": https://i.ibb.co/7498K26/shot-2018-12-12-T20-55-20-02-00.png
hitting **c-g** crash emacs! 
```  
PS: Company complete list dont crash Emacs after c-g.

``` 
Debian SID
T430
Emacs 26.1 ( guix )
Eclipse-server version:v20180922-1751
```

**Comment by joaotavora** [comment] 2018-12-12 09:44
I don't understand something.

First you were looking for an Emacs crash right? It didn't happen right? Good :-)

Then, that's precisely the idea behind `company-idle-delay`

```
company-idle-delay is a variable defined in `company.el'.
Its value is 0.5

Documentation:
The idle delay in seconds until completion starts automatically.
The prefix still has to satisfy `company-minimum-prefix-length' before that
happens.  The value of nil means no idle completion.

You can customize this variable.

[back]
```

So I am going to close this and will reopen when you explain what the problem is, OK?  Thanks.

**Comment by joaotavora** [comment] 2018-12-12 09:45
Oops I just noticed your edit about the crashes. A simple question: do any of those crashes happen in your minimal/controlled Emacs -Q environment?

**Comment by eubarbosa** [comment] 2018-12-12 13:39
@joaotavora 
Yes, but they are so random that I can't pinpoint what is happening. I guess I have to wait someone having the same issue!

**Comment by joaotavora** [comment] 2018-12-12 14:56
So just to confirm, one more time: the crashes happen in the controlled Emacs -Q environment with a very small `.emacs`.

If so, can you tell me which operating system and/or emacs version you are using?

**Comment by eubarbosa** [comment] 2018-12-12 19:38
@joaotavora 

Yes. I even moved all folders inside .emacs.d to confirm, downloaded all those packages, tried at least six times.

The first three attempt crashed emacs. 

That is it! 

``` 
Debian SID
T430
Emacs 26.1 ( guix )
```

**Comment by eubarbosa** [comment] 2018-12-12 22:51
@joaotavora 
Edited and added more info as some small screencast confirming the issue!

**Comment by joaotavora** [comment] 2019-10-24 12:01
@lxbarbosa pretty sure this doesn't happen anymore (though if you could retest that would be great).

**Closed by joaotavora** 2019-10-24 12:01 UTC

**Comment by zachravingsmiles** [comment] 2020-01-23 16:36
I'm fairly sure I had just had this crash. I know it was related to company mode

**Comment by joaotavora** [comment] 2020-01-23 16:37
@zachravingsmiles What is the Emacs version you are using?

**Comment by zachravingsmiles** [comment] 2020-01-30 01:02
Sorry for the delay. Emacs 26.3 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.13)

After company mode delay, the items populated. Upon pressing the esc key a few times my emacs crashed. I cannot reproduce for the life of me. It may not even be worth bringing it up.
